policy_id: baseline_intensity_policy_5A
version: v1

scale_source_field: weekly_volume_expected
scale_units: arrivals_per_local_week
lambda_units_local: expected_arrivals_per_local_week_bucket

shape_sum_abs_tol: 0.000001
weekly_sum_rel_tol: 0.000001

clip_mode: hard_fail

hard_limits:
  max_lambda_per_bucket: 200000.0
  max_weekly_volume_expected: 2000000.0

utc_projection:
  emit_utc_baseline: false
