semver: 1.0.0
version: 2024-Q4
defaults:
  total_obs: 100000
  min_obs_per_pair: 50
  epsilon_share: 1.0e-06
currencies:
  AED:
    iso:
    - AE
  AFN:
    iso:
    - AF
  ALL:
    iso:
    - AL
  AMD:
    iso:
    - AM
  AOA:
    iso:
    - AO
  ARS:
    iso:
    - AR
  AUD:
    iso:
    - AU
    - CC
    - CX
    - HM
    - KI
    - NF
    - NR
    - TV
  AWG:
    iso:
    - AW
  AZN:
    iso:
    - AZ
  BAM:
    iso:
    - BA
  BBD:
    iso:
    - BB
  BDT:
    iso:
    - BD
  BGN:
    iso:
    - BG
  BHD:
    iso:
    - BH
  BIF:
    iso:
    - BI
  BMD:
    iso:
    - BM
  BND:
    iso:
    - BN
  BOB:
    iso:
    - BO
  BRL:
    iso:
    - BR
  BSD:
    iso:
    - BS
  BWP:
    iso:
    - BW
  BYN:
    iso:
    - BY
  BZD:
    iso:
    - BZ
  CAD:
    iso:
    - CA
  CDF:
    iso:
    - CD
  CHF:
    iso:
    - CH
    - LI
  CLP:
    iso:
    - CL
  CNY:
    iso:
    - CN
  COP:
    iso:
    - CO
  CRC:
    iso:
    - CR
  CUP:
    iso:
    - CU
  CVE:
    iso:
    - CV
  CZK:
    iso:
    - CZ
  DJF:
    iso:
    - DJ
  DKK:
    iso:
    - DK
    - FO
    - GL
  DOP:
    iso:
    - DO
  DZD:
    iso:
    - DZ
  EGP:
    iso:
    - EG
  ERN:
    iso:
    - ER
  ETB:
    iso:
    - ET
  EUR:
    iso:
    - AD
    - AT
    - AX
    - BE
    - BL
    - CY
    - DE
    - EE
    - ES
    - EU
    - FI
    - FR
    - GF
    - GP
    - GR
    - HR
    - IE
    - IT
    - LT
    - LU
    - LV
    - MC
    - ME
    - MF
    - MQ
    - MT
    - NL
    - PM
    - PT
    - RE
    - SI
    - SK
    - SM
    - TF
    - VA
    - YT
    total_obs: 200000
  FJD:
    iso:
    - FJ
  FKP:
    iso:
    - FK
  GBP:
    iso:
    - GB
    - GG
    - IM
    - JE
    total_obs: 80000
  GEL:
    iso:
    - GE
  GHS:
    iso:
    - GH
  GIP:
    iso:
    - GI
  GMD:
    iso:
    - GM
  GNF:
    iso:
    - GN
  GTQ:
    iso:
    - GT
  GYD:
    iso:
    - GY
  HKD:
    iso:
    - HK
  HNL:
    iso:
    - HN
  HTG,USD:
    iso:
    - HT
  HUF:
    iso:
    - HU
  IDR:
    iso:
    - ID
  ILS:
    iso:
    - IL
  INR:
    iso:
    - IN
  INR,BTN:
    iso:
    - BT
  IQD:
    iso:
    - IQ
  IRR:
    iso:
    - IR
  ISK:
    iso:
    - IS
  JMD:
    iso:
    - JM
  JOD:
    iso:
    - JO
  JPY:
    iso:
    - JP
  KES:
    iso:
    - KE
  KGS:
    iso:
    - KG
  KHR:
    iso:
    - KH
  KMF:
    iso:
    - KM
  KPW:
    iso:
    - KP
  KRW:
    iso:
    - KR
  KWD:
    iso:
    - KW
  KYD:
    iso:
    - KY
  KZT:
    iso:
    - KZ
  LAK:
    iso:
    - LA
  LBP:
    iso:
    - LB
  LKR:
    iso:
    - LK
  LRD:
    iso:
    - LR
  LSL,ZAR:
    iso:
    - LS
  LYD:
    iso:
    - LY
  MAD:
    iso:
    - EH
    - MA
  MDL:
    iso:
    - MD
  MGA:
    iso:
    - MG
  MKD:
    iso:
    - MK
  MMK:
    iso:
    - MM
  MNT:
    iso:
    - MN
  MOP:
    iso:
    - MO
  MRU:
    iso:
    - MR
  MUR:
    iso:
    - MU
  MVR:
    iso:
    - MV
  MWK:
    iso:
    - MW
  MXN:
    iso:
    - MX
  MYR:
    iso:
    - MY
  MZN:
    iso:
    - MZ
  NAD,ZAR:
    iso:
    - NA
  NGN:
    iso:
    - NG
  NIO:
    iso:
    - NI
  NOK:
    iso:
    - BV
    - 'NO'
    - SJ
  NPR:
    iso:
    - NP
  NZD:
    iso:
    - CK
    - NU
    - NZ
    - PN
    - TK
  OMR:
    iso:
    - OM
  PAB,USD:
    iso:
    - PA
  PEN:
    iso:
    - PE
  PGK:
    iso:
    - PG
  PHP:
    iso:
    - PH
  PKR:
    iso:
    - PK
  PLN:
    iso:
    - PL
  PYG:
    iso:
    - PY
  QAR:
    iso:
    - QA
  RON:
    iso:
    - RO
  RSD:
    iso:
    - RS
  RUB:
    iso:
    - RU
  RWF:
    iso:
    - RW
  SAR:
    iso:
    - SA
  SBD:
    iso:
    - SB
  SCR:
    iso:
    - SC
  SDG:
    iso:
    - SD
  SEK:
    iso:
    - SE
  SGD:
    iso:
    - SG
  SHP:
    iso:
    - SH
  SLE:
    iso:
    - SL
  SOS:
    iso:
    - SO
  SRD:
    iso:
    - SR
  SSP:
    iso:
    - SS
  STN:
    iso:
    - ST
  SVC,USD:
    iso:
    - SV
  SYP:
    iso:
    - SY
  SZL:
    iso:
    - SZ
  THB:
    iso:
    - TH
  TJS:
    iso:
    - TJ
  TMT:
    iso:
    - TM
  TND:
    iso:
    - TN
  TOP:
    iso:
    - TO
  TRY:
    iso:
    - TR
  TTD:
    iso:
    - TT
  TWD:
    iso:
    - TW
  TZS:
    iso:
    - TZ
  UAH:
    iso:
    - UA
  UGX:
    iso:
    - UG
  USD:
    iso:
    - AQ
    - AS
    - BQ
    - EC
    - FM
    - GS
    - GU
    - IO
    - MH
    - MP
    - OE
    - PR
    - PS
    - PW
    - TC
    - TL
    - UM
    - US
    - VG
    - VI
    - XC
    - XE
    - XF
    - XG
    - XH
    - XI
    - XJ
    - XK
    - XL
    - XO
    - XP
    - XQ
    - XU
    - ZF
    - ZG
    - ZH
    - ZI
    - ZJ
    - ZQ
    - ZT
    total_obs: 150000
  UYU,UYW:
    iso:
    - UY
  UZS:
    iso:
    - UZ
  VES,VED:
    iso:
    - VE
  VND:
    iso:
    - VN
  VUV:
    iso:
    - VU
  WST:
    iso:
    - WS
  XAF:
    iso:
    - CF
    - CG
    - CM
    - GA
    - GQ
    - TD
  XCD:
    iso:
    - AG
    - AI
    - DM
    - GD
    - KN
    - LC
    - MS
    - VC
  XCG:
    iso:
    - CW
    - SX
  XOF:
    iso:
    - BF
    - BJ
    - CI
    - GW
    - ML
    - NE
    - SN
    - TG
  XPF:
    iso:
    - NC
    - PF
    - WF
  YER:
    iso:
    - YE
  ZAR:
    iso:
    - ZA
  ZMW:
    iso:
    - ZM
  ZWG:
    iso:
    - ZW
