semver: 1.0.0
version: '2025-12-31'
metadata:
  simulation_manifest: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084401Z/manifest.json
  simulation_config_path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/models/hurdle/hurdle_simulation.priors.yaml
  seed: 9248923
  created_utc: 20251231T084401Z
  inputs:
    priors:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/models/hurdle/hurdle_simulation.priors.yaml
      sha256: e7c82d4a13057774789c3b1d25dd4eac6dd832956b49425b83c6a14d7d26780e
    transaction_schema_merchant_ids:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/layer1/transaction_schema_merchant_ids/2025-12-31/transaction_schema_merchant_ids.parquet
      sha256: a5ce122a1c61a4247ba4ece8624a201fe824c72c10f352cfba74623e54a0cb12
    world_bank_gdp_per_capita:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/world_bank_gdp_per_capita/2025-04-15/gdp.parquet
      sha256: 1eb6d9ae47639b17fd41e7875c03247c4133a849b442c0e3ebe61a4cb2c06074
    gdp_bucket_map:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/gdp_bucket_map/2024/gdp_bucket_map.parquet
      sha256: 624c9d1029e81980c7d7eb368a7ed07d67c62d8423d0c053cdcd9c58a6c80a3b
    iso3166_canonical:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/iso/iso3166_canonical/2024-12-31/iso3166.parquet
      sha256: bfb68d1770abef6a74571cfea4d659eefb7b6c7b39e81f1b6cc483bd60bd8b5f
    logistic:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084401Z/logistic.parquet
      sha256: da7fdbd584b2d12f7b76d638b9549cbe67bc1e970dbdb92bb81fb70ddcf4b99a
    nb_mean:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084401Z/nb_mean.parquet
      sha256: b8fc131dd597037356979e754899f1ac77c8ba4832d243f5b49530634f68c653
dict_mcc:
- 742
- 743
- 744
- 763
- 780
- 1520
- 1711
- 1731
- 1740
- 1750
- 1761
- 1771
- 1799
- 2741
- 2791
- 2842
- 4011
- 4111
- 4112
- 4119
- 4121
- 4131
- 4214
- 4215
- 4225
- 4411
- 4457
- 4468
- 4511
- 4582
- 4722
- 4784
- 4789
- 4812
- 4814
- 4815
- 4816
- 4821
- 4829
- 4899
- 4900
- 5013
- 5021
- 5039
- 5044
- 5045
- 5046
- 5047
- 5051
- 5065
- 5072
- 5074
- 5085
- 5094
- 5099
- 5111
- 5122
- 5131
- 5137
- 5139
- 5169
- 5172
- 5192
- 5193
- 5198
- 5199
- 5200
- 5211
- 5231
- 5251
- 5261
- 5262
- 5271
- 5300
- 5309
- 5310
- 5311
- 5331
- 5399
- 5411
- 5422
- 5441
- 5451
- 5462
- 5499
- 5511
- 5521
- 5531
- 5532
- 5533
- 5541
- 5542
- 5551
- 5552
- 5561
- 5571
- 5592
- 5598
- 5599
- 5611
- 5621
- 5631
- 5641
- 5651
- 5655
- 5661
- 5681
- 5691
- 5697
- 5698
- 5699
- 5712
- 5713
- 5714
- 5715
- 5718
- 5719
- 5722
- 5732
- 5733
- 5734
- 5735
- 5811
- 5812
- 5813
- 5814
- 5815
- 5816
- 5817
- 5818
- 5912
- 5921
- 5931
- 5932
- 5933
- 5935
- 5937
- 5940
- 5941
- 5942
- 5943
- 5944
- 5945
- 5946
- 5947
- 5948
- 5949
- 5950
- 5960
- 5962
- 5963
- 5964
- 5965
- 5966
- 5967
- 5968
- 5969
- 5970
- 5971
- 5972
- 5973
- 5975
- 5976
- 5977
- 5978
- 5983
- 5992
- 5993
- 5994
- 5995
- 5996
- 5997
- 5998
- 5999
- 6010
- 6011
- 6012
- 6051
- 6211
- 6300
- 7011
- 7012
- 7032
- 7033
- 7210
- 7211
- 7216
- 7217
- 7221
- 7230
- 7251
- 7261
- 7273
- 7276
- 7277
- 7278
- 7296
- 7297
- 7298
- 7299
- 7311
- 7321
- 7322
- 7333
- 7338
- 7339
- 7342
- 7349
- 7361
- 7372
- 7375
- 7379
- 7392
- 7393
- 7394
- 7395
- 7399
- 7512
- 7513
- 7519
- 7523
- 7531
- 7534
- 7535
- 7538
- 7542
- 7549
- 7622
- 7623
- 7629
- 7631
- 7641
- 7692
- 7699
- 7800
- 7801
- 7802
- 7829
- 7832
- 7841
- 7911
- 7922
- 7929
- 7932
- 7933
- 7941
- 7991
- 7992
- 7993
- 7994
- 7995
- 7996
- 7997
- 7998
- 7999
- 8011
- 8021
- 8031
- 8041
- 8042
- 8043
- 8049
- 8050
- 8062
- 8071
- 8099
- 8111
- 8211
- 8220
- 8241
- 8244
- 8249
- 8299
- 8351
- 8398
- 8641
- 8651
- 8661
- 8675
- 8699
- 8734
- 8911
- 8931
- 8999
- 9211
- 9222
- 9223
- 9311
- 9399
- 9402
dict_ch:
- CP
- CNP
design:
  beta_phi_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
  - ln_gdp_pc_usd_2015
beta_phi:
- 1.2594673852479923
- -0.04519466841161407
- -0.0444778486090375
- -0.04562871216460825
- -0.04539321384924821
- -0.04626893315414837
- -0.04614447877040163
- -0.045903063739660306
- -0.04652281750086931
- -0.044417136071174194
- -0.04549191808010669
- -0.04583042176400983
- -0.045597518059733125
- -0.046735739534073784
- -0.045250022667059436
- -0.04508187331427138
- -0.04644666267237498
- -0.046171543200120076
- -0.04586188023995012
- -0.044862519269373215
- -0.044906918408703554
- -0.04542864837645762
- -0.046181410323183146
- -0.04492296690669542
- -0.04480939235039832
- -0.045097744675364954
- -0.04534642377557794
- -0.045643741933321554
- -0.04567098341858534
- -0.045488568065459915
- -0.04605781565790392
- -0.045794001680064526
- -0.04553923302403028
- -0.044334183561230124
- -0.045545237027545885
- -0.04631651689078705
- -0.04533069002504589
- -0.04564719019578684
- -0.04591122384996998
- -0.04569403221450972
- -0.04415041581940397
- -0.04603447146102484
- -0.044880161230275654
- -0.04640542001196642
- -0.04614989785565932
- -0.044872670265808164
- -0.04552452458713899
- -0.04466944130100523
- -0.04525056785690736
- -0.04524806369962237
- -0.046376849349128
- -0.04610106072060216
- -0.04625996094709231
- -0.04555663687172724
- -0.04555377485460943
- -0.04518501450705219
- -0.04620242570608752
- -0.04576243341810963
- -0.04652268552797141
- -0.045786254524637186
- -0.04599651251842771
- -0.04509049506138071
- -0.04614233565298259
- -0.04602808209486974
- -0.04602251994271295
- -0.04489877200104499
- -0.04495282206805375
- -0.04542574312070291
- -0.04681569032143958
- -0.046165310219502334
- -0.045142167660047985
- -0.04580749039169262
- -0.045548868213760495
- -0.04582803652562404
- -0.046213196921816385
- -0.04547332778882146
- -0.044944903850727
- -0.04583210371845893
- -0.04576658090473543
- -0.045059569134619414
- 0.4944469110215907
- 0.6614215069606403
- 0.15388229460151176
- 0.25401452577687594
- 0.38844432896432035
- 1.0605477256187812
- 0.5205790159307303
- -0.03917852464929611
- 0.213903872281892
- -0.015408737944782445
- -0.04520984384541003
- -0.045672089847424026
- 0.33530574174516786
- -0.045427417687424705
- 0.42251352736608744
- 1.3800255972913313
- 1.1468033041325916
- 0.5543227863958516
- -0.045319865190748126
- 0.24823055012492928
- -0.04503100110483413
- -0.045727341681145874
- -0.04580307471250977
- -0.04590984964062984
- -0.04450132388981043
- -0.04529167063637038
- -0.04617039298495298
- -0.04564698992903688
- -0.04513783362917088
- -0.04527245742766502
- -0.0465734723307759
- -0.0441902811304134
- -0.04570009524936946
- -0.045721275699976936
- -0.0459878848000471
- -0.04700462430990091
- -0.04451786316057427
- -0.04538121110912096
- -0.04586298507526691
- -0.04492124894551089
- -0.0459877905139694
- -0.04527495629639811
- -0.04572588296587242
- 1.5766289213436933
- 1.3460282298182007
- 0.7110808842003401
- -0.04604070647026166
- 0.5531305613050864
- 0.06583291934870764
- -0.043429987510979616
- 1.3996514315025077
- -0.04507020748048425
- -0.04515835368465863
- -0.04592317603401118
- -0.04563753375780556
- -0.04504131886813744
- -0.04553617631262677
- -0.04520057002239388
- -0.04506680426030606
- -0.046441232708633665
- -0.04600102540634496
- -0.044746604490125554
- -0.045876636900349065
- -0.04636252399009405
- -0.046238115744727214
- -0.04471133106384549
- -0.046083544536478775
- -0.046375769082532374
- -0.04465355906500097
- -0.045553544710973184
- -0.045472693756046866
- -0.04596790885531606
- -0.04639492412097995
- -0.045971367446540456
- -0.045579845289795834
- -0.04601726858917954
- -0.045598967057529256
- -0.04579254238344749
- -0.04564180188469031
- -0.045091856113512886
- -0.04440216806893206
- -0.04579877138760117
- -0.04542396910184363
- -0.04511078176813579
- -0.04640449274898278
- -0.04647753822035735
- -0.04592796479101027
- -0.04552975613255322
- -0.04565510399738843
- -0.04557613621942876
- -0.045333958045247556
- -0.0454852053363865
- -0.04567851798695849
- -0.04552014240126026
- -0.04602489753703631
- -0.04479002010106854
- -0.04401101510425614
- -0.04582686906223435
- -0.04498091196247187
- -0.046300358374307904
- -0.04613252992015186
- -0.045369338068620334
- -0.04538684496128308
- -0.04493206861771093
- -0.04546715030813208
- -0.046103227584846466
- -0.04636114198899541
- -0.045076895908543024
- -0.04630017132390575
- -0.04411509120672748
- -0.04471351997806014
- -0.046208272363131686
- -0.04613721633356846
- -0.045962307106926927
- -0.04400417903895366
- -0.04590885446160485
- -0.04566848870292274
- -0.04604121755833442
- -0.046309178798098594
- -0.04615094910734388
- -0.04514968379117772
- -0.045383777821373344
- -0.04513845206352319
- -0.0459365779622212
- -0.044443674271819465
- -0.046880734343173636
- -0.04656368648294861
- -0.04593018219120743
- -0.045191941464841394
- -0.04518782226757732
- -0.046163864017615866
- -0.045384313879145814
- -0.044555234080146715
- -0.044791675265379145
- -0.04626911364758508
- -0.046092380370589735
- -0.045805902689093216
- -0.04471856160797853
- -0.04588343156999104
- -0.04669030251608506
- -0.045183300068928664
- -0.046083315323322695
- -0.04553957522188913
- -0.04409119025718624
- -0.0462836683732941
- -0.04686627360016724
- -0.045502470714992575
- -0.04606950983027955
- -0.045597513703896586
- -0.04620535724908892
- -0.045391049315119725
- -0.045818900273315775
- -0.04558879802028271
- -0.04509073034322457
- -0.043400946350277074
- -0.0446002401320165
- -0.045740333460742445
- -0.04644141072520814
- -0.04543566095962154
- -0.04437991349679408
- -0.046592857213740846
- -0.04552633250019607
- -0.046369086721475127
- -0.04565442241636078
- -0.04604470202407945
- -0.04560662692313828
- -0.04615471535248404
- -0.04602361534278201
- -0.0457643752402763
- -0.045021947620309526
- -0.04547963584135256
- -0.04536925638386013
- -0.04438674092954882
- -0.04568179016729949
- -0.046614708058310764
- -0.04445384529682529
- -0.044980038309556894
- -0.046752783238077564
- -0.046831329317058565
- -0.04523414577356773
- -0.04542220122062671
- -0.04656431710986582
- -0.045705826326311705
- -0.045900427674764564
- -0.0463774530687467
- -0.04589363051308098
- -0.04556544979986049
- -0.045565486429982406
- -0.04563117418849256
- -0.046244914083276356
- -0.04457764691328211
- -0.04450561508944736
- -0.04553426828392885
- -0.04661767528846686
- -0.04412377148444398
- -0.045362015411916465
- -0.04631296526117882
- -0.04560158161349118
- -0.04461272707295312
- -0.04643468871563822
- -0.044593363115976975
- -0.046897827059686606
- -0.045911481542592676
- -0.045185536871581146
- -0.04575783629402369
- -0.0474840678388844
- -0.043185620374711596
- 0.0
- -0.04695511671625018
- -0.04482213454921918
- -0.04652764695557491
- 0.0
- 1.2594652069187684
- 0.0011570854967934588
