semver: 1.0.0
version: '2026-01-03'
metadata:
  simulation_manifest: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2026-01-03/seed=9248923/20260103T175111Z/manifest.json
  simulation_config_path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/layer1/1A/models/hurdle/hurdle_simulation.priors.yaml
  seed: 9248923
  created_utc: 20260103T175111Z
  inputs:
    priors:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/layer1/1A/models/hurdle/hurdle_simulation.priors.yaml
      sha256: 7588df761e0c4ba3f09adced410db1ffb79fd7236b2ad99c6ef0362a230fa119
    transaction_schema_merchant_ids:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/layer1/transaction_schema_merchant_ids/2026-01-03/transaction_schema_merchant_ids.parquet
      sha256: df2f940f061a09a018e133828c9b7b2e7e442a1052b5c0105ef927e2b7c696e8
    world_bank_gdp_per_capita:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/world_bank_gdp_per_capita/2025-04-15/gdp.parquet
      sha256: 1eb6d9ae47639b17fd41e7875c03247c4133a849b442c0e3ebe61a4cb2c06074
    gdp_bucket_map:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/gdp_bucket_map/2024/gdp_bucket_map.parquet
      sha256: 624c9d1029e81980c7d7eb368a7ed07d67c62d8423d0c053cdcd9c58a6c80a3b
    iso3166_canonical:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/iso/iso3166_canonical/2024-12-31/iso3166.parquet
      sha256: bfb68d1770abef6a74571cfea4d659eefb7b6c7b39e81f1b6cc483bd60bd8b5f
    logistic:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2026-01-03/seed=9248923/20260103T175111Z/logistic.parquet
      sha256: e52e774343461db1071bf79d8166bc90e4ee9a78a43c935bb1ae0780afd05b00
    nb_mean:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2026-01-03/seed=9248923/20260103T175111Z/nb_mean.parquet
      sha256: 4e7ca3ee110b8dfb22d66b55dfcfa5264efc0a5d12202591c5301e023a51aea7
dict_mcc:
- 742
- 743
- 744
- 763
- 780
- 1520
- 1711
- 1731
- 1740
- 1750
- 1761
- 1771
- 1799
- 2741
- 2791
- 2842
- 4011
- 4111
- 4112
- 4119
- 4121
- 4131
- 4214
- 4215
- 4225
- 4411
- 4457
- 4468
- 4511
- 4582
- 4722
- 4784
- 4789
- 4812
- 4814
- 4815
- 4816
- 4821
- 4829
- 4899
- 4900
- 5013
- 5021
- 5039
- 5044
- 5045
- 5046
- 5047
- 5051
- 5065
- 5072
- 5074
- 5085
- 5094
- 5099
- 5111
- 5122
- 5131
- 5137
- 5139
- 5169
- 5172
- 5192
- 5193
- 5198
- 5199
- 5200
- 5211
- 5231
- 5251
- 5261
- 5262
- 5271
- 5300
- 5309
- 5310
- 5311
- 5331
- 5399
- 5411
- 5422
- 5441
- 5451
- 5462
- 5499
- 5511
- 5521
- 5531
- 5532
- 5533
- 5541
- 5542
- 5551
- 5552
- 5561
- 5571
- 5592
- 5598
- 5599
- 5611
- 5621
- 5631
- 5641
- 5651
- 5655
- 5661
- 5681
- 5691
- 5697
- 5698
- 5699
- 5712
- 5713
- 5714
- 5715
- 5718
- 5719
- 5722
- 5732
- 5733
- 5734
- 5735
- 5811
- 5812
- 5813
- 5814
- 5815
- 5816
- 5817
- 5818
- 5912
- 5921
- 5931
- 5932
- 5933
- 5935
- 5937
- 5940
- 5941
- 5942
- 5943
- 5944
- 5945
- 5946
- 5947
- 5948
- 5949
- 5950
- 5960
- 5962
- 5963
- 5964
- 5965
- 5966
- 5967
- 5968
- 5969
- 5970
- 5971
- 5972
- 5973
- 5975
- 5976
- 5977
- 5978
- 5983
- 5992
- 5993
- 5994
- 5995
- 5996
- 5997
- 5998
- 5999
- 6010
- 6011
- 6012
- 6051
- 6211
- 6300
- 7011
- 7012
- 7032
- 7033
- 7210
- 7211
- 7216
- 7217
- 7221
- 7230
- 7251
- 7261
- 7273
- 7276
- 7277
- 7278
- 7296
- 7297
- 7298
- 7299
- 7311
- 7321
- 7322
- 7333
- 7338
- 7339
- 7342
- 7349
- 7361
- 7372
- 7375
- 7379
- 7392
- 7393
- 7394
- 7395
- 7399
- 7512
- 7513
- 7519
- 7523
- 7531
- 7534
- 7535
- 7538
- 7542
- 7549
- 7622
- 7623
- 7629
- 7631
- 7641
- 7692
- 7699
- 7800
- 7801
- 7802
- 7829
- 7832
- 7841
- 7911
- 7922
- 7929
- 7932
- 7933
- 7941
- 7991
- 7992
- 7993
- 7994
- 7995
- 7996
- 7997
- 7998
- 7999
- 8011
- 8021
- 8031
- 8041
- 8042
- 8043
- 8049
- 8050
- 8062
- 8071
- 8099
- 8111
- 8211
- 8220
- 8241
- 8244
- 8249
- 8299
- 8351
- 8398
- 8641
- 8651
- 8661
- 8675
- 8699
- 8734
- 8911
- 8931
- 8999
- 9211
- 9222
- 9223
- 9311
- 9399
- 9402
dict_ch:
- CP
- CNP
design:
  beta_phi_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
  - ln_gdp_pc_usd_2015
beta_phi:
- 1.6526973503532505
- 0.005755363156265243
- 0.0057619159563683815
- 0.005767636161108572
- 0.005765287568429792
- 0.005760801630838997
- 0.005758652079320699
- 0.00575574361758825
- 0.005761524605602276
- 0.0057563450417637135
- 0.005754179553396254
- 0.005762596197013031
- 0.0057592172214074745
- 0.0057546232972251485
- 0.005751673237967369
- 0.005772088096854034
- 0.005751353511395474
- 0.005758047758444295
- 0.005755558007635898
- 0.0057650375229579675
- 0.00575920172719178
- 0.005760221953998443
- 0.005760101485520894
- 0.005752914111345779
- 0.005759148129196362
- 0.005757350445219239
- 0.005757160611405535
- 0.005751652373535756
- 0.005759406631140799
- 0.005757014484557966
- 0.005756768971607151
- 0.00575891640455569
- 0.005757628979905524
- 0.005760227834184584
- 0.005763172024252564
- 0.005764298297945783
- 0.0
- 0.005760747689777165
- 0.005760087941699248
- 0.005762081554750923
- 0.005754918119912421
- 0.005756193363670183
- 0.005757046289793816
- 0.005756986888563546
- 0.005759472821298982
- 0.005764794479127227
- 0.005751236904306461
- 0.005756459775463503
- 0.005761068015603023
- 0.0057614746629268965
- 0.0057789587359416104
- 0.0057559751833194915
- 0.0057572316689548245
- 0.0057538128644162335
- 0.005759674048191078
- 0.005750202792557966
- 0.005767665178550604
- 0.005756947954458272
- 0.005762497965348414
- 0.005766749464944217
- 0.00575344802018957
- 0.0057615200033463675
- 0.005774026366365915
- 0.0057568727098644586
- 0.005759650314140284
- 0.005759131502610618
- 0.005762421334888468
- 0.00575080907384838
- 0.005757500952813955
- 0.005753789996199523
- 0.005757040956736801
- 0.005762931338567084
- 0.005755283933245982
- 0.0057529813420473565
- 0.0057578915016951926
- 0.005762491342236514
- 0.005755323138719837
- 0.005759379606116832
- 0.005759817738451704
- 0.005753648638074055
- 0.00575411698554266
- 0.005764836065463002
- 0.0057560177759969095
- 0.005762968964255671
- 0.005760486180920428
- 0.005757642217085972
- 0.005759573162175122
- 0.005757840728026056
- 0.0057580787962872365
- 0.005755991599162885
- 0.00575882666874937
- 0.005757775052744183
- 0.005760577665305114
- 0.005757553936607097
- 0.005760640448743443
- 0.005750969678109639
- 0.0057588265069003115
- 0.0057583305767191706
- 0.005760787307849699
- 0.005755242517169048
- 0.005757741595414298
- 0.005764306422108736
- 0.0057591779751055144
- 0.005756776650077522
- 0.005754009128790577
- 0.005758109400289169
- 0.005754271207378346
- 0.005768359096611352
- 0.005757835233630137
- 0.005766024715276663
- 0.005753671863480724
- 0.0057591671034170795
- 0.005757440050255948
- 0.00575007426864925
- 0.00576094687854141
- 0.005760138951154394
- 0.005770089301493425
- 0.005759168658794734
- 0.005753113462716773
- 0.0057560886049363965
- 0.005754775489889977
- 0.0057678424466095285
- 0.00575802456812474
- 0.00576417373012159
- 0.00576336187937209
- 0.005757187953698869
- 0.0057559570578944695
- 0.005755504592940946
- 0.005757454383946468
- 0.00576045461756776
- 0.005757689653615294
- 0.005757675038595487
- 0.005757937137868473
- 0.00577457138527315
- 0.005761581727234661
- 0.0057627689996457175
- 0.0057570532257094145
- 0.0057547347265938095
- 0.005751535878084156
- 0.005754054834175074
- 0.005759464628585635
- 0.005752205866826887
- 0.005762303494980501
- 0.005762764744202952
- 0.00575803020514979
- 0.005761829496353603
- 0.005756930589520444
- 0.005755599875741395
- 0.005752111448425915
- 0.005753063571487066
- 0.005758635231144835
- 0.005762937201598683
- 0.005767777226321007
- 0.005757792565903687
- 0.005757010638102183
- 0.005762176754699946
- 0.005757382050428812
- 0.005763431115262472
- 0.0057603777830286425
- 0.005761637093787507
- 0.0057586124655445185
- 0.0057566757054654735
- 0.005760335952366473
- 0.005756775409605065
- 0.005757211724217575
- 0.0057587244972901715
- 0.005757444181875927
- 0.005753639193231232
- 0.005758325185285544
- 0.005762191856725749
- 0.005753676328108246
- 0.005759864220487446
- 0.005753563905835074
- 0.0057688863240839714
- 0.005769625331142553
- 0.005747841497612506
- 0.005752020331091282
- 0.005752810115796006
- 0.005753575842014158
- 0.005757137662831418
- 0.005757835233625669
- 0.005753086835957316
- 0.00576955946369028
- 0.005758453086332387
- 0.005754933266187855
- 0.0057628879314806794
- 0.005754338809465593
- 0.0057630545270793
- 0.005757022667014289
- 0.005762530873564486
- 0.005753564389165676
- 0.005761316685876416
- 0.005755344546457341
- 0.005758816778370095
- 0.005758559637378041
- 0.005753274297357963
- 0.005756388792076261
- 0.005761577507811137
- 0.005755569367424382
- 0.005759085756326564
- 0.005759130993014948
- 0.0057552984460252825
- 0.005760854032102222
- 0.005755930301374409
- 0.005758774150858699
- 0.005756586007753864
- 0.005755837523193186
- 0.005754757126573575
- 0.005759993537278361
- 0.005753279913444391
- 0.00576340596305836
- 0.005757193574477138
- 0.005756705516417062
- 0.00576129152822025
- 0.00576034613126378
- 0.0057558415038940795
- 0.005769015190593872
- 0.005750710225045852
- 0.005754211442197412
- 0.005755107589153717
- 0.005753141579809974
- 0.005759155834651572
- 0.005766003056296255
- 0.005745282708756982
- 0.005755813543214722
- 0.005759183196005327
- 0.005758488342641451
- 0.0057528675057802545
- 0.005757903805006481
- 0.005752837178668179
- 0.00575529551936985
- 0.005759673359113168
- 0.005757216251609825
- 0.005758335938092576
- 0.00575961657877388
- 0.005750649525747817
- 0.0057588780515560765
- 0.005750248318874834
- 0.005758778268611328
- 0.005757614125670796
- 0.005756036132580685
- 0.005756194100649652
- 0.0057580598415726885
- 0.005755595531946255
- 0.005749375948159724
- 0.005757241491555291
- 0.005759874082447423
- 0.00577077939993319
- 0.005752182313620133
- 0.005761776329519
- 0.005755097951539285
- 0.005750761396918438
- 0.005761329757681946
- 0.005755975822798843
- 0.005762468919766539
- 0.005757575040982563
- 0.005764947367623702
- 0.005762044309665863
- 0.005762463025821959
- 0.005756769050282307
- 0.005763216966378003
- 0.005765531930455053
- 0.005762718994237725
- 0.005750074730793789
- 0.00576360956420367
- 0.005763615171409959
- 0.00576033902745953
- 0.0057634000987994635
- 0.005756530563592469
- 0.005749096959738771
- 0.005751441091729401
- 0.005764697784972839
- 0.00575988400316306
- 0.00576960517310112
- 0.005755836485506505
- 0.0
- 0.0057630851762473425
- 0.005759562040007771
- 0.0057624157793894374
- 0.005758679805549592
- 0.005759853581337721
- 0.0057632044820280035
- 0.0
- 0.005764728603630664
- 0.005764007940433967
- 0.005759420156512002
- 0.005747328244972984
- 0.005750905771558339
- 0.005758452304609612
- 0.0057560196027838075
- 0.005753683279384527
- 0.8263497073213745
- 0.82634764574547
- 9.26889212502042e-06
