semver: 1.0.0
version: '2025-12-31'
metadata:
  simulation_manifest: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T073822Z/manifest.json
  simulation_config_path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/models/hurdle/hurdle_simulation.priors.yaml
  seed: 9248923
  created_utc: 20251231T073822Z
  inputs:
    priors:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/models/hurdle/hurdle_simulation.priors.yaml
      sha256: 3033d20210592838bd8dec9e61ce4e737983b8b1a638cfe7364ecc2988ade31a
    transaction_schema_merchant_ids:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/layer1/transaction_schema_merchant_ids/2025-12-31/transaction_schema_merchant_ids.parquet
      sha256: a5ce122a1c61a4247ba4ece8624a201fe824c72c10f352cfba74623e54a0cb12
    world_bank_gdp_per_capita:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/world_bank_gdp_per_capita/2025-04-15/gdp.parquet
      sha256: 1eb6d9ae47639b17fd41e7875c03247c4133a849b442c0e3ebe61a4cb2c06074
    gdp_bucket_map:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/gdp_bucket_map/2024/gdp_bucket_map.parquet
      sha256: 624c9d1029e81980c7d7eb368a7ed07d67c62d8423d0c053cdcd9c58a6c80a3b
    iso3166_canonical:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/iso/iso3166_canonical/2024-12-31/iso3166.parquet
      sha256: bfb68d1770abef6a74571cfea4d659eefb7b6c7b39e81f1b6cc483bd60bd8b5f
    logistic:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T073822Z/logistic.parquet
      sha256: 325a4776e9d18e45438c2ae9c4dec640c43eb1adad08e34ea66b1370b6291f88
    nb_mean:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T073822Z/nb_mean.parquet
      sha256: e5c410ab3da5d86a8fdf09acb27c5516625975b7242f193b43fed566c57ad22e
dict_mcc:
- 742
- 743
- 744
- 763
- 780
- 1520
- 1711
- 1731
- 1740
- 1750
- 1761
- 1771
- 1799
- 2741
- 2791
- 2842
- 4011
- 4111
- 4112
- 4119
- 4121
- 4131
- 4214
- 4215
- 4225
- 4411
- 4457
- 4468
- 4511
- 4582
- 4722
- 4784
- 4789
- 4812
- 4814
- 4815
- 4816
- 4821
- 4829
- 4899
- 4900
- 5013
- 5021
- 5039
- 5044
- 5045
- 5046
- 5047
- 5051
- 5065
- 5072
- 5074
- 5085
- 5094
- 5099
- 5111
- 5122
- 5131
- 5137
- 5139
- 5169
- 5172
- 5192
- 5193
- 5198
- 5199
- 5200
- 5211
- 5231
- 5251
- 5261
- 5262
- 5271
- 5300
- 5309
- 5310
- 5311
- 5331
- 5399
- 5411
- 5422
- 5441
- 5451
- 5462
- 5499
- 5511
- 5521
- 5531
- 5532
- 5533
- 5541
- 5542
- 5551
- 5552
- 5561
- 5571
- 5592
- 5598
- 5599
- 5611
- 5621
- 5631
- 5641
- 5651
- 5655
- 5661
- 5681
- 5691
- 5697
- 5698
- 5699
- 5712
- 5713
- 5714
- 5715
- 5718
- 5719
- 5722
- 5732
- 5733
- 5734
- 5735
- 5811
- 5812
- 5813
- 5814
- 5815
- 5816
- 5817
- 5818
- 5912
- 5921
- 5931
- 5932
- 5933
- 5935
- 5937
- 5940
- 5941
- 5942
- 5943
- 5944
- 5945
- 5946
- 5947
- 5948
- 5949
- 5950
- 5960
- 5962
- 5963
- 5964
- 5965
- 5966
- 5967
- 5968
- 5969
- 5970
- 5971
- 5972
- 5973
- 5975
- 5976
- 5977
- 5978
- 5983
- 5992
- 5993
- 5994
- 5995
- 5996
- 5997
- 5998
- 5999
- 6010
- 6011
- 6012
- 6051
- 6211
- 6300
- 7011
- 7012
- 7032
- 7033
- 7210
- 7211
- 7216
- 7217
- 7221
- 7230
- 7251
- 7261
- 7273
- 7276
- 7277
- 7278
- 7296
- 7297
- 7298
- 7299
- 7311
- 7321
- 7322
- 7333
- 7338
- 7339
- 7342
- 7349
- 7361
- 7372
- 7375
- 7379
- 7392
- 7393
- 7394
- 7395
- 7399
- 7512
- 7513
- 7519
- 7523
- 7531
- 7534
- 7535
- 7538
- 7542
- 7549
- 7622
- 7623
- 7629
- 7631
- 7641
- 7692
- 7699
- 7800
- 7801
- 7802
- 7829
- 7832
- 7841
- 7911
- 7922
- 7929
- 7932
- 7933
- 7941
- 7991
- 7992
- 7993
- 7994
- 7995
- 7996
- 7997
- 7998
- 7999
- 8011
- 8021
- 8031
- 8041
- 8042
- 8043
- 8049
- 8050
- 8062
- 8071
- 8099
- 8111
- 8211
- 8220
- 8241
- 8244
- 8249
- 8299
- 8351
- 8398
- 8641
- 8651
- 8661
- 8675
- 8699
- 8734
- 8911
- 8931
- 8999
- 9211
- 9222
- 9223
- 9311
- 9399
- 9402
dict_ch:
- CP
- CNP
dict_dev5:
- 1
- 2
- 3
- 4
- 5
design:
  beta_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
  - gdp_bucket_onehot([1,2,3,4,5])
  beta_mu_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
beta:
- -0.9766773999266223
- 0.25618448841733943
- -0.42352086314101056
- -0.6723043570286862
- -0.07443138699779256
- 0.1899078251555454
- -0.1471203745370476
- -0.18698076095164143
- -0.018507431893808195
- 0.25408339770328686
- 0.5840576667224735
- 0.12370587470125324
- -0.7936357436355729
- 0.02586196739118751
- -0.7550615812861128
- 0.09895798754508556
- 0.25881129634315553
- -1.0913855415144784
- 0.009362257518454443
- 0.7847756140022263
- 0.7600892667368048
- 0.1359238496733833
- 0.43215052371472695
- 0.39939902842412456
- 0.2174774101311917
- 0.8468999827726875
- 0.3531631048404611
- 0.47942681491140443
- -0.18615357784816955
- -0.8681596924171072
- 0.1990819739786113
- 0.39498606422444976
- -0.2654696556911051
- -0.2897741963629404
- -0.017181593522944592
- 0.5063016849264764
- 0.1967430002590282
- 0.2686928556875002
- 0.49995472101675065
- -0.11486155673075772
- -0.4645549100428424
- -0.19814743611635185
- -0.1150916936962381
- 0.034325567904323014
- 0.3062732726614082
- 0.5357248605831242
- 0.27445679858301886
- 0.09782987863766371
- 0.16510069179918713
- 0.16549380522542334
- -0.006911514545227531
- 0.32498215979034767
- 0.1013506719389784
- -0.11932891554733321
- 0.20443690557524102
- 0.3825198509004221
- 0.37417226715946866
- 0.2512076960943089
- 0.2631387734912809
- -0.2434824865945423
- 0.17067050383743435
- 0.04091544969680797
- 0.10088451859911296
- -0.2659388005246297
- 0.18431605256624378
- -0.24257843706620888
- 0.2878276113532769
- 0.4311140273204376
- -0.19543558698014918
- 0.2564370593665214
- -0.15730812009425493
- 0.21930650168600258
- 0.3342356877629409
- 0.08528470300293733
- 0.6205138831490963
- 0.5529663437342358
- 0.6138636553332917
- 0.8748260503190837
- 0.6861349083749528
- 0.8019564557903004
- 1.5190415863478264
- 0.8448568174966856
- 0.6888325372268561
- 0.5680099926742366
- 0.6255235594220748
- 0.6813509390060958
- 0.8396419198287446
- 0.9428063178251989
- 0.7865391331780034
- 0.4988155954737645
- 0.6923252575995273
- 1.6130090803399997
- 1.5185690107992202
- 0.5790417365193303
- 0.6919170938518138
- 0.7077310113724725
- 0.8532742245901307
- 0.8217678084513746
- 0.7655498761885946
- 0.6357573949217878
- 0.6668581507157852
- 0.2658038074336179
- 0.2747545649233658
- -0.05313865137496663
- 0.32054229077487045
- 0.2530743463524477
- 0.17056898316126937
- 0.2446662600282243
- 0.1534294364451599
- 0.09531040276636911
- 0.37852393648943133
- 0.17620076657688383
- 0.3657349221640593
- 0.31340086146539314
- -0.7614328026187821
- 0.7060941875823816
- 0.13842349117280492
- 0.06471443730105116
- 0.008429852596951497
- 0.4264224881575043
- 0.4573646793961205
- 0.45585708920375384
- 0.1273263718644731
- 0.0501530292683696
- 0.6439738357363883
- 0.10920641249907105
- 0.45492102522920663
- 0.16644225957725986
- 0.12404771332810371
- 0.25915731436345907
- 0.1851931963410259
- 0.9059392459803428
- -0.02572014063218457
- 0.26285553828979114
- 0.5329849612046397
- 0.42727493865971583
- -0.7534258748469953
- 0.12980642920240562
- 0.5122775875236195
- 0.07961496725120339
- 0.2740918127453399
- -1.041984168802845
- -0.12454277226476997
- 0.18159443636524383
- -0.06817469730286287
- -0.08114226661489783
- 0.31409283487585443
- -0.08495924287658249
- 0.18434424973184377
- 0.23874658722807482
- 0.2288365986455677
- -0.3189790462378427
- 0.17710587556479246
- 0.5408050267826997
- 0.22483583439665272
- -0.013843791445322204
- 0.28544083852596075
- 0.1818416342253591
- 0.07519988870962531
- 0.03674196479641561
- 0.22825081482754092
- 0.17326873550096286
- 0.3148105961338513
- 0.09102074404599479
- 0.29841621994074896
- -0.1589209677845006
- 0.4075512217820787
- 0.42782420399772814
- 0.526691507821854
- -0.1444321781128287
- 0.09279424714532995
- 0.16994081668569974
- 0.2304510480101794
- 0.1280795613329675
- -0.24602281772163487
- -0.3784565764194161
- -0.7492755006325682
- -0.46942630762396054
- -0.827375418612307
- 0.37324570632590987
- 0.2615563167672651
- 0.6330340669437472
- -0.6101019466274977
- -0.10166638280933911
- 0.4815072616442675
- -0.11775330759645271
- -0.07670840791016136
- 0.2750222343759868
- -0.27565096378523263
- -0.602429185115888
- -0.12365232094001398
- 0.4602082297958105
- 0.1115994720883164
- -0.5497099964507323
- -1.0511985779828679
- -0.38852181494403715
- 0.20297710880704292
- 0.17196826104359852
- -0.58752046416041
- -0.28102616012004344
- -0.5168375894769535
- -0.5267683758478198
- 0.29054479390476834
- -0.6602916143447916
- -0.25708770519675417
- -0.6873200709626008
- -0.7474307244126112
- -0.16113643243345155
- 0.17605256795763488
- -0.46082983885749085
- 0.524028125270797
- 0.08306848117909506
- -0.15855353785916806
- -0.136272225577963
- 0.09620937747243113
- -0.3585646745478788
- 0.35487136632410865
- -0.7322452750680782
- 0.2509673200013902
- 0.3233210606065246
- -0.0014739416089555655
- -0.47239105772841233
- -0.52829357508762
- 0.058798383595834114
- 0.6404861951056648
- -0.06459396145634888
- -0.13661235343890885
- 0.7769353216917634
- -1.0368976050020653
- 0.4943464859188192
- -1.4738621134968128
- -0.2625551419319258
- 0.09342235584763134
- -0.7797946679982044
- 0.05374679498129475
- 0.08902874418190343
- -0.25477873561188413
- 0.21801989921423345
- -0.39615519985127395
- -0.8068999951665201
- -0.6595811246527378
- -0.6975202326371498
- 0.921869487664892
- 0.06748558574882377
- 0.4280057796161259
- -0.047869132799517156
- 0.034073359457120055
- -0.03709811408224799
- -0.25405204755158456
- 0.5990644033434803
- -0.7320426552894539
- -0.886402473726615
- -0.9899875338260701
- -0.5508864441991267
- 0.22788522551169324
- -0.2587199577515807
- 0.31203204511250565
- -0.7671120741597319
- -0.8881861837800292
- -0.0810919411411917
- -0.22369003000812343
- -0.4853529561810987
- -0.6525107359119883
- -0.57884847477978
- 0.2657624716376746
- -0.7236329281723498
- -0.6386027662661731
- -0.23056029061617972
- -0.8505491772372864
- -0.6140590344730851
- -0.6339291381032781
- -0.6119485916432852
- -0.06146446128738379
- -0.3471014737838422
- -0.5465898342621763
- -0.7492365637807502
- 0.06300898946779483
- -0.5412512434056082
- -1.3069613300271876
- -0.07023214102875977
- 0.03473103030129304
- -0.22373034348909418
- -0.5109449701553626
- 0.18911242981548704
- -0.2811546852807569
- -0.020901095575296486
- -6.452570720620783
- -6.563273885241916
- -0.9085364909821704
- -0.8302492942991143
- -0.34082933932309506
- 0.0
- -0.9766773933361387
- -0.8588288225592885
- -0.5296390045641658
- -0.230576046602627
- 0.15681522976794926
- 0.4855513272779908
beta_mu:
- 1.5527443313368519
- -0.09107538054283086
- -0.18312089488894
- -0.4689123309814828
- -0.23952985847335503
- -0.024675556308175695
- 0.09508282478420021
- 0.07480650181008675
- 0.32982997831714717
- -0.008713374483581763
- -0.017839101934359433
- 0.06974388698017098
- 0.003507802213661048
- -0.0595353698933421
- -0.41757886770768105
- 0.006904963128964282
- -0.12652776242933603
- 0.07924190781137204
- 0.36402558498050713
- 0.19488070927474513
- 0.4125240950714837
- 0.29418545170585625
- 0.28857012444676833
- 0.41064530075913813
- 0.10163094748246997
- 0.24145206970195285
- 0.28219171038275187
- 0.24896317802212337
- 0.18738484395848276
- -0.0417701591042266
- 0.4489502520681685
- 0.48354621794358704
- 0.3285108256979838
- 0.47886083047072336
- 0.030401680116194006
- -0.10315885870781465
- -0.22111564646263202
- 0.0028550788236581612
- 0.029007542668237567
- -0.27092370944734445
- 0.1441393505493948
- -0.08836057471354675
- 0.28735683325700906
- -0.07749766330935662
- 0.02498984519433189
- -0.06245296345477717
- -0.169708937370852
- 0.019480572537046548
- 0.14831289066282077
- -0.06964373377584175
- 0.24572028438168553
- 0.038405652935242625
- 0.012439334542521451
- 0.1278284771364281
- 0.03910825143116933
- -0.023468644141707806
- -0.04493026028157349
- 0.014722854320909468
- -0.005448060907833427
- -0.03690793355759456
- 0.20189013052728835
- 0.12206314072413207
- -0.08433477728707786
- 0.10151809384560667
- 0.04345034095901736
- -0.06862226295456413
- -0.10269002371228464
- 0.09962034997985485
- 0.017015199454990342
- 0.03848929151512351
- -0.00693241569914184
- 0.067391444525862
- 0.0006125258094202612
- 0.07397626225279509
- 0.34340838967731374
- 0.32678719911217863
- 0.2772954075201485
- 0.48349367284106204
- 0.3212571834027699
- 0.32066880139626214
- 1.3071852376343693
- 0.6131073752240573
- 0.5513343578369988
- 0.5242652687965756
- 0.5959912967943999
- 0.5003395982989419
- 0.6045343191003266
- 0.5796895784059591
- 0.5601042668897412
- 0.5509470338066952
- 0.5741802396442492
- 1.1849962605652875
- 1.1619462364081805
- 0.6675492841282303
- 0.611918749349639
- 0.6060396149315627
- 0.577425011492149
- 0.4706008762641058
- 0.583734039378739
- 0.47313190942747235
- 0.09327879507802646
- 0.23583455426613678
- -0.16599544644283476
- 0.16725518457088415
- 0.2560245548869106
- -0.034335913387132294
- 0.2774166361522343
- -0.09699513799558074
- 0.14698969824586575
- 0.007886701452919937
- -0.15251144546276696
- -0.02544297675921156
- 0.16553344459262243
- -0.0017631401179416834
- -0.12485890273189842
- 0.040526614437184125
- 0.009174422041104809
- 0.03466688321615511
- 0.07387854531117392
- -0.09875277921366342
- 0.12208400891984782
- -0.07142714512402408
- 0.02376374060387575
- 0.12421688058242863
- 0.2973762233242939
- -0.105878295920766
- 0.3000088806181932
- 0.04966457426509164
- 0.1286414714450282
- 0.06208770215906533
- -0.0392695454901125
- 0.04280375137675203
- 0.1250995459430601
- -0.03620786892864802
- 0.05500233963619588
- 0.05801623996632718
- 0.021922790179608773
- 0.029118212650662882
- -0.14949761405450188
- 0.04605455652477688
- 0.0585276515760511
- -0.05526717998853921
- 0.18254887051677735
- -0.14494090628175244
- 0.045721532717693567
- 0.18914079864543146
- -0.04252719609063501
- -0.16724507411673734
- -0.02546736736092561
- 0.08870133576333113
- -0.02873921192567191
- -0.09756140002387416
- 0.06221975701056056
- 0.04384682924653094
- -0.004278551719982473
- 0.16577727668747125
- -0.005695173416929813
- 0.19990022298868312
- 0.036084847902103305
- 0.0685420848980916
- -0.16160755810092192
- -0.07897972353876441
- -0.035070290382705614
- 0.11668007331147587
- -0.026652550351842434
- -0.06212207248008251
- 0.11000652474736589
- -0.12433333014165512
- -0.015896063277826226
- -0.05392282955480936
- 0.07407089704348947
- 0.08893603773797312
- 0.09708373434980228
- -0.026935312456589606
- -0.013562025521287152
- -0.1230960787695148
- -0.3539969595038485
- -0.3458252503515698
- -0.0034134635649569166
- -0.1661491330905184
- -0.11659337681042314
- 0.4704349067256857
- -0.19986247563402934
- 0.06518033546611515
- -0.07857083278942088
- -0.2759530838513808
- -0.3271646008862744
- -0.22817270960516273
- 0.00017160074388139585
- 0.005762263040315203
- -0.12101490561616202
- -0.1770865205515059
- -0.20176524308654364
- 0.00038097453656194403
- 0.0873013107663656
- -0.00427706710513031
- -0.2002191177691894
- -0.08173068131885919
- 0.03906778913174181
- -0.3728059754315846
- -0.2458727631081206
- 0.13181100158612152
- -0.21494376100295587
- -0.2520782292321859
- -0.01275312683809414
- -0.08657759075669057
- -0.4139584070745037
- -0.30105346101048075
- -0.38815636113527924
- -0.4457015639393337
- -0.43245500441124823
- -0.07588886356948778
- 0.1728243023618372
- 0.23942490034178573
- -0.11659337681042282
- -0.1979165344014055
- -0.08270821244415456
- -0.08657759075669054
- -0.029278728451562694
- -0.2584899383541044
- -0.21063436072006134
- -0.09333934035045285
- -0.3642995624606229
- -0.1630644363343676
- -0.13757965783861104
- -0.12729449933150358
- -0.3262505886191265
- -0.22986585797792544
- -0.9953998553572445
- -0.22688144192801812
- 0.16028498796583135
- 0.22417580298171688
- 0.10368124184096005
- -0.1333478243687414
- 0.06750781704002477
- -0.12917482789731657
- 0.09101341292772976
- -0.02709033377286187
- -0.3250319563662608
- 0.132202352965863
- -0.8663283854866525
- -0.08657759075669053
- 0.042639098482570054
- -0.3915199186664965
- -0.22888450176503783
- -0.05223963351783929
- -0.09613660526076016
- -0.15974749820611
- -0.45412493456377706
- -0.16929196516220732
- 0.16900844068915655
- -0.11781648004676305
- 0.018917468088524396
- -0.1349336916790835
- -0.24913120248960569
- 0.022769369461436043
- -0.26034737328190666
- -0.434052085231446
- -0.2624192942393342
- -0.41202604660728925
- -0.30306737681567436
- -0.41395840707450354
- -0.32870725718708893
- -0.11470028698834275
- -0.4891797686944206
- -0.25207822923218587
- -0.3659515436270426
- -0.37600718932993027
- -0.01788861963476887
- -0.22659735368532838
- -0.32076720035410733
- -0.11346563362592622
- -0.25654696431512863
- -0.11532911254550916
- -0.10651857316640669
- -0.4830684293744409
- -0.17509239294758672
- -0.280700393739628
- -0.20357178257541764
- -0.1370867393003275
- -0.527034702441045
- 0.19599300817013082
- -0.3581535993148427
- -0.4112811380927354
- -0.3511288889745284
- -0.567669840308313
- 0.0
- 0.0
- -0.8016590852255946
- 0.0537530038111691
- -0.645679250351545
- 0.0
- 0.8289498851402832
