version: governed-radar-20251127
source:
  snapshot_date: 2025-11-27
  logical_id: web_traffic_by_country
  notes: Cloudflare Radar HTTP top locations (30d), normalised; XK dropped.
edge_scale: 500
weights:
- country_iso3: USA
  weight: 0.292073
- country_iso3: IND
  weight: 0.049377
- country_iso3: BRA
  weight: 0.045866
- country_iso3: DEU
  weight: 0.041158
- country_iso3: JPN
  weight: 0.040633
- country_iso3: GBR
  weight: 0.035889
- country_iso3: FRA
  weight: 0.030461
- country_iso3: CHN
  weight: 0.023760
- country_iso3: IDN
  weight: 0.022836
- country_iso3: NLD
  weight: 0.021803
- country_iso3: CAN
  weight: 0.020430
- country_iso3: SGP
  weight: 0.017230
- country_iso3: VNM
  weight: 0.016472
- country_iso3: TUR
  weight: 0.015826
- country_iso3: MEX
  weight: 0.015323
- country_iso3: ESP
  weight: 0.014503
- country_iso3: KOR
  weight: 0.014390
- country_iso3: PHL
  weight: 0.014187
- country_iso3: AUS
  weight: 0.013390
- country_iso3: THA
  weight: 0.012380
- country_iso3: RUS
  weight: 0.011790
- country_iso3: ITA
  weight: 0.011632
- country_iso3: POL
  weight: 0.010236
- country_iso3: HKG
  weight: 0.009657
- country_iso3: SAU
  weight: 0.008100
- country_iso3: TWN
  weight: 0.007369
- country_iso3: IRL
  weight: 0.007135
- country_iso3: ARG
  weight: 0.006804
- country_iso3: IRN
  weight: 0.006647
- country_iso3: ZAF
  weight: 0.006494
- country_iso3: MYS
  weight: 0.006473
- country_iso3: UKR
  weight: 0.005960
- country_iso3: COL
  weight: 0.005882
- country_iso3: BGD
  weight: 0.005784
- country_iso3: PAK
  weight: 0.005269
- country_iso3: BEL
  weight: 0.004935
- country_iso3: SWE
  weight: 0.004924
- country_iso3: NGA
  weight: 0.004531
- country_iso3: FIN
  weight: 0.004485
- country_iso3: EGY
  weight: 0.004380
- country_iso3: CHE
  weight: 0.003867
- country_iso3: CHL
  weight: 0.003843
- country_iso3: ROU
  weight: 0.003774
- country_iso3: PER
  weight: 0.003706
- country_iso3: PRT
  weight: 0.003639
- country_iso3: ISR
  weight: 0.003394
- country_iso3: ARE
  weight: 0.003289
- country_iso3: CZE
  weight: 0.003275
- country_iso3: GRC
  weight: 0.002934
- country_iso3: AUT
  weight: 0.002714
