
eligibility:
  rule_set_id: synthetic_s0_2025_10
  default_decision: allow
  rules:
    - id: deny_high_risk_cnp
      priority: 10
      decision: deny
      mcc: [6011, 6051]
      channel: ["CNP"]
      iso: ["*"]
    - id: deny_travel_cnp
      priority: 20
      decision: deny
      mcc: ["3000-3999", 4722]
      channel: ["CNP"]
      iso: ["*"]
    - id: allow_eea_multisite
      priority: 40
      decision: allow
      mcc: ["*"]
      channel: ["CP"]
      iso:
        - AT
        - BE
        - BG
        - HR
        - CY
        - CZ
        - DK
        - EE
        - FI
        - FR
        - DE
        - GR
        - HU
        - IE
        - IT
        - LV
        - LT
        - LU
        - MT
        - NL
        - PL
        - PT
        - RO
        - SK
        - SI
        - ES
        - SE
    - id: allow_rest
      priority: 100
      decision: allow
      mcc: ["*"]
      channel: ["*"]
      iso: ["*"]
