semver: 1.0.0
version: '2025-12-31'
metadata:
  simulation_manifest: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084417Z/manifest.json
  simulation_config_path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/models/hurdle/hurdle_simulation.priors.yaml
  seed: 9248923
  created_utc: 20251231T084417Z
  inputs:
    priors:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/models/hurdle/hurdle_simulation.priors.yaml
      sha256: e7c82d4a13057774789c3b1d25dd4eac6dd832956b49425b83c6a14d7d26780e
    transaction_schema_merchant_ids:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/layer1/transaction_schema_merchant_ids/2025-12-31/transaction_schema_merchant_ids.parquet
      sha256: a5ce122a1c61a4247ba4ece8624a201fe824c72c10f352cfba74623e54a0cb12
    world_bank_gdp_per_capita:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/world_bank_gdp_per_capita/2025-04-15/gdp.parquet
      sha256: 1eb6d9ae47639b17fd41e7875c03247c4133a849b442c0e3ebe61a4cb2c06074
    gdp_bucket_map:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/gdp_bucket_map/2024/gdp_bucket_map.parquet
      sha256: 624c9d1029e81980c7d7eb368a7ed07d67c62d8423d0c053cdcd9c58a6c80a3b
    iso3166_canonical:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/iso/iso3166_canonical/2024-12-31/iso3166.parquet
      sha256: bfb68d1770abef6a74571cfea4d659eefb7b6c7b39e81f1b6cc483bd60bd8b5f
    logistic:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084417Z/logistic.parquet
      sha256: da7fdbd584b2d12f7b76d638b9549cbe67bc1e970dbdb92bb81fb70ddcf4b99a
    nb_mean:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084417Z/nb_mean.parquet
      sha256: b8fc131dd597037356979e754899f1ac77c8ba4832d243f5b49530634f68c653
dict_mcc:
- 742
- 743
- 744
- 763
- 780
- 1520
- 1711
- 1731
- 1740
- 1750
- 1761
- 1771
- 1799
- 2741
- 2791
- 2842
- 4011
- 4111
- 4112
- 4119
- 4121
- 4131
- 4214
- 4215
- 4225
- 4411
- 4457
- 4468
- 4511
- 4582
- 4722
- 4784
- 4789
- 4812
- 4814
- 4815
- 4816
- 4821
- 4829
- 4899
- 4900
- 5013
- 5021
- 5039
- 5044
- 5045
- 5046
- 5047
- 5051
- 5065
- 5072
- 5074
- 5085
- 5094
- 5099
- 5111
- 5122
- 5131
- 5137
- 5139
- 5169
- 5172
- 5192
- 5193
- 5198
- 5199
- 5200
- 5211
- 5231
- 5251
- 5261
- 5262
- 5271
- 5300
- 5309
- 5310
- 5311
- 5331
- 5399
- 5411
- 5422
- 5441
- 5451
- 5462
- 5499
- 5511
- 5521
- 5531
- 5532
- 5533
- 5541
- 5542
- 5551
- 5552
- 5561
- 5571
- 5592
- 5598
- 5599
- 5611
- 5621
- 5631
- 5641
- 5651
- 5655
- 5661
- 5681
- 5691
- 5697
- 5698
- 5699
- 5712
- 5713
- 5714
- 5715
- 5718
- 5719
- 5722
- 5732
- 5733
- 5734
- 5735
- 5811
- 5812
- 5813
- 5814
- 5815
- 5816
- 5817
- 5818
- 5912
- 5921
- 5931
- 5932
- 5933
- 5935
- 5937
- 5940
- 5941
- 5942
- 5943
- 5944
- 5945
- 5946
- 5947
- 5948
- 5949
- 5950
- 5960
- 5962
- 5963
- 5964
- 5965
- 5966
- 5967
- 5968
- 5969
- 5970
- 5971
- 5972
- 5973
- 5975
- 5976
- 5977
- 5978
- 5983
- 5992
- 5993
- 5994
- 5995
- 5996
- 5997
- 5998
- 5999
- 6010
- 6011
- 6012
- 6051
- 6211
- 6300
- 7011
- 7012
- 7032
- 7033
- 7210
- 7211
- 7216
- 7217
- 7221
- 7230
- 7251
- 7261
- 7273
- 7276
- 7277
- 7278
- 7296
- 7297
- 7298
- 7299
- 7311
- 7321
- 7322
- 7333
- 7338
- 7339
- 7342
- 7349
- 7361
- 7372
- 7375
- 7379
- 7392
- 7393
- 7394
- 7395
- 7399
- 7512
- 7513
- 7519
- 7523
- 7531
- 7534
- 7535
- 7538
- 7542
- 7549
- 7622
- 7623
- 7629
- 7631
- 7641
- 7692
- 7699
- 7800
- 7801
- 7802
- 7829
- 7832
- 7841
- 7911
- 7922
- 7929
- 7932
- 7933
- 7941
- 7991
- 7992
- 7993
- 7994
- 7995
- 7996
- 7997
- 7998
- 7999
- 8011
- 8021
- 8031
- 8041
- 8042
- 8043
- 8049
- 8050
- 8062
- 8071
- 8099
- 8111
- 8211
- 8220
- 8241
- 8244
- 8249
- 8299
- 8351
- 8398
- 8641
- 8651
- 8661
- 8675
- 8699
- 8734
- 8911
- 8931
- 8999
- 9211
- 9222
- 9223
- 9311
- 9399
- 9402
dict_ch:
- CP
- CNP
dict_dev5:
- 1
- 2
- 3
- 4
- 5
design:
  beta_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
  - gdp_bucket_onehot([1,2,3,4,5])
  beta_mu_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
beta:
- -0.9053241682765886
- 0.21396020154918544
- -0.43405548126332744
- -0.3878010454822819
- 0.05516958369433146
- 0.1068738906483275
- -0.039038275257253216
- -0.37449471242083104
- 0.025071587519717664
- 0.12565211030945367
- 0.45927643549841823
- 0.025349605636786555
- -0.99043040783481
- -0.02781295646040288
- -0.3509672093555116
- -0.11113148577928346
- 0.14996417379581176
- -0.9717546571373065
- 0.16592238472684603
- 0.6182928072230123
- 0.4334402500546438
- 0.08554197384466257
- 0.10214884800306473
- 0.38018577665714026
- 0.013685683570221008
- 0.5935426860935921
- 0.3285622801859995
- 0.3589821408715832
- -0.21374036074057406
- -0.5259073178322844
- 0.11202288922152069
- 0.015851419346465803
- -0.694647643779957
- -0.05216868422342179
- -0.22272817219041421
- 0.19799378444821567
- 0.20098580618108727
- 0.18674389722944423
- 0.2933124960834415
- -0.19231419790295193
- -0.4984880372904357
- -0.024594625113016196
- -0.23629677557101547
- 0.05235150823758567
- 0.3082131505488255
- 0.4067614680278262
- 0.3224746145990893
- 0.14359688109708613
- 0.19514727861035824
- 0.1629951477757259
- -0.09552179671765845
- 0.22716035675649282
- 0.10396831932784044
- 0.08080480506244808
- 0.33617542895815167
- 0.4418713812567132
- 0.3146851207939639
- 0.24892242734827572
- 0.33448824836139524
- -0.14247417904224213
- 0.10063622900305351
- 0.03118502265582454
- 0.18687579162104823
- 0.05347105304132469
- 0.09445120016709566
- -0.20938740591198732
- 0.16452128021184717
- 0.3371549273715608
- -0.32356972684777563
- 0.046003262505960145
- -0.17305256298986704
- 0.2313734759756334
- 0.45781233217877126
- -0.20162313797957876
- 0.6502856543809424
- 0.722824862009697
- 0.9594879787027875
- 0.8122544894685678
- 0.7113104705736402
- 0.9092894209088862
- 1.2792096095980365
- 0.8132577856597996
- 0.7214391377223253
- 0.9836536342113034
- 0.9772956415222086
- 0.7701145454008165
- 0.8769040764635985
- 0.932058295543979
- 1.0235170150712405
- 0.5385478288550822
- 0.8943776915696514
- 0.954335714285141
- 0.6519102464537229
- 0.7159993688437523
- 0.8207623269272531
- 0.7151595722822276
- 0.8287926608212942
- 0.8752140105675893
- 0.8544332519183062
- 0.5224962628849774
- 0.6127858877734033
- 0.32707063170529965
- 0.23884863988008595
- 0.11613857725412269
- 0.15181823297339003
- 0.19911389495184326
- 0.02354131968558938
- 0.26982542534087844
- 0.13327782224977522
- -0.12234371198505734
- 0.42618869737930937
- 0.11576542083887155
- 0.31686672681914674
- 0.34855637568386993
- -0.31140669610327454
- 0.5454512421796639
- 0.18527989457505845
- 0.20323232233739308
- -0.005510265503478692
- 0.39237441873962275
- 0.3821174078242405
- 0.38694415711190006
- 0.13244391973671066
- 0.3656948235268085
- 0.2632289065013701
- 0.16894450182128704
- 0.3305936191790904
- -0.11846513417666799
- 0.07408015968979426
- 0.1002313718188723
- 0.22973297809233753
- 0.2387777233208354
- -0.04206146609249372
- 0.25165712072373914
- 0.405852594750241
- 0.39747734060548284
- -0.6498759202123288
- -0.006747016900221048
- 0.4498746140389275
- 0.03415301434358922
- 0.11259989909029296
- -0.44418528446995786
- -0.19153871613415258
- 0.07248923476616004
- -0.12262996808067159
- -0.1113269969419824
- 0.10684455587628282
- -0.28203635855023956
- 0.04005340284355525
- 0.349818341523693
- 0.2838973305159993
- -0.2787314923380577
- -0.03810801655826276
- 0.434640292092247
- 0.15019507534308102
- -0.04964695357721198
- 0.22824418335219912
- 0.06179156605466096
- 0.059821375013715324
- 0.005564232879826866
- 0.25437525793423393
- 0.18636700442167758
- 0.2853158873224752
- 0.17278691776250055
- 0.21048821409825857
- -0.2089831095607581
- 0.2294129644085816
- 0.22598553566925184
- 0.4555698552511732
- 0.047749600166125845
- -0.06601265641732723
- 0.17724300150795352
- 0.22652207263650329
- 0.051750883260902304
- -0.22289161104540514
- -0.4229977225445152
- -0.1946208705434748
- -0.13883669293136777
- -0.4185707807739638
- 0.2426932791324295
- 0.2529323450942542
- -0.052119859068210504
- -0.8061898808747693
- -0.15576074627001896
- 0.2616311144875816
- -0.019409502001095993
- -0.2694450998689621
- 0.17059709252855795
- -0.33072348143244124
- -0.7721955076400568
- -0.1835200732313527
- 0.3234497143293896
- 0.31665732160348653
- -0.5625540246060869
- -0.5091003754168518
- -0.4173679234660795
- 0.22436512921817844
- -0.16382758210807044
- -0.44377245352322603
- -0.32524610717954794
- -0.21817649710114356
- -0.3569438855672883
- 0.19367808007594178
- -0.6519201688053929
- -0.47744792260435626
- -0.9075706755518156
- -0.9519325716550675
- -0.012234749096147643
- 0.29909013586950367
- -0.4746755441473258
- 0.41533848561638503
- -0.03934024779262822
- -0.17961181925006636
- -0.025822834415328722
- 0.05923925493252004
- -0.22371759893937332
- 0.40481631744161695
- -0.6934677779838763
- 0.26781460108102734
- 0.10853648028446389
- 0.1580738732318246
- -0.6935006685859116
- -0.5411299526064841
- -0.13225098893908382
- 0.5018357515333032
- -0.291728101363112
- -0.21519869173114947
- 0.6459653956995467
- -0.34650802401341374
- 0.3639383188025728
- -1.2408913768079386
- -0.147251739809623
- 0.3179194342949468
- -1.002172094530653
- 0.025649875589810807
- 0.20079570154268242
- -0.09929618449366419
- 0.24225879602913813
- -0.4063439097608455
- -1.012251583213237
- -0.5602955076002275
- -0.6823210337209606
- 0.7155551773037094
- -0.3009350934448067
- 0.20850139916656452
- -0.2744928491253581
- 0.07882764528234219
- -0.24227952495027305
- -0.457767816564452
- 0.45122772461134986
- -0.5090717268458416
- -0.7951108382323522
- -0.585956423905312
- -0.7779173312986808
- 0.028273171682819866
- -0.298530475106179
- 0.449980551830657
- -0.9656393463515371
- -0.5483290936367989
- -0.013392582587951807
- -0.12963716207955867
- -0.34134226808771584
- -0.1064650267805864
- -0.3760335451754383
- 0.15806737419880443
- -0.7161679197534719
- -0.31039125066710677
- -0.3025073457910513
- -0.7956545656023282
- -0.6152278670496616
- -0.2335816402496909
- -0.48349757546877814
- -0.2901247205172597
- -0.3467216854381896
- -0.5564021503617127
- -0.4218888242362564
- -0.013645439370503649
- -0.36291255080647505
- -1.5099606173640825
- 0.014428964158474762
- 0.08434570039420412
- -0.4121814515342124
- -0.5023063372167543
- 0.1897708923907672
- -0.20039934368735995
- 0.09440427764694997
- -1.6709587129931007
- -6.749026030002962
- -1.13436780924228
- -0.30127372427053833
- -0.5811532802869512
- 0.0
- -0.9053241633944523
- -0.5944562075167208
- -0.386827045099014
- -0.20606914607455667
- 0.003143679139133222
- 0.2788845398744571
beta_mu:
- 1.1780114652199445
- -0.16902520873698723
- -0.5654228566678826
- -0.012389043092763464
- -0.16142140901733162
- -0.06555890417221623
- 0.013146955883447605
- 0.16997712306388804
- -0.17272144897915784
- 0.002411735294757327
- -0.19422726007033944
- 0.026962525549469797
- 0.2492823280611574
- -0.050675007560200644
- -0.27331168901394
- -0.1087992020173133
- -0.21160270603376344
- -0.1286917194220845
- -0.05456082090677413
- 0.1582074167779286
- 0.16135337537880673
- 0.20626396569872882
- 0.2632768590059178
- 0.1340433154069132
- 0.17247654257056336
- 0.28650934648282156
- 0.20390591957706156
- 0.02667600054262447
- 0.1700458110852213
- 0.308481660722501
- 0.08540903934866871
- 0.25145410691450915
- 0.07378464789408373
- 0.12419889561076589
- -0.19953313668132597
- -0.21559679599181578
- -0.2874367131823972
- 0.12399197317771897
- -0.1927797707809294
- -0.22041391280348918
- -0.15940168261292736
- 0.06926484385231381
- -0.031996907701154424
- 0.05526099858532409
- -0.1333309897529009
- -0.010050415674762576
- 0.09211494947721804
- 0.1412040962884043
- 0.006967360960822563
- 0.026977323809230586
- 0.20674688604263194
- 0.058577927903791786
- 0.13154867549255145
- 0.06043420167918602
- -0.011741398555271034
- -0.08233858525383349
- 0.013335389164206478
- 0.09848147413229638
- -0.011627050594749487
- -0.060016871034710734
- 0.14956989561514367
- 0.003058109483772726
- -0.17177278626558193
- -0.18625519797594736
- 0.009731130216355128
- -0.1585030242648523
- -0.08084121902144785
- -0.013059311796299673
- 0.04213939155646173
- 0.051285698664625644
- 0.08536414085508151
- -0.06230969880594621
- -0.035615787037413735
- 0.033271845765503225
- 0.1717210259455314
- 0.30061931953940085
- 0.4323359004106897
- 0.30161182940091386
- 0.1996237728181119
- 0.2251285663024737
- 0.6592647262654806
- 0.41963728048091126
- 0.35624839538235126
- 0.5376477461165606
- 0.4372853344095687
- 0.39107366438892727
- 0.3129218047767943
- 0.35697790561760584
- 0.49710034814284243
- 0.3179895614709299
- 0.45781437817162984
- 0.3562056616924299
- 0.2925203219000076
- 0.3801511730569167
- 0.4336069512235365
- 0.36184359174347597
- 0.3924667641404461
- 0.33366288085620427
- 0.34825640148510423
- 0.33885682137903766
- 0.06019877355534318
- -0.04436487481271081
- 0.025217273330131164
- 0.09864647713838241
- 0.21329370841168754
- -0.08401063666565872
- 0.20117116555783038
- -0.01419605139236367
- -0.062141251975450444
- 0.0653709231601966
- -0.03955993718529101
- 0.09260077601722934
- 0.007080667581051688
- 0.10682325361023111
- 0.12100720611453711
- 0.06411238519021664
- -0.11827189882513728
- 0.049877434839413676
- 0.023964708738409054
- 0.013744037495485669
- 0.17945639630513568
- 0.0195381390071443
- 0.09179449286333705
- 0.12077988801587418
- 0.04041642478266581
- 0.0009211957625459739
- 0.025535312090329446
- -0.029062523010718308
- 0.12914269789823749
- 0.028632191268243144
- -0.0005407428122757077
- -0.012258389257595568
- 0.08688412701584652
- 0.20445837399752115
- 0.034732499462971814
- 0.24409603860712192
- 0.014857802439198554
- 0.12732848616401451
- 0.05009345605129096
- 0.08954054871467151
- 0.10401963898961271
- 0.03571756632899561
- -0.04991078944637793
- -0.005329422150145777
- -0.17127464244041504
- -0.016480266664061147
- -0.2027203699636398
- -0.2669381135760676
- -0.15548822125128298
- 0.043951009115412124
- 0.03408387967994301
- 0.15111521415365733
- 0.02681252772496478
- -0.1349090017349374
- 0.15331982389754825
- 0.18200064574095248
- -0.10377794474702211
- 0.17030192779580633
- -0.012301424606854114
- 0.14431820255588745
- 0.11778689908143747
- -0.1271147246044964
- -0.05568793172935069
- -0.08249768270084024
- 0.01987757161443688
- 0.07856966481709339
- -0.09328225906260454
- 0.010339410950690782
- -0.03844000538671722
- 0.2974994570681652
- -0.06974692735547738
- -0.21117282956894487
- -0.0788601976721632
- 0.022126243657266773
- 0.044163830106210854
- 0.004635768357194809
- -0.14927068706505667
- 0.0398088497736751
- -0.09148542479270198
- 0.25386574162917536
- 0.21701313530854804
- -0.02599146812099168
- -0.08622757625902588
- 0.14445459573230293
- 0.05488130292977999
- 0.1575267384301925
- -0.17639184136375038
- -0.10448487369669998
- -0.23457822792747451
- 0.0964458527145205
- -0.3628253967665395
- 0.048329859085380435
- 0.023299292172478944
- 0.02836421734288067
- -0.03583548283886299
- 0.31848015877802344
- -0.12331635609788455
- 0.19948419657998948
- -0.12918940220085257
- 0.030353724114860006
- -0.27563610406446143
- -0.24840762000311573
- 0.08359259730469841
- 0.21764877284455741
- 0.11005165886316962
- 0.15891845048721906
- 0.03892094320606571
- -0.04242270686036716
- -0.15145992656553556
- 0.11024166784888392
- 0.14129091538118518
- 0.08994699474924853
- -0.10134014147416892
- 0.22779502609866867
- 0.02514703306756421
- 0.021769986940434416
- -0.01650680571284976
- -0.20745851716038743
- -0.22733000590683594
- -0.0700047838915391
- 0.14362955403358338
- 0.1410656390201011
- 0.3142108672420071
- -0.12429281509298931
- 0.19524076674372662
- -0.2483033705355492
- -0.35162527694530643
- 0.0024809075077806817
- -0.3656738037011348
- -0.050829023840046936
- -0.051314016690317356
- -0.08436067535634406
- 0.02013997505821069
- -0.039195508136210706
- -0.33948132638242073
- -0.05125497196841638
- 0.12968486667942006
- -0.04641500155492583
- -0.4522522644310754
- 0.10032370968917649
- -0.3262200695879409
- -0.043749178321097294
- -0.11675847982188851
- 0.0034976209997921847
- -0.09329224489649338
- -0.1337813443045589
- 0.0346275484899154
- -0.11396751838603797
- -0.39384821624442695
- 0.06257931379308103
- -0.13545837914874795
- -0.0638301359466823
- -0.304548541030056
- -0.3531210104008295
- -0.25197374182189336
- -0.18529767109881087
- -0.2078558807713527
- -0.5116580462761137
- -0.18075757882315024
- -0.4148285561709742
- -0.1950157157786415
- -0.3792875988453032
- -0.3976593344424229
- -0.07564416610537647
- -0.1597285141114388
- -0.33112504144720106
- -0.028906816972597112
- -0.49151173812151483
- 0.02827416965701307
- -0.2560914135141372
- -0.14018226623972269
- -0.12041332996503049
- -0.66531538066843
- -0.19632318726666256
- -0.23646417877719614
- 0.02827416965701312
- 0.060791568334356325
- -0.05622473661508054
- -0.3018597576131195
- -0.09913234533587469
- -0.07988572876819587
- -0.21020174010963466
- 0.13780923257185454
- -0.10686189761830638
- -0.23777161189078738
- -0.30645417138911174
- 0.04451838440364282
- 0.0
- -0.36072184439791904
- -0.43271454479686394
- -0.3079312181885097
- 0.0
- 0.8735982765683759
