semver: 1.0.0
version: '2025-12-31'
metadata:
  simulation_manifest: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T073822Z/manifest.json
  simulation_config_path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/layer1/1A/models/hurdle/hurdle_simulation.priors.yaml
  seed: 9248923
  created_utc: 20251231T073822Z
  inputs:
    priors:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/layer1/1A/models/hurdle/hurdle_simulation.priors.yaml
      sha256: 3033d20210592838bd8dec9e61ce4e737983b8b1a638cfe7364ecc2988ade31a
    transaction_schema_merchant_ids:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/layer1/transaction_schema_merchant_ids/2025-12-31/transaction_schema_merchant_ids.parquet
      sha256: a5ce122a1c61a4247ba4ece8624a201fe824c72c10f352cfba74623e54a0cb12
    world_bank_gdp_per_capita:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/world_bank_gdp_per_capita/2025-04-15/gdp.parquet
      sha256: 1eb6d9ae47639b17fd41e7875c03247c4133a849b442c0e3ebe61a4cb2c06074
    gdp_bucket_map:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/gdp_bucket_map/2024/gdp_bucket_map.parquet
      sha256: 624c9d1029e81980c7d7eb368a7ed07d67c62d8423d0c053cdcd9c58a6c80a3b
    iso3166_canonical:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/iso/iso3166_canonical/2024-12-31/iso3166.parquet
      sha256: bfb68d1770abef6a74571cfea4d659eefb7b6c7b39e81f1b6cc483bd60bd8b5f
    logistic:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T073822Z/logistic.parquet
      sha256: 325a4776e9d18e45438c2ae9c4dec640c43eb1adad08e34ea66b1370b6291f88
    nb_mean:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T073822Z/nb_mean.parquet
      sha256: e5c410ab3da5d86a8fdf09acb27c5516625975b7242f193b43fed566c57ad22e
dict_mcc:
- 742
- 743
- 744
- 763
- 780
- 1520
- 1711
- 1731
- 1740
- 1750
- 1761
- 1771
- 1799
- 2741
- 2791
- 2842
- 4011
- 4111
- 4112
- 4119
- 4121
- 4131
- 4214
- 4215
- 4225
- 4411
- 4457
- 4468
- 4511
- 4582
- 4722
- 4784
- 4789
- 4812
- 4814
- 4815
- 4816
- 4821
- 4829
- 4899
- 4900
- 5013
- 5021
- 5039
- 5044
- 5045
- 5046
- 5047
- 5051
- 5065
- 5072
- 5074
- 5085
- 5094
- 5099
- 5111
- 5122
- 5131
- 5137
- 5139
- 5169
- 5172
- 5192
- 5193
- 5198
- 5199
- 5200
- 5211
- 5231
- 5251
- 5261
- 5262
- 5271
- 5300
- 5309
- 5310
- 5311
- 5331
- 5399
- 5411
- 5422
- 5441
- 5451
- 5462
- 5499
- 5511
- 5521
- 5531
- 5532
- 5533
- 5541
- 5542
- 5551
- 5552
- 5561
- 5571
- 5592
- 5598
- 5599
- 5611
- 5621
- 5631
- 5641
- 5651
- 5655
- 5661
- 5681
- 5691
- 5697
- 5698
- 5699
- 5712
- 5713
- 5714
- 5715
- 5718
- 5719
- 5722
- 5732
- 5733
- 5734
- 5735
- 5811
- 5812
- 5813
- 5814
- 5815
- 5816
- 5817
- 5818
- 5912
- 5921
- 5931
- 5932
- 5933
- 5935
- 5937
- 5940
- 5941
- 5942
- 5943
- 5944
- 5945
- 5946
- 5947
- 5948
- 5949
- 5950
- 5960
- 5962
- 5963
- 5964
- 5965
- 5966
- 5967
- 5968
- 5969
- 5970
- 5971
- 5972
- 5973
- 5975
- 5976
- 5977
- 5978
- 5983
- 5992
- 5993
- 5994
- 5995
- 5996
- 5997
- 5998
- 5999
- 6010
- 6011
- 6012
- 6051
- 6211
- 6300
- 7011
- 7012
- 7032
- 7033
- 7210
- 7211
- 7216
- 7217
- 7221
- 7230
- 7251
- 7261
- 7273
- 7276
- 7277
- 7278
- 7296
- 7297
- 7298
- 7299
- 7311
- 7321
- 7322
- 7333
- 7338
- 7339
- 7342
- 7349
- 7361
- 7372
- 7375
- 7379
- 7392
- 7393
- 7394
- 7395
- 7399
- 7512
- 7513
- 7519
- 7523
- 7531
- 7534
- 7535
- 7538
- 7542
- 7549
- 7622
- 7623
- 7629
- 7631
- 7641
- 7692
- 7699
- 7800
- 7801
- 7802
- 7829
- 7832
- 7841
- 7911
- 7922
- 7929
- 7932
- 7933
- 7941
- 7991
- 7992
- 7993
- 7994
- 7995
- 7996
- 7997
- 7998
- 7999
- 8011
- 8021
- 8031
- 8041
- 8042
- 8043
- 8049
- 8050
- 8062
- 8071
- 8099
- 8111
- 8211
- 8220
- 8241
- 8244
- 8249
- 8299
- 8351
- 8398
- 8641
- 8651
- 8661
- 8675
- 8699
- 8734
- 8911
- 8931
- 8999
- 9211
- 9222
- 9223
- 9311
- 9399
- 9402
dict_ch:
- CP
- CNP
design:
  beta_phi_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
  - ln_gdp_pc_usd_2015
beta_phi:
- 1.3897808588353249
- -0.0758690476989405
- -0.0798898351550514
- -0.05828576222497799
- -0.04222935953993195
- -0.02827256230196661
- -0.026544863744719094
- -0.041713259754263605
- 0.019654448720000998
- -0.16256203418927945
- -0.06728964627212439
- -0.04338087453596196
- -0.05426956365901746
- 0.014773575824552894
- -0.050144759731821434
- -0.06559615700576905
- -0.013150651720361022
- -0.007030486520501419
- -0.0296598677432022
- -0.0922080590308067
- -0.1056074199947531
- -0.06239206446852401
- -0.026687291419478357
- -0.11849305661891385
- -0.07466919820799359
- -0.09441449019924014
- -0.0476540276325116
- -0.046333097745388574
- -0.053877403944770745
- -0.048311881544186884
- -0.03173198461840539
- -0.03934000292132991
- -0.04573746944663786
- -0.10487136966770634
- -0.08086978898955156
- -0.008717859116897353
- -0.10305102431046358
- -0.03607735053412767
- -0.04237303480483882
- -0.056454396357883546
- -0.15281756154596218
- -0.02340503943135379
- -0.08384366769502821
- 0.016788840316150525
- -0.017489941690700745
- -0.08912519428530137
- -0.045439584234802315
- -0.14841870662047812
- -0.08536697910866878
- -0.09685069757908442
- -0.01587378496952132
- -0.03742123109480348
- -0.02009876514953102
- -0.025946301297590305
- -0.04923074549594726
- -0.09286156488610842
- -0.01684665976887217
- -0.05573135999499874
- 0.026425849765242097
- -0.016603834002989214
- -0.023520137722866423
- -0.10671452614990302
- -0.0204190248249933
- -0.01950570978497522
- -0.02764170929868301
- -0.10475605510430462
- -0.09843471804678279
- -0.07303664246922659
- 0.02045755211868788
- -0.01860399346955464
- -0.0691293871079894
- -0.027160035394537582
- -0.053822559049147074
- -0.04595086284507126
- -0.0293749103435318
- -0.0743915827488214
- -0.09355643754585613
- -0.053749519923605465
- -0.043266591697384074
- -0.06892149276765983
- 0.43663910581947585
- 0.13299714663409867
- 0.03744388106965783
- -0.04861819555161681
- 0.20498131559089391
- 0.8387418171681654
- 0.3001248860926237
- -0.01564541063565674
- 0.5048581192541316
- -0.048628523751977695
- 0.7540225501204243
- 0.4203414861148408
- 0.866694140678062
- 1.1867772455921366
- 0.5382375913519092
- 0.30352177135754466
- 0.4867571152936265
- 0.13260071337909418
- 0.9547828368390624
- -0.021796801987158047
- -0.09331533998323852
- -0.03761579842409144
- -0.025934850359658812
- -0.026307911944308107
- -0.10216259705298393
- -0.05159300409369776
- -0.021369476564196785
- -0.0555231602056014
- -0.08318668655986163
- -0.09301306374101091
- 0.012271527504942774
- -0.13765939619001744
- -0.04999810178517936
- -0.04459461398020005
- -0.0165646625678047
- 0.023823773811120694
- -0.07948410149278956
- -0.04840150598352697
- -0.02619260773720968
- -0.09712558926377175
- -0.043756058057558264
- -0.05973898907781659
- -0.03152734799296325
- 1.2356747926226122
- 1.1340593296470767
- -0.0052815991631471725
- 0.8489145667891446
- 0.2858615943989519
- 0.8119706297088491
- 1.7443986938043854
- 0.5741648453340248
- -0.06636827025960387
- -0.09639085938959568
- -0.03423536653922551
- -0.03514484784440971
- -0.09025321442926924
- -0.004189936723536969
- -0.10502931012779639
- -0.04098512035963855
- -0.006906654456197374
- -0.020192909832736333
- -0.05435016538674635
- -0.0063894902016320265
- -0.01808784401611295
- -0.013875599916577457
- -0.06450672847826663
- -0.02546044135960949
- -0.015370685414025816
- -0.12901546649684248
- -0.08489582645217231
- -0.04443137493513475
- -0.026539245018266648
- -0.006660328123175556
- -0.03224017300292717
- -0.07648716198593546
- -0.02571114039089339
- -0.04267871454014553
- -0.03876288003219434
- -0.05015467350088577
- -0.09039621030216663
- -0.10136636126214582
- -0.04906020341050811
- -0.0756678017840578
- -0.09208260345625272
- 0.011065683815221702
- 0.00035824009996410325
- -0.04805065150584006
- -0.07536100658743969
- -0.06404169409659789
- -0.05315983981772083
- -0.07639869882195562
- -0.07734978413070498
- -0.048992979878888794
- -0.05973053812469897
- 0.005801501789552747
- -0.15759352786928119
- -0.05938240561770255
- -0.02742626380504945
- -0.019294268516175068
- -0.01859081716064854
- -0.02984414111068294
- -0.07101932308619824
- -0.07035003548312556
- -0.12476406104714792
- -0.08287072091903483
- -0.0328381745022486
- -0.021125763734924283
- -0.09200080420977615
- -0.021155887533743187
- -0.1592820093346801
- -0.09499591196747817
- -0.026233771521474138
- 0.014373044724031286
- -0.01647265357043972
- -0.04643764662518288
- -0.0368901355634403
- -0.05599685117450738
- -0.03358379252865056
- 0.00912868217832824
- -0.01369637799907927
- -0.06202752839253673
- -0.05154265141447629
- -0.09529075306964709
- -0.030323828031671583
- -0.14614161614202914
- 0.01937145688221801
- -0.010765168120993476
- -0.068024020955146
- -0.05750223958112352
- -0.03778637950585394
- -0.03388927875256405
- -0.0809111886602529
- -0.14716886308475993
- -0.07474771455475847
- -0.013353193918606924
- -0.01792738567827987
- -0.02198913793810488
- -0.039604631961830755
- -0.04500683787916202
- -0.005312406496835457
- -0.10656793120873724
- -0.030770620687358342
- -0.04715995866787648
- -0.17098464578175301
- -0.0075669428020098736
- 0.007968035292764755
- -0.051822966011187854
- -0.033431081106725574
- -0.02366835348593199
- -0.03138753523256354
- -0.0234752665330442
- -0.05860719588900165
- -0.047990163636002316
- -0.09188849426318062
- -0.20402170315156626
- -0.11566258074291844
- -0.019763290255912273
- 0.002027093097504753
- -0.05097703027157116
- -0.08618758980107848
- 0.020149776966061336
- -0.06669560744472637
- -0.018400569407542706
- -0.0409014044645543
- -0.046673422176674376
- -0.06289130517236356
- -0.026606995232537137
- -0.030297038833729514
- -0.03918582760342494
- -0.05764913764309601
- -0.08523382824776904
- -0.11488861546591357
- -0.1522437993521035
- -0.05002558268531077
- 0.009475450347302699
- -0.10379224665774955
- -0.06390648802696447
- 0.0035284672765194627
- 0.017609049821731955
- -0.05842543966840648
- -0.08276630820984751
- 0.0038570081369370167
- 0.013699104684831834
- -0.0653176870703881
- -0.011377958963453822
- -0.06507149866502056
- -0.011117625761043732
- -0.0779494082908912
- -0.021107201021137213
- -0.0068712078087199485
- -0.04600272858803377
- -0.15801919929492278
- -0.09024209826220116
- -0.006253575427262068
- -0.10901410113084281
- -0.003563510588946218
- -0.030104641972567535
- -0.03082537009914498
- -0.11769968896468937
- -0.021022218186537017
- -0.08568278739130368
- 0.01784608604792094
- -0.05169578532663755
- -0.05355333898144325
- -0.05200228893208584
- 0.0672201679206985
- 0.0
- 0.0
- 0.010880058716281867
- -0.1108822743621457
- -0.011189837789820457
- 0.0
- 1.389779315001462
- -0.06351537697784781
