semver: 1.0.0
version: '2025-12-31'
metadata:
  simulation_manifest: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084218Z/manifest.json
  simulation_config_path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/layer1/1A/models/hurdle/hurdle_simulation.priors.yaml
  seed: 9248923
  created_utc: 20251231T084218Z
  inputs:
    priors:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/layer1/1A/models/hurdle/hurdle_simulation.priors.yaml
      sha256: 279cf29d9a726aa1e77ce13d70d49183d0c6f75aa41da0592274a80e69ec6fee
    transaction_schema_merchant_ids:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/layer1/transaction_schema_merchant_ids/2025-12-31/transaction_schema_merchant_ids.parquet
      sha256: a5ce122a1c61a4247ba4ece8624a201fe824c72c10f352cfba74623e54a0cb12
    world_bank_gdp_per_capita:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/world_bank_gdp_per_capita/2025-04-15/gdp.parquet
      sha256: 1eb6d9ae47639b17fd41e7875c03247c4133a849b442c0e3ebe61a4cb2c06074
    gdp_bucket_map:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/gdp_bucket_map/2024/gdp_bucket_map.parquet
      sha256: 624c9d1029e81980c7d7eb368a7ed07d67c62d8423d0c053cdcd9c58a6c80a3b
    iso3166_canonical:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/iso/iso3166_canonical/2024-12-31/iso3166.parquet
      sha256: bfb68d1770abef6a74571cfea4d659eefb7b6c7b39e81f1b6cc483bd60bd8b5f
    logistic:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084218Z/logistic.parquet
      sha256: da7fdbd584b2d12f7b76d638b9549cbe67bc1e970dbdb92bb81fb70ddcf4b99a
    nb_mean:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084218Z/nb_mean.parquet
      sha256: 7ee7782b97a23c0ef24039563d27203af05f1793d40d0471dd0ed48e4505bbf3
dict_mcc:
- 742
- 743
- 744
- 763
- 780
- 1520
- 1711
- 1731
- 1740
- 1750
- 1761
- 1771
- 1799
- 2741
- 2791
- 2842
- 4011
- 4111
- 4112
- 4119
- 4121
- 4131
- 4214
- 4215
- 4225
- 4411
- 4457
- 4468
- 4511
- 4582
- 4722
- 4784
- 4789
- 4812
- 4814
- 4815
- 4816
- 4821
- 4829
- 4899
- 4900
- 5013
- 5021
- 5039
- 5044
- 5045
- 5046
- 5047
- 5051
- 5065
- 5072
- 5074
- 5085
- 5094
- 5099
- 5111
- 5122
- 5131
- 5137
- 5139
- 5169
- 5172
- 5192
- 5193
- 5198
- 5199
- 5200
- 5211
- 5231
- 5251
- 5261
- 5262
- 5271
- 5300
- 5309
- 5310
- 5311
- 5331
- 5399
- 5411
- 5422
- 5441
- 5451
- 5462
- 5499
- 5511
- 5521
- 5531
- 5532
- 5533
- 5541
- 5542
- 5551
- 5552
- 5561
- 5571
- 5592
- 5598
- 5599
- 5611
- 5621
- 5631
- 5641
- 5651
- 5655
- 5661
- 5681
- 5691
- 5697
- 5698
- 5699
- 5712
- 5713
- 5714
- 5715
- 5718
- 5719
- 5722
- 5732
- 5733
- 5734
- 5735
- 5811
- 5812
- 5813
- 5814
- 5815
- 5816
- 5817
- 5818
- 5912
- 5921
- 5931
- 5932
- 5933
- 5935
- 5937
- 5940
- 5941
- 5942
- 5943
- 5944
- 5945
- 5946
- 5947
- 5948
- 5949
- 5950
- 5960
- 5962
- 5963
- 5964
- 5965
- 5966
- 5967
- 5968
- 5969
- 5970
- 5971
- 5972
- 5973
- 5975
- 5976
- 5977
- 5978
- 5983
- 5992
- 5993
- 5994
- 5995
- 5996
- 5997
- 5998
- 5999
- 6010
- 6011
- 6012
- 6051
- 6211
- 6300
- 7011
- 7012
- 7032
- 7033
- 7210
- 7211
- 7216
- 7217
- 7221
- 7230
- 7251
- 7261
- 7273
- 7276
- 7277
- 7278
- 7296
- 7297
- 7298
- 7299
- 7311
- 7321
- 7322
- 7333
- 7338
- 7339
- 7342
- 7349
- 7361
- 7372
- 7375
- 7379
- 7392
- 7393
- 7394
- 7395
- 7399
- 7512
- 7513
- 7519
- 7523
- 7531
- 7534
- 7535
- 7538
- 7542
- 7549
- 7622
- 7623
- 7629
- 7631
- 7641
- 7692
- 7699
- 7800
- 7801
- 7802
- 7829
- 7832
- 7841
- 7911
- 7922
- 7929
- 7932
- 7933
- 7941
- 7991
- 7992
- 7993
- 7994
- 7995
- 7996
- 7997
- 7998
- 7999
- 8011
- 8021
- 8031
- 8041
- 8042
- 8043
- 8049
- 8050
- 8062
- 8071
- 8099
- 8111
- 8211
- 8220
- 8241
- 8244
- 8249
- 8299
- 8351
- 8398
- 8641
- 8651
- 8661
- 8675
- 8699
- 8734
- 8911
- 8931
- 8999
- 9211
- 9222
- 9223
- 9311
- 9399
- 9402
dict_ch:
- CP
- CNP
dict_dev5:
- 1
- 2
- 3
- 4
- 5
design:
  beta_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
  - gdp_bucket_onehot([1,2,3,4,5])
  beta_mu_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
beta:
- -0.9053241682765886
- 0.21396020154918544
- -0.43405548126332744
- -0.3878010454822819
- 0.05516958369433146
- 0.1068738906483275
- -0.039038275257253216
- -0.37449471242083104
- 0.025071587519717664
- 0.12565211030945367
- 0.45927643549841823
- 0.025349605636786555
- -0.99043040783481
- -0.02781295646040288
- -0.3509672093555116
- -0.11113148577928346
- 0.14996417379581176
- -0.9717546571373065
- 0.16592238472684603
- 0.6182928072230123
- 0.4334402500546438
- 0.08554197384466257
- 0.10214884800306473
- 0.38018577665714026
- 0.013685683570221008
- 0.5935426860935921
- 0.3285622801859995
- 0.3589821408715832
- -0.21374036074057406
- -0.5259073178322844
- 0.11202288922152069
- 0.015851419346465803
- -0.694647643779957
- -0.05216868422342179
- -0.22272817219041421
- 0.19799378444821567
- 0.20098580618108727
- 0.18674389722944423
- 0.2933124960834415
- -0.19231419790295193
- -0.4984880372904357
- -0.024594625113016196
- -0.23629677557101547
- 0.05235150823758567
- 0.3082131505488255
- 0.4067614680278262
- 0.3224746145990893
- 0.14359688109708613
- 0.19514727861035824
- 0.1629951477757259
- -0.09552179671765845
- 0.22716035675649282
- 0.10396831932784044
- 0.08080480506244808
- 0.33617542895815167
- 0.4418713812567132
- 0.3146851207939639
- 0.24892242734827572
- 0.33448824836139524
- -0.14247417904224213
- 0.10063622900305351
- 0.03118502265582454
- 0.18687579162104823
- 0.05347105304132469
- 0.09445120016709566
- -0.20938740591198732
- 0.16452128021184717
- 0.3371549273715608
- -0.32356972684777563
- 0.046003262505960145
- -0.17305256298986704
- 0.2313734759756334
- 0.45781233217877126
- -0.20162313797957876
- 0.6502856543809424
- 0.722824862009697
- 0.9594879787027875
- 0.8122544894685678
- 0.7113104705736402
- 0.9092894209088862
- 1.2792096095980365
- 0.8132577856597996
- 0.7214391377223253
- 0.9836536342113034
- 0.9772956415222086
- 0.7701145454008165
- 0.8769040764635985
- 0.932058295543979
- 1.0235170150712405
- 0.5385478288550822
- 0.8943776915696514
- 0.954335714285141
- 0.6519102464537229
- 0.7159993688437523
- 0.8207623269272531
- 0.7151595722822276
- 0.8287926608212942
- 0.8752140105675893
- 0.8544332519183062
- 0.5224962628849774
- 0.6127858877734033
- 0.32707063170529965
- 0.23884863988008595
- 0.11613857725412269
- 0.15181823297339003
- 0.19911389495184326
- 0.02354131968558938
- 0.26982542534087844
- 0.13327782224977522
- -0.12234371198505734
- 0.42618869737930937
- 0.11576542083887155
- 0.31686672681914674
- 0.34855637568386993
- -0.31140669610327454
- 0.5454512421796639
- 0.18527989457505845
- 0.20323232233739308
- -0.005510265503478692
- 0.39237441873962275
- 0.3821174078242405
- 0.38694415711190006
- 0.13244391973671066
- 0.3656948235268085
- 0.2632289065013701
- 0.16894450182128704
- 0.3305936191790904
- -0.11846513417666799
- 0.07408015968979426
- 0.1002313718188723
- 0.22973297809233753
- 0.2387777233208354
- -0.04206146609249372
- 0.25165712072373914
- 0.405852594750241
- 0.39747734060548284
- -0.6498759202123288
- -0.006747016900221048
- 0.4498746140389275
- 0.03415301434358922
- 0.11259989909029296
- -0.44418528446995786
- -0.19153871613415258
- 0.07248923476616004
- -0.12262996808067159
- -0.1113269969419824
- 0.10684455587628282
- -0.28203635855023956
- 0.04005340284355525
- 0.349818341523693
- 0.2838973305159993
- -0.2787314923380577
- -0.03810801655826276
- 0.434640292092247
- 0.15019507534308102
- -0.04964695357721198
- 0.22824418335219912
- 0.06179156605466096
- 0.059821375013715324
- 0.005564232879826866
- 0.25437525793423393
- 0.18636700442167758
- 0.2853158873224752
- 0.17278691776250055
- 0.21048821409825857
- -0.2089831095607581
- 0.2294129644085816
- 0.22598553566925184
- 0.4555698552511732
- 0.047749600166125845
- -0.06601265641732723
- 0.17724300150795352
- 0.22652207263650329
- 0.051750883260902304
- -0.22289161104540514
- -0.4229977225445152
- -0.1946208705434748
- -0.13883669293136777
- -0.4185707807739638
- 0.2426932791324295
- 0.2529323450942542
- -0.052119859068210504
- -0.8061898808747693
- -0.15576074627001896
- 0.2616311144875816
- -0.019409502001095993
- -0.2694450998689621
- 0.17059709252855795
- -0.33072348143244124
- -0.7721955076400568
- -0.1835200732313527
- 0.3234497143293896
- 0.31665732160348653
- -0.5625540246060869
- -0.5091003754168518
- -0.4173679234660795
- 0.22436512921817844
- -0.16382758210807044
- -0.44377245352322603
- -0.32524610717954794
- -0.21817649710114356
- -0.3569438855672883
- 0.19367808007594178
- -0.6519201688053929
- -0.47744792260435626
- -0.9075706755518156
- -0.9519325716550675
- -0.012234749096147643
- 0.29909013586950367
- -0.4746755441473258
- 0.41533848561638503
- -0.03934024779262822
- -0.17961181925006636
- -0.025822834415328722
- 0.05923925493252004
- -0.22371759893937332
- 0.40481631744161695
- -0.6934677779838763
- 0.26781460108102734
- 0.10853648028446389
- 0.1580738732318246
- -0.6935006685859116
- -0.5411299526064841
- -0.13225098893908382
- 0.5018357515333032
- -0.291728101363112
- -0.21519869173114947
- 0.6459653956995467
- -0.34650802401341374
- 0.3639383188025728
- -1.2408913768079386
- -0.147251739809623
- 0.3179194342949468
- -1.002172094530653
- 0.025649875589810807
- 0.20079570154268242
- -0.09929618449366419
- 0.24225879602913813
- -0.4063439097608455
- -1.012251583213237
- -0.5602955076002275
- -0.6823210337209606
- 0.7155551773037094
- -0.3009350934448067
- 0.20850139916656452
- -0.2744928491253581
- 0.07882764528234219
- -0.24227952495027305
- -0.457767816564452
- 0.45122772461134986
- -0.5090717268458416
- -0.7951108382323522
- -0.585956423905312
- -0.7779173312986808
- 0.028273171682819866
- -0.298530475106179
- 0.449980551830657
- -0.9656393463515371
- -0.5483290936367989
- -0.013392582587951807
- -0.12963716207955867
- -0.34134226808771584
- -0.1064650267805864
- -0.3760335451754383
- 0.15806737419880443
- -0.7161679197534719
- -0.31039125066710677
- -0.3025073457910513
- -0.7956545656023282
- -0.6152278670496616
- -0.2335816402496909
- -0.48349757546877814
- -0.2901247205172597
- -0.3467216854381896
- -0.5564021503617127
- -0.4218888242362564
- -0.013645439370503649
- -0.36291255080647505
- -1.5099606173640825
- 0.014428964158474762
- 0.08434570039420412
- -0.4121814515342124
- -0.5023063372167543
- 0.1897708923907672
- -0.20039934368735995
- 0.09440427764694997
- -1.6709587129931007
- -6.749026030002962
- -1.13436780924228
- -0.30127372427053833
- -0.5811532802869512
- 0.0
- -0.9053241633944523
- -0.5944562075167208
- -0.386827045099014
- -0.20606914607455667
- 0.003143679139133222
- 0.2788845398744571
beta_mu:
- 1.2418928113580012
- -0.09587015511816506
- -0.4262311997046855
- -0.19009700271534263
- -0.3263799973796083
- -0.09010636342152556
- -0.11915787540818087
- 0.18586675778782094
- -0.21727264803289573
- -0.10306068342439456
- -0.2635736781838871
- -0.22757254783339267
- -0.3764835035620055
- -0.02166177811107187
- -0.04921473865625454
- -0.23210782108305955
- 0.04382427005808607
- 0.05410049987241148
- 0.37011260726633965
- -0.11494680831863326
- 0.15171663242650077
- 0.09041444038230291
- 0.11932521196364139
- 0.08141276477481102
- 0.1246491310236164
- 0.3551809422853485
- 0.15481433456898583
- 0.12022005628860527
- 0.3227552590247404
- 0.18987899849648873
- 0.01888067845408816
- 0.33989394148511964
- 0.4603465656760697
- 0.03883065989890099
- -0.02494691451750327
- -0.10636653236275259
- 0.0749533761205443
- -0.2872436692585031
- 0.06644608694927623
- 0.07847579981584171
- -0.1161574885373788
- 0.14471419406352756
- 0.1492303203248125
- 0.02042983111590095
- 0.050741317716366474
- 0.2439668036715669
- -0.0907509331919361
- 0.20165130884025098
- 0.10635815116952733
- 0.04971835080036553
- 0.15623633982021584
- 0.12698124765608074
- 0.18604282418871382
- 0.11774524037120711
- -0.12991381773444302
- 0.07742459130947649
- 0.05680823504604536
- 0.27725817951896936
- -0.24102550917998836
- 0.055373233377638456
- -0.10520264386454475
- -0.059340425365107516
- -0.06673123573754547
- 0.15902658219194757
- 0.10071094389229962
- -0.036371990715611625
- -0.049753686075583586
- 0.09675295429988885
- 0.21103500281588522
- 0.012888661995798164
- 0.046973231373588706
- 0.1340896219288202
- -0.022519789528516174
- 0.16637742096202565
- 0.3300578301235634
- 0.3546320108627286
- 0.6870896642753166
- 0.39666717816652974
- 0.4293985433073922
- 0.45669162767620486
- 1.045319450159265
- 0.6216887977842859
- 0.5381068357875193
- 0.8826945652800949
- 0.8320808033877508
- 0.5894780071648767
- 0.5273386951339804
- 0.6420270632340787
- 0.7969634474692012
- 0.5630841060754547
- 0.6814085806123441
- 0.6257381637614824
- 0.5311595332332034
- 0.6970154593754665
- 0.6499355126729058
- 0.5066453319536216
- 0.5563593104505338
- 0.547039290124351
- 0.5688435987017492
- 0.5036092117254705
- -0.03432160342190192
- -0.14465387514154487
- 0.11496861868281308
- 0.021774476800429012
- 0.10608791091758189
- 0.02094903568230612
- 0.1631855697453198
- -0.08859085612403923
- -0.005112416119344221
- 0.1590266743981403
- 0.12497684244356483
- 0.09532688336309775
- -0.03115916490444811
- 0.06493806210523298
- 0.1294463731309771
- -0.06854726502406734
- 0.14995423292348675
- 0.15575927681772397
- 0.20571370759248123
- 0.024190694579120917
- 0.14600842437482095
- -0.0028615533630222726
- -0.05134017198872846
- 0.21718567135026595
- 0.013952975463702246
- 0.05124826024885521
- 0.1860779860809316
- -0.14268298588390105
- 0.13653725457507052
- 0.09229036856817723
- -0.01652264456825705
- 0.08352432112654412
- 0.15666160039589794
- -0.011749811665134544
- 0.08600246196881946
- 0.0014531672305040193
- -0.09350791283576262
- 0.26978266810967894
- -0.01627686262988735
- 0.06937907908355476
- 0.06618902854896552
- 0.005627547994478149
- 0.1168337692636316
- 0.07988574899320279
- -0.005306940466410956
- 0.030826303373060977
- 0.02494616196164454
- -0.07732065455537146
- -0.17653406608117947
- -0.22030531438645945
- -0.1157621091431344
- -0.028085560389180475
- 0.08070508812896109
- -0.017112663569713263
- 0.05981328036983981
- 0.1183002402502939
- 0.029298685675715582
- -0.0675551671925791
- -0.12266760380654512
- -0.14254270720400025
- 0.08473173226394304
- -0.006845300553293624
- -0.08940984187480823
- -0.012364662082154088
- -0.11777466514327053
- 0.019436612316097245
- 0.06649111985988974
- 0.009322757633729835
- 0.26746113326524656
- 0.05850224463477256
- 0.04933730887255877
- 0.054012114384863
- 0.05023168292769485
- 0.0661551771881386
- -0.006094389681436468
- -0.06341755210978794
- -0.19104239805962556
- -0.3684642512642917
- 0.0906876423178567
- -0.3418239603643721
- -0.09925683971576833
- -0.37636429704320135
- -0.0370374940260908
- -0.34899397518073955
- 0.1633872533464827
- 0.20716214117081733
- -0.12296252801425901
- 0.020694737289373395
- 0.0878109944917059
- -0.27054593511559727
- -0.20678634062616835
- -0.06015708626722341
- -0.1736796245188638
- -0.5221092441811997
- -0.3518624107314448
- 0.06018141459352324
- -0.15664312670939937
- -0.07580144975513739
- 0.019089845895939823
- -0.13856297360625672
- 0.14129655429175922
- 0.21190897415604806
- -0.19808547882020333
- -0.23408891516079736
- -0.08534223466402277
- -0.09280943886843263
- -0.3824467125471957
- -0.006928865979100532
- -0.1756456935341816
- 0.08862499461394373
- -0.1821891255091406
- 0.15571681399658086
- 0.013895210248050202
- -0.09736642594626614
- -0.1360731677116887
- -0.23270749977453375
- 0.1527572168957037
- -0.06263315994159666
- -0.003195917615094267
- -0.15651175718651755
- 0.04580433478123232
- 0.03584244195758211
- -0.29161382466925184
- -0.1559852779311022
- -0.19711493164023816
- -0.23467579835822813
- 0.28583177625423417
- -0.10936010479302878
- -0.07120046673399441
- -0.1469200189422713
- -0.6152604735532826
- -0.13451822240520014
- 0.003460724137336793
- -0.24917840468686858
- -0.33250848667839233
- -0.20550698495969175
- 0.17851632317486438
- 0.02408383808441879
- -0.07069856424866418
- -0.39372741045701953
- -0.0755655319734187
- 0.24425486641963273
- 0.08389891765314864
- 0.07700515915235533
- 0.024828931003623756
- -0.10662876467314032
- -0.2073168477118553
- -0.24265993158620427
- -0.12691211628901602
- -0.12465654652405002
- -0.26626356174820914
- -0.2923864686654265
- -0.15985072952119592
- -0.30458096108467964
- 0.11896820656334255
- -0.23978442298433306
- -0.3830782729170841
- -0.4028170490900798
- -0.6807180336385207
- -0.3302565719999661
- -0.28028424426657916
- -0.2750451111619539
- -0.2806625945740078
- -0.27279925799104904
- -0.5380887328079537
- -0.2607898534980343
- 0.03994294646569634
- -0.2757336744952154
- -0.4845914083612308
- -0.20128090526225706
- -0.3897375903173819
- -0.016807087153753956
- -0.4209744423334981
- -0.3578644934291931
- -0.07897309405075877
- -0.63609824733294
- -0.2944597891519402
- -0.07991703605805875
- 0.10280579068891373
- -0.11547387768802812
- -0.23546860159899957
- -0.215991650548136
- 0.002783765880664618
- -0.3385181114260149
- -0.39154394210175997
- -0.4528767452585239
- -0.9806889676328713
- 0.0
- -0.22951620011231003
- -0.11914298439650724
- -0.7503704729228814
- 0.0
- 0.8374084449429798
