semver: 1.0.0
version: '2025-12-31'
metadata:
  simulation_manifest: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084305Z/manifest.json
  simulation_config_path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/models/hurdle/hurdle_simulation.priors.yaml
  seed: 9248923
  created_utc: 20251231T084305Z
  inputs:
    priors:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/models/hurdle/hurdle_simulation.priors.yaml
      sha256: 43029b464d23d4270ccfb0e18014564f2461b7fee13b90db3ce05850c93d1ed2
    transaction_schema_merchant_ids:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/layer1/transaction_schema_merchant_ids/2025-12-31/transaction_schema_merchant_ids.parquet
      sha256: a5ce122a1c61a4247ba4ece8624a201fe824c72c10f352cfba74623e54a0cb12
    world_bank_gdp_per_capita:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/world_bank_gdp_per_capita/2025-04-15/gdp.parquet
      sha256: 1eb6d9ae47639b17fd41e7875c03247c4133a849b442c0e3ebe61a4cb2c06074
    gdp_bucket_map:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/gdp_bucket_map/2024/gdp_bucket_map.parquet
      sha256: 624c9d1029e81980c7d7eb368a7ed07d67c62d8423d0c053cdcd9c58a6c80a3b
    iso3166_canonical:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/iso/iso3166_canonical/2024-12-31/iso3166.parquet
      sha256: bfb68d1770abef6a74571cfea4d659eefb7b6c7b39e81f1b6cc483bd60bd8b5f
    logistic:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084305Z/logistic.parquet
      sha256: da7fdbd584b2d12f7b76d638b9549cbe67bc1e970dbdb92bb81fb70ddcf4b99a
    nb_mean:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084305Z/nb_mean.parquet
      sha256: d10c52ea37f927379911f8f671abd794ea24db654787f872e51fb189963360c6
dict_mcc:
- 742
- 743
- 744
- 763
- 780
- 1520
- 1711
- 1731
- 1740
- 1750
- 1761
- 1771
- 1799
- 2741
- 2791
- 2842
- 4011
- 4111
- 4112
- 4119
- 4121
- 4131
- 4214
- 4215
- 4225
- 4411
- 4457
- 4468
- 4511
- 4582
- 4722
- 4784
- 4789
- 4812
- 4814
- 4815
- 4816
- 4821
- 4829
- 4899
- 4900
- 5013
- 5021
- 5039
- 5044
- 5045
- 5046
- 5047
- 5051
- 5065
- 5072
- 5074
- 5085
- 5094
- 5099
- 5111
- 5122
- 5131
- 5137
- 5139
- 5169
- 5172
- 5192
- 5193
- 5198
- 5199
- 5200
- 5211
- 5231
- 5251
- 5261
- 5262
- 5271
- 5300
- 5309
- 5310
- 5311
- 5331
- 5399
- 5411
- 5422
- 5441
- 5451
- 5462
- 5499
- 5511
- 5521
- 5531
- 5532
- 5533
- 5541
- 5542
- 5551
- 5552
- 5561
- 5571
- 5592
- 5598
- 5599
- 5611
- 5621
- 5631
- 5641
- 5651
- 5655
- 5661
- 5681
- 5691
- 5697
- 5698
- 5699
- 5712
- 5713
- 5714
- 5715
- 5718
- 5719
- 5722
- 5732
- 5733
- 5734
- 5735
- 5811
- 5812
- 5813
- 5814
- 5815
- 5816
- 5817
- 5818
- 5912
- 5921
- 5931
- 5932
- 5933
- 5935
- 5937
- 5940
- 5941
- 5942
- 5943
- 5944
- 5945
- 5946
- 5947
- 5948
- 5949
- 5950
- 5960
- 5962
- 5963
- 5964
- 5965
- 5966
- 5967
- 5968
- 5969
- 5970
- 5971
- 5972
- 5973
- 5975
- 5976
- 5977
- 5978
- 5983
- 5992
- 5993
- 5994
- 5995
- 5996
- 5997
- 5998
- 5999
- 6010
- 6011
- 6012
- 6051
- 6211
- 6300
- 7011
- 7012
- 7032
- 7033
- 7210
- 7211
- 7216
- 7217
- 7221
- 7230
- 7251
- 7261
- 7273
- 7276
- 7277
- 7278
- 7296
- 7297
- 7298
- 7299
- 7311
- 7321
- 7322
- 7333
- 7338
- 7339
- 7342
- 7349
- 7361
- 7372
- 7375
- 7379
- 7392
- 7393
- 7394
- 7395
- 7399
- 7512
- 7513
- 7519
- 7523
- 7531
- 7534
- 7535
- 7538
- 7542
- 7549
- 7622
- 7623
- 7629
- 7631
- 7641
- 7692
- 7699
- 7800
- 7801
- 7802
- 7829
- 7832
- 7841
- 7911
- 7922
- 7929
- 7932
- 7933
- 7941
- 7991
- 7992
- 7993
- 7994
- 7995
- 7996
- 7997
- 7998
- 7999
- 8011
- 8021
- 8031
- 8041
- 8042
- 8043
- 8049
- 8050
- 8062
- 8071
- 8099
- 8111
- 8211
- 8220
- 8241
- 8244
- 8249
- 8299
- 8351
- 8398
- 8641
- 8651
- 8661
- 8675
- 8699
- 8734
- 8911
- 8931
- 8999
- 9211
- 9222
- 9223
- 9311
- 9399
- 9402
dict_ch:
- CP
- CNP
dict_dev5:
- 1
- 2
- 3
- 4
- 5
design:
  beta_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
  - gdp_bucket_onehot([1,2,3,4,5])
  beta_mu_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
beta:
- -0.9053241682765886
- 0.21396020154918544
- -0.43405548126332744
- -0.3878010454822819
- 0.05516958369433146
- 0.1068738906483275
- -0.039038275257253216
- -0.37449471242083104
- 0.025071587519717664
- 0.12565211030945367
- 0.45927643549841823
- 0.025349605636786555
- -0.99043040783481
- -0.02781295646040288
- -0.3509672093555116
- -0.11113148577928346
- 0.14996417379581176
- -0.9717546571373065
- 0.16592238472684603
- 0.6182928072230123
- 0.4334402500546438
- 0.08554197384466257
- 0.10214884800306473
- 0.38018577665714026
- 0.013685683570221008
- 0.5935426860935921
- 0.3285622801859995
- 0.3589821408715832
- -0.21374036074057406
- -0.5259073178322844
- 0.11202288922152069
- 0.015851419346465803
- -0.694647643779957
- -0.05216868422342179
- -0.22272817219041421
- 0.19799378444821567
- 0.20098580618108727
- 0.18674389722944423
- 0.2933124960834415
- -0.19231419790295193
- -0.4984880372904357
- -0.024594625113016196
- -0.23629677557101547
- 0.05235150823758567
- 0.3082131505488255
- 0.4067614680278262
- 0.3224746145990893
- 0.14359688109708613
- 0.19514727861035824
- 0.1629951477757259
- -0.09552179671765845
- 0.22716035675649282
- 0.10396831932784044
- 0.08080480506244808
- 0.33617542895815167
- 0.4418713812567132
- 0.3146851207939639
- 0.24892242734827572
- 0.33448824836139524
- -0.14247417904224213
- 0.10063622900305351
- 0.03118502265582454
- 0.18687579162104823
- 0.05347105304132469
- 0.09445120016709566
- -0.20938740591198732
- 0.16452128021184717
- 0.3371549273715608
- -0.32356972684777563
- 0.046003262505960145
- -0.17305256298986704
- 0.2313734759756334
- 0.45781233217877126
- -0.20162313797957876
- 0.6502856543809424
- 0.722824862009697
- 0.9594879787027875
- 0.8122544894685678
- 0.7113104705736402
- 0.9092894209088862
- 1.2792096095980365
- 0.8132577856597996
- 0.7214391377223253
- 0.9836536342113034
- 0.9772956415222086
- 0.7701145454008165
- 0.8769040764635985
- 0.932058295543979
- 1.0235170150712405
- 0.5385478288550822
- 0.8943776915696514
- 0.954335714285141
- 0.6519102464537229
- 0.7159993688437523
- 0.8207623269272531
- 0.7151595722822276
- 0.8287926608212942
- 0.8752140105675893
- 0.8544332519183062
- 0.5224962628849774
- 0.6127858877734033
- 0.32707063170529965
- 0.23884863988008595
- 0.11613857725412269
- 0.15181823297339003
- 0.19911389495184326
- 0.02354131968558938
- 0.26982542534087844
- 0.13327782224977522
- -0.12234371198505734
- 0.42618869737930937
- 0.11576542083887155
- 0.31686672681914674
- 0.34855637568386993
- -0.31140669610327454
- 0.5454512421796639
- 0.18527989457505845
- 0.20323232233739308
- -0.005510265503478692
- 0.39237441873962275
- 0.3821174078242405
- 0.38694415711190006
- 0.13244391973671066
- 0.3656948235268085
- 0.2632289065013701
- 0.16894450182128704
- 0.3305936191790904
- -0.11846513417666799
- 0.07408015968979426
- 0.1002313718188723
- 0.22973297809233753
- 0.2387777233208354
- -0.04206146609249372
- 0.25165712072373914
- 0.405852594750241
- 0.39747734060548284
- -0.6498759202123288
- -0.006747016900221048
- 0.4498746140389275
- 0.03415301434358922
- 0.11259989909029296
- -0.44418528446995786
- -0.19153871613415258
- 0.07248923476616004
- -0.12262996808067159
- -0.1113269969419824
- 0.10684455587628282
- -0.28203635855023956
- 0.04005340284355525
- 0.349818341523693
- 0.2838973305159993
- -0.2787314923380577
- -0.03810801655826276
- 0.434640292092247
- 0.15019507534308102
- -0.04964695357721198
- 0.22824418335219912
- 0.06179156605466096
- 0.059821375013715324
- 0.005564232879826866
- 0.25437525793423393
- 0.18636700442167758
- 0.2853158873224752
- 0.17278691776250055
- 0.21048821409825857
- -0.2089831095607581
- 0.2294129644085816
- 0.22598553566925184
- 0.4555698552511732
- 0.047749600166125845
- -0.06601265641732723
- 0.17724300150795352
- 0.22652207263650329
- 0.051750883260902304
- -0.22289161104540514
- -0.4229977225445152
- -0.1946208705434748
- -0.13883669293136777
- -0.4185707807739638
- 0.2426932791324295
- 0.2529323450942542
- -0.052119859068210504
- -0.8061898808747693
- -0.15576074627001896
- 0.2616311144875816
- -0.019409502001095993
- -0.2694450998689621
- 0.17059709252855795
- -0.33072348143244124
- -0.7721955076400568
- -0.1835200732313527
- 0.3234497143293896
- 0.31665732160348653
- -0.5625540246060869
- -0.5091003754168518
- -0.4173679234660795
- 0.22436512921817844
- -0.16382758210807044
- -0.44377245352322603
- -0.32524610717954794
- -0.21817649710114356
- -0.3569438855672883
- 0.19367808007594178
- -0.6519201688053929
- -0.47744792260435626
- -0.9075706755518156
- -0.9519325716550675
- -0.012234749096147643
- 0.29909013586950367
- -0.4746755441473258
- 0.41533848561638503
- -0.03934024779262822
- -0.17961181925006636
- -0.025822834415328722
- 0.05923925493252004
- -0.22371759893937332
- 0.40481631744161695
- -0.6934677779838763
- 0.26781460108102734
- 0.10853648028446389
- 0.1580738732318246
- -0.6935006685859116
- -0.5411299526064841
- -0.13225098893908382
- 0.5018357515333032
- -0.291728101363112
- -0.21519869173114947
- 0.6459653956995467
- -0.34650802401341374
- 0.3639383188025728
- -1.2408913768079386
- -0.147251739809623
- 0.3179194342949468
- -1.002172094530653
- 0.025649875589810807
- 0.20079570154268242
- -0.09929618449366419
- 0.24225879602913813
- -0.4063439097608455
- -1.012251583213237
- -0.5602955076002275
- -0.6823210337209606
- 0.7155551773037094
- -0.3009350934448067
- 0.20850139916656452
- -0.2744928491253581
- 0.07882764528234219
- -0.24227952495027305
- -0.457767816564452
- 0.45122772461134986
- -0.5090717268458416
- -0.7951108382323522
- -0.585956423905312
- -0.7779173312986808
- 0.028273171682819866
- -0.298530475106179
- 0.449980551830657
- -0.9656393463515371
- -0.5483290936367989
- -0.013392582587951807
- -0.12963716207955867
- -0.34134226808771584
- -0.1064650267805864
- -0.3760335451754383
- 0.15806737419880443
- -0.7161679197534719
- -0.31039125066710677
- -0.3025073457910513
- -0.7956545656023282
- -0.6152278670496616
- -0.2335816402496909
- -0.48349757546877814
- -0.2901247205172597
- -0.3467216854381896
- -0.5564021503617127
- -0.4218888242362564
- -0.013645439370503649
- -0.36291255080647505
- -1.5099606173640825
- 0.014428964158474762
- 0.08434570039420412
- -0.4121814515342124
- -0.5023063372167543
- 0.1897708923907672
- -0.20039934368735995
- 0.09440427764694997
- -1.6709587129931007
- -6.749026030002962
- -1.13436780924228
- -0.30127372427053833
- -0.5811532802869512
- 0.0
- -0.9053241633944523
- -0.5944562075167208
- -0.386827045099014
- -0.20606914607455667
- 0.003143679139133222
- 0.2788845398744571
beta_mu:
- 1.3540693908921226
- -0.05666779937604256
- -0.1980807078186803
- -0.048507690727380974
- -0.11049275390509398
- -0.1663815171343013
- 0.07195353259996964
- 0.09123270605275052
- -0.22112036295949564
- -0.13974278281956648
- -0.11353111091318892
- -0.012354505901035488
- -0.06007465583648141
- -0.080408125315383
- -0.24349191721739608
- 0.034694001332698926
- -0.14131513535181742
- 0.45506965883775974
- 0.20938547692106166
- -0.05341473361583093
- 0.17538623348332116
- -0.14273243933339805
- 0.15721300204344082
- 0.3933911785833229
- -0.03485144266240846
- 0.35195995302305233
- 0.07140054963308003
- 0.17903294234460693
- 0.26836623711142976
- -0.06040952020461054
- 0.16566186295964064
- 0.1266532523669064
- 0.37398113250270376
- 0.01645147098265377
- 0.08201423424335623
- 0.03106909604446395
- -0.04100723435401355
- 0.015013870548662028
- 0.10433387702907469
- 0.18790325782676953
- -0.09699477407302652
- -0.1390680744726992
- 0.2511414780415065
- -0.05135789367030101
- 0.1441043534149511
- 0.012640292157662738
- -0.1678064668196396
- 0.07936577223259293
- -0.013535860903968999
- -0.03525290475254389
- 0.20093716372346915
- 0.024994807847283376
- -0.08075741561387059
- 0.009357824318109298
- -0.006079023972184983
- -0.0406961245109163
- -0.0553843325103725
- 0.1437656634696721
- -0.054976377337248826
- -0.012760562407697683
- 0.054374098004564414
- 0.11259870628215529
- 0.049166092721951486
- -0.004540489074872239
- 0.0550392389903771
- -0.15376409683881134
- -0.09255652166190619
- -0.02889454300922999
- 0.10901294722474851
- 0.04733209035644596
- -0.017111831447906536
- 0.20507022921274415
- 0.047368053780898055
- -0.10912100916085314
- 0.41543514093085737
- 0.32640635993713374
- 0.6277973231961111
- 0.5310734058273312
- 0.3936191121255863
- 0.29376100512690534
- 0.9387998022315776
- 0.4400573229644738
- 0.4431243308009162
- 0.7085900750370626
- 0.6729043647669688
- 0.44313710702439185
- 0.4348451044560703
- 0.4882483746666864
- 0.727797669818116
- 0.4137964220373527
- 0.6605896654657654
- 0.5426032123698895
- 0.4903470865589189
- 0.5291643992000993
- 0.545049563062201
- 0.4953535014884589
- 0.435731783267536
- 0.3845227634095295
- 0.4217386988816124
- 0.46806964048881267
- -0.0972692394948092
- -0.05095032486475698
- -0.164826308792726
- 0.057924709685837
- 0.1518273902429054
- 0.012098336798369361
- 0.30486706389924734
- 0.1583746998409311
- 0.004460838782287813
- -0.1635974847348018
- -0.019757843712955567
- -0.25453457357016573
- -0.0445708502143466
- 0.05336790417558459
- -0.03126296984250404
- -0.004124293422231947
- 0.21682671327625752
- 0.23890730565177137
- 0.20566126850108057
- 0.07992498462592809
- 0.16856536073058465
- 0.0530951884292689
- 0.09697507230173341
- 0.252834444581186
- 0.10742879672856198
- 0.11034689969676009
- 0.057494440135671
- -0.16760374541713866
- 0.08296367272159011
- 0.07882895061718116
- 0.01610463106979348
- 0.024418368586844003
- -0.10469848892150603
- -0.010255384257048528
- 0.09340982414065292
- -0.051578260909430074
- -0.06975315362243742
- 0.17491094254165576
- -0.09489033848760407
- 0.04535972343937818
- -0.00567045077017996
- 0.18919043991448434
- 0.03310964414690576
- 0.06917836672838719
- 0.08689699920173574
- -0.06199835429063955
- -0.06923535388899651
- -0.17356848038092026
- 0.1295432953386228
- 0.12589839613836304
- 0.10320791940921997
- 0.185325465308446
- 0.1629682487175555
- 0.035124893522956564
- 0.13346998011319913
- 0.17129925889669811
- 0.0746832270290187
- 0.15178681637145536
- -0.018043236641805346
- 0.1607997895760779
- -0.1618997739450289
- -0.022564675650348632
- 0.0431202869032997
- 0.06954420871335586
- 0.0637441341500768
- 0.1369796155619159
- 0.10679656746231031
- -0.019315688146519395
- 0.08026780618477211
- 0.012019896818580239
- -0.21493797392707473
- 0.25049963169283856
- 0.17346968072431884
- -0.15085713005388682
- -0.016568403540686498
- -0.5214393745885311
- 0.44115633011251465
- -0.01768455518190489
- 0.18621575184524475
- -0.025326858161353515
- -0.1751608284965071
- 0.028127492462841658
- 0.055972734348746986
- -0.15845286620526822
- 0.02200041772851936
- -0.05305307807532151
- -0.3276718228992458
- -0.15503811455746835
- -0.11432121162903386
- -0.44750406393622716
- -0.5779506006199939
- -0.029663802880802725
- -0.08000680633088622
- -0.010276714619246024
- -0.45477876496701375
- 0.02051748439900854
- 0.01670527374447648
- -0.22516076337843513
- 0.0633834453260671
- -0.06455134180026047
- 0.056691893684952976
- 0.018268040466978712
- 0.10365410615425097
- 0.20589845336783857
- -0.256220144015943
- -0.5419271036126962
- -0.01884261774841823
- -0.17884905611242727
- -0.12335518116386149
- -0.23186527542381163
- 0.18306017883492867
- 0.012688678172817604
- -0.11197569350313617
- 0.0037217341078551293
- -0.13259557362058103
- -0.03378665140024844
- -0.23760076764275487
- -0.09738659248895673
- -0.32590266171635424
- -0.19760814315694972
- -0.09488921713052993
- -0.07946774452061282
- 0.07292978638258603
- 0.17622996135336053
- -0.09620693865055414
- -0.08446345531327978
- -0.24103925440031493
- -0.11531832200467522
- -0.31199257144706144
- -0.10707919858312666
- -0.22373092426643798
- -0.13813302565204796
- 0.01850452842273689
- -0.4939509230056346
- -0.031818352816553985
- -0.14714350925221012
- -0.0587204612802983
- 0.0019150300819988958
- -0.21858784820657254
- -0.48615515877035437
- -0.257139729659093
- 0.14951292020704193
- -0.05367021396536436
- -0.18038196831309114
- 0.046917963160615146
- -0.26227397965908233
- -0.13696954291001837
- 0.0007310441107837912
- 0.002547988119652498
- -0.18729822366015825
- 0.010300032051479183
- -0.20698459457732554
- -0.07088412480555287
- 0.11767232893298202
- -0.24960936739763315
- -0.07265851703502817
- -0.5053482599366987
- -0.44058616182110283
- -0.008147019877795104
- -0.5611126743350714
- -0.12873623859341804
- -0.10999100726990965
- -0.3028125789623301
- -0.11295729109380291
- -0.1392534128037987
- -0.19586219438813549
- -0.44416214771393125
- -0.6093609778579534
- -0.03986168298050204
- -0.18865388704074462
- -0.21161882032920734
- -0.32098232145000377
- -0.37551004341698707
- -0.1126119383752086
- -0.40340376752416834
- 0.25938362935949233
- -0.14188488048876755
- -0.25271038902679077
- -0.4302756718955466
- -0.21345534001905006
- -0.43497494672378584
- -0.02282352823060483
- -0.27377730376562215
- -0.4577845708389303
- -0.3403891832145778
- -0.3299702377210463
- -0.3978237254372717
- 0.0
- -0.006838460307738655
- -0.12353759259753162
- -0.8600329918720491
- 0.0
- 0.8922579620998172
