semver: 1.0.0
version: '2025-12-31'
metadata:
  simulation_manifest: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084305Z/manifest.json
  simulation_config_path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/models/hurdle/hurdle_simulation.priors.yaml
  seed: 9248923
  created_utc: 20251231T084305Z
  inputs:
    priors:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/models/hurdle/hurdle_simulation.priors.yaml
      sha256: 43029b464d23d4270ccfb0e18014564f2461b7fee13b90db3ce05850c93d1ed2
    transaction_schema_merchant_ids:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/layer1/transaction_schema_merchant_ids/2025-12-31/transaction_schema_merchant_ids.parquet
      sha256: a5ce122a1c61a4247ba4ece8624a201fe824c72c10f352cfba74623e54a0cb12
    world_bank_gdp_per_capita:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/world_bank_gdp_per_capita/2025-04-15/gdp.parquet
      sha256: 1eb6d9ae47639b17fd41e7875c03247c4133a849b442c0e3ebe61a4cb2c06074
    gdp_bucket_map:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/gdp_bucket_map/2024/gdp_bucket_map.parquet
      sha256: 624c9d1029e81980c7d7eb368a7ed07d67c62d8423d0c053cdcd9c58a6c80a3b
    iso3166_canonical:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/iso/iso3166_canonical/2024-12-31/iso3166.parquet
      sha256: bfb68d1770abef6a74571cfea4d659eefb7b6c7b39e81f1b6cc483bd60bd8b5f
    logistic:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084305Z/logistic.parquet
      sha256: da7fdbd584b2d12f7b76d638b9549cbe67bc1e970dbdb92bb81fb70ddcf4b99a
    nb_mean:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084305Z/nb_mean.parquet
      sha256: d10c52ea37f927379911f8f671abd794ea24db654787f872e51fb189963360c6
dict_mcc:
- 742
- 743
- 744
- 763
- 780
- 1520
- 1711
- 1731
- 1740
- 1750
- 1761
- 1771
- 1799
- 2741
- 2791
- 2842
- 4011
- 4111
- 4112
- 4119
- 4121
- 4131
- 4214
- 4215
- 4225
- 4411
- 4457
- 4468
- 4511
- 4582
- 4722
- 4784
- 4789
- 4812
- 4814
- 4815
- 4816
- 4821
- 4829
- 4899
- 4900
- 5013
- 5021
- 5039
- 5044
- 5045
- 5046
- 5047
- 5051
- 5065
- 5072
- 5074
- 5085
- 5094
- 5099
- 5111
- 5122
- 5131
- 5137
- 5139
- 5169
- 5172
- 5192
- 5193
- 5198
- 5199
- 5200
- 5211
- 5231
- 5251
- 5261
- 5262
- 5271
- 5300
- 5309
- 5310
- 5311
- 5331
- 5399
- 5411
- 5422
- 5441
- 5451
- 5462
- 5499
- 5511
- 5521
- 5531
- 5532
- 5533
- 5541
- 5542
- 5551
- 5552
- 5561
- 5571
- 5592
- 5598
- 5599
- 5611
- 5621
- 5631
- 5641
- 5651
- 5655
- 5661
- 5681
- 5691
- 5697
- 5698
- 5699
- 5712
- 5713
- 5714
- 5715
- 5718
- 5719
- 5722
- 5732
- 5733
- 5734
- 5735
- 5811
- 5812
- 5813
- 5814
- 5815
- 5816
- 5817
- 5818
- 5912
- 5921
- 5931
- 5932
- 5933
- 5935
- 5937
- 5940
- 5941
- 5942
- 5943
- 5944
- 5945
- 5946
- 5947
- 5948
- 5949
- 5950
- 5960
- 5962
- 5963
- 5964
- 5965
- 5966
- 5967
- 5968
- 5969
- 5970
- 5971
- 5972
- 5973
- 5975
- 5976
- 5977
- 5978
- 5983
- 5992
- 5993
- 5994
- 5995
- 5996
- 5997
- 5998
- 5999
- 6010
- 6011
- 6012
- 6051
- 6211
- 6300
- 7011
- 7012
- 7032
- 7033
- 7210
- 7211
- 7216
- 7217
- 7221
- 7230
- 7251
- 7261
- 7273
- 7276
- 7277
- 7278
- 7296
- 7297
- 7298
- 7299
- 7311
- 7321
- 7322
- 7333
- 7338
- 7339
- 7342
- 7349
- 7361
- 7372
- 7375
- 7379
- 7392
- 7393
- 7394
- 7395
- 7399
- 7512
- 7513
- 7519
- 7523
- 7531
- 7534
- 7535
- 7538
- 7542
- 7549
- 7622
- 7623
- 7629
- 7631
- 7641
- 7692
- 7699
- 7800
- 7801
- 7802
- 7829
- 7832
- 7841
- 7911
- 7922
- 7929
- 7932
- 7933
- 7941
- 7991
- 7992
- 7993
- 7994
- 7995
- 7996
- 7997
- 7998
- 7999
- 8011
- 8021
- 8031
- 8041
- 8042
- 8043
- 8049
- 8050
- 8062
- 8071
- 8099
- 8111
- 8211
- 8220
- 8241
- 8244
- 8249
- 8299
- 8351
- 8398
- 8641
- 8651
- 8661
- 8675
- 8699
- 8734
- 8911
- 8931
- 8999
- 9211
- 9222
- 9223
- 9311
- 9399
- 9402
dict_ch:
- CP
- CNP
design:
  beta_phi_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
  - ln_gdp_pc_usd_2015
beta_phi:
- 1.168541571025575
- -0.04119813597188174
- -0.0407666544458305
- -0.04145796138719679
- -0.041317215779622454
- -0.041842646672547494
- -0.04176739267111002
- -0.04162235263028437
- -0.041994568189886436
- -0.04073158585507241
- -0.04137663268426439
- -0.041579426215789944
- -0.041437707550578545
- -0.0421225348195105
- -0.041230294641872264
- -0.04112986642574723
- -0.041948981449181105
- -0.04178217651486545
- -0.04159848300577892
- -0.040999069049861475
- -0.04102543743111459
- -0.04133802763168314
- -0.04179018509332225
- -0.04103512556119975
- -0.04096659237585892
- -0.041140229600333623
- -0.041289161430275466
- -0.04146759969558811
- -0.041483082653749385
- -0.04137328631026867
- -0.041716016693117426
- -0.0415577339200543
- -0.04140323110928783
- -0.040681542851847205
- -0.04140745096804177
- -0.04187122150994816
- -0.04127960301346942
- -0.041469649513413795
- -0.04162797639023547
- -0.04149715954831145
- -0.04057050798174149
- -0.041701936525330545
- -0.0410096003891929
- -0.041925033145042215
- -0.041771847944850525
- -0.04100533817539122
- -0.041396509664003565
- -0.0408833129692063
- -0.04123207278455635
- -0.04123066213834345
- -0.04190784585243387
- -0.04174243194769377
- -0.041837774100117096
- -0.04141578091972446
- -0.041414051516455816
- -0.04119286275965755
- -0.041803282458986325
- -0.04153924883199468
- -0.041995463256974994
- -0.041553400135896916
- -0.04167967652535926
- -0.0411359976968499
- -0.04176722576056273
- -0.04169851391323747
- -0.041695296962046796
- -0.041020800501138835
- -0.04105345524711868
- -0.041337310561431195
- -0.04217110259414092
- -0.041780935721898414
- -0.04116690617964639
- -0.041566322074303476
- -0.04141118647972913
- -0.041578506293103355
- -0.041809883898318786
- -0.04136591027393297
- -0.041048866320078516
- -0.041581232866135825
- -0.04154188364193829
- -0.04111769647842537
- 0.42093362360965036
- 5.009159248519891e-06
- 0.9556274038298708
- 0.6922814170000186
- 0.3638920112492643
- 0.22017378550936376
- 0.2008470652814834
- 0.3018247296919512
- -0.041245629334160164
- -0.04129873727263441
- 0.2904243312512028
- 0.4275717489722844
- 1.0597436317284936
- -0.0413385139140995
- -0.030681956931540265
- -0.006908070701519602
- 0.3721421474300772
- -0.041142195434651016
- 1.6114128982411995
- 1.404670926760984
- -0.0411004483776581
- -0.04151821063648513
- -0.04156359718811428
- -0.04162773416351613
- -0.04078243654539698
- -0.041256762176759755
- -0.04178396216488652
- -0.041469963356616735
- -0.041164342484777426
- -0.04124504996864296
- -0.04202600741989735
- -0.040595793509655816
- -0.04150186976692638
- -0.04151456719270609
- -0.04167420418065035
- -0.04228478967066074
- -0.04079242254279
- -0.041310497313375466
- -0.041599503620840764
- -0.0410345398295515
- -0.04167457619901302
- -0.041246772259302296
- -0.04151733018660844
- 0.06135998228330493
- 0.31988900407920406
- 0.5279425655144785
- 0.7319567864070617
- -0.04159805457688372
- 0.15938873901187534
- 1.598164085119685
- 0.5086312071976851
- -0.041123885626156674
- -0.04117669264163656
- -0.041635784347761745
- -0.04146438180209895
- -0.04110657783656908
- -0.04140305022667701
- -0.04120197304310487
- -0.0411218505955446
- -0.04194653962029562
- -0.041682423417277084
- -0.040929439204324694
- -0.04160759029806032
- -0.04189933135322011
- -0.0418246738281799
- -0.04090815762569772
- -0.04173187706975396
- -0.041906971158349696
- -0.04087386235008642
- -0.04141389155299087
- -0.04136547041975972
- -0.041662275151971344
- -0.04191867498340327
- -0.041664724126181
- -0.04142973102938135
- -0.041692134151916575
- -0.04144120814955976
- -0.04155730979086178
- -0.04146678386346437
- -0.04113678418869501
- -0.040723094286492616
- -0.04156110016631379
- -0.0413361285289061
- -0.041148251153104526
- -0.04192457375828992
- -0.04196822909329928
- -0.04163854497768587
- -0.04139966607218492
- -0.04147492176704276
- -0.041427444150615125
- -0.04128199308948516
- -0.04137292750639419
- -0.041488926423126994
- -0.04139380775030099
- -0.041696559341737965
- -0.04095464380011748
- -0.0404868544680027
- -0.04157679703422514
- -0.041068802959425985
- -0.041861611729231016
- -0.041760882639579555
- -0.04130261236530168
- -0.041311283916977456
- -0.04104006481324685
- -0.04136144192711172
- -0.04174281891033754
- -0.04189741093905159
- -0.04112757676293642
- -0.041861107418446994
- -0.04054861234385652
- -0.04090876017205249
- -0.041806393483288795
- -0.041763753195977124
- -0.041657468881154056
- -0.04048275218716362
- -0.04162604943423802
- -0.041482367737177894
- -0.041705865945634496
- -0.04186588773668294
- -0.04177093507022509
- -0.04117042230855697
- -0.04131095416452592
- -0.041164225331463716
- -0.04164167536842129
- -0.04074614663577433
- -0.042207757767917915
- -0.042018299833437106
- -0.04163959302998298
- -0.041196497635959034
- -0.04119235167074441
- -0.04177987500122236
- -0.04131162893118951
- -0.0408137501497078
- -0.040955698745475826
- -0.041842706027985115
- -0.04173630956362532
- -0.04156511091290613
- -0.0409107512284995
- -0.04161132966653172
- -0.042095614130140915
- -0.04119103673083599
- -0.04173019049009317
- -0.04140303641650181
- -0.040535666528402015
- -0.04185189732527111
- -0.04220085905314888
- -0.04138212757668969
- -0.04172345003034749
- -0.041439215756055026
- -0.04180489919231898
- -0.041313045710654375
- -0.04157213016925487
- -0.04143470023379075
- -0.04113181131556093
- -0.040121535446114194
- -0.040841381204669916
- -0.04152452714040918
- -0.041946232292710016
- -0.04134200908868006
- -0.04070642695649859
- -0.04203543128706305
- -0.04139548958409812
- -0.041903205638652005
- -0.04147314449793982
- -0.041708129797423374
- -0.04144474623441168
- -0.041774113909758465
- -0.04169523809928903
- -0.04153903512627493
- -0.04109468534963628
- -0.04136816476026119
- -0.04130072911959681
- -0.04071263844397856
- -0.04148827872520032
- -0.04205010569084262
- -0.04075290736300053
- -0.04106923163556163
- -0.0421309750949114
- -0.04217861016588928
- -0.04122139442492077
- -0.04133415873303125
- -0.04201926206570663
- -0.04150469283658282
- -0.04162033541363158
- -0.04190775768344547
- -0.041616203357664396
- -0.04141992093905262
- -0.041419942920563994
- -0.041458004394270845
- -0.04182705959346638
- -0.040827073471778635
- -0.0407837522706226
- -0.04140113608607363
- -0.0420516225853663
- -0.040554518879832704
- -0.04129688390774011
- -0.041869210386026715
- -0.04144126300831324
- -0.04084262013501958
- -0.04194220808428932
- -0.04083702985386111
- -0.04221930399434706
- -0.04162719176872465
- -0.04119257656424675
- -0.04153560292854517
- -0.04257031454735946
- -0.03997919379290967
- 0.0
- -0.042248273786076436
- -0.04097304801333221
- -0.041995110980051376
- 0.0
- 1.1685401129716504
- 0.0006943599062636552
