semver: 1.0.0
version: '2026-02-12'
metadata:
  simulation_manifest: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2026-01-03/seed=9248923/20260103T184840Z/manifest.json
  simulation_config_path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/layer1/1A/models/hurdle/hurdle_simulation.priors.yaml
  seed: 9248923
  created_utc: 20260212T200543Z
  inputs:
    priors:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/layer1/1A/models/hurdle/hurdle_simulation.priors.yaml
      sha256: 7588df761e0c4ba3f09adced410db1ffb79fd7236b2ad99c6ef0362a230fa119
    transaction_schema_merchant_ids:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/layer1/transaction_schema_merchant_ids/2026-01-03/transaction_schema_merchant_ids.parquet
      sha256: df2f940f061a09a018e133828c9b7b2e7e442a1052b5c0105ef927e2b7c696e8
    world_bank_gdp_per_capita:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/world_bank_gdp_per_capita/2025-04-15/gdp.parquet
      sha256: 1eb6d9ae47639b17fd41e7875c03247c4133a849b442c0e3ebe61a4cb2c06074
    gdp_bucket_map:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/gdp_bucket_map/2024/gdp_bucket_map.parquet
      sha256: 624c9d1029e81980c7d7eb368a7ed07d67c62d8423d0c053cdcd9c58a6c80a3b
    iso3166_canonical:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/iso/iso3166_canonical/2024-12-31/iso3166.parquet
      sha256: bfb68d1770abef6a74571cfea4d659eefb7b6c7b39e81f1b6cc483bd60bd8b5f
    logistic:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2026-01-03/seed=9248923/20260103T184840Z/logistic.parquet
      sha256: e52e774343461db1071bf79d8166bc90e4ee9a78a43c935bb1ae0780afd05b00
    nb_mean:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2026-01-03/seed=9248923/20260103T184840Z/nb_mean.parquet
      sha256: 4e7ca3ee110b8dfb22d66b55dfcfa5264efc0a5d12202591c5301e023a51aea7
  remediation:
    wave: P1.3
    change: beta_mu_non_intercept_uplift_after_sampler_fix
    delta_intercept: 2.2
    rationale: increase NB mean heterogeneity to recover top-decile outlet concentration
      while keeping hurdle and dispersion blocks fixed
    parent_bundle: version=2026-02-12/20260212T195808Z
    note: retain P1.2 coefficient shape; concentration to be evaluated with S2 poisson
      inversion patch
    beta_mu_non_intercept_scale: 1.15
    intercept_recenter: none_first_pass
dict_mcc:
- 742
- 743
- 744
- 763
- 780
- 1520
- 1711
- 1731
- 1740
- 1750
- 1761
- 1771
- 1799
- 2741
- 2791
- 2842
- 4011
- 4111
- 4112
- 4119
- 4121
- 4131
- 4214
- 4215
- 4225
- 4411
- 4457
- 4468
- 4511
- 4582
- 4722
- 4784
- 4789
- 4812
- 4814
- 4815
- 4816
- 4821
- 4829
- 4899
- 4900
- 5013
- 5021
- 5039
- 5044
- 5045
- 5046
- 5047
- 5051
- 5065
- 5072
- 5074
- 5085
- 5094
- 5099
- 5111
- 5122
- 5131
- 5137
- 5139
- 5169
- 5172
- 5192
- 5193
- 5198
- 5199
- 5200
- 5211
- 5231
- 5251
- 5261
- 5262
- 5271
- 5300
- 5309
- 5310
- 5311
- 5331
- 5399
- 5411
- 5422
- 5441
- 5451
- 5462
- 5499
- 5511
- 5521
- 5531
- 5532
- 5533
- 5541
- 5542
- 5551
- 5552
- 5561
- 5571
- 5592
- 5598
- 5599
- 5611
- 5621
- 5631
- 5641
- 5651
- 5655
- 5661
- 5681
- 5691
- 5697
- 5698
- 5699
- 5712
- 5713
- 5714
- 5715
- 5718
- 5719
- 5722
- 5732
- 5733
- 5734
- 5735
- 5811
- 5812
- 5813
- 5814
- 5815
- 5816
- 5817
- 5818
- 5912
- 5921
- 5931
- 5932
- 5933
- 5935
- 5937
- 5940
- 5941
- 5942
- 5943
- 5944
- 5945
- 5946
- 5947
- 5948
- 5949
- 5950
- 5960
- 5962
- 5963
- 5964
- 5965
- 5966
- 5967
- 5968
- 5969
- 5970
- 5971
- 5972
- 5973
- 5975
- 5976
- 5977
- 5978
- 5983
- 5992
- 5993
- 5994
- 5995
- 5996
- 5997
- 5998
- 5999
- 6010
- 6011
- 6012
- 6051
- 6211
- 6300
- 7011
- 7012
- 7032
- 7033
- 7210
- 7211
- 7216
- 7217
- 7221
- 7230
- 7251
- 7261
- 7273
- 7276
- 7277
- 7278
- 7296
- 7297
- 7298
- 7299
- 7311
- 7321
- 7322
- 7333
- 7338
- 7339
- 7342
- 7349
- 7361
- 7372
- 7375
- 7379
- 7392
- 7393
- 7394
- 7395
- 7399
- 7512
- 7513
- 7519
- 7523
- 7531
- 7534
- 7535
- 7538
- 7542
- 7549
- 7622
- 7623
- 7629
- 7631
- 7641
- 7692
- 7699
- 7800
- 7801
- 7802
- 7829
- 7832
- 7841
- 7911
- 7922
- 7929
- 7932
- 7933
- 7941
- 7991
- 7992
- 7993
- 7994
- 7995
- 7996
- 7997
- 7998
- 7999
- 8011
- 8021
- 8031
- 8041
- 8042
- 8043
- 8049
- 8050
- 8062
- 8071
- 8099
- 8111
- 8211
- 8220
- 8241
- 8244
- 8249
- 8299
- 8351
- 8398
- 8641
- 8651
- 8661
- 8675
- 8699
- 8734
- 8911
- 8931
- 8999
- 9211
- 9222
- 9223
- 9311
- 9399
- 9402
dict_ch:
- CP
- CNP
dict_dev5:
- 1
- 2
- 3
- 4
- 5
design:
  beta_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
  - gdp_bucket_onehot([1,2,3,4,5])
  beta_mu_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
beta:
- 1.060423738098163
- -0.12355519992395293
- 0.6491379679497475
- 0.2529727775030237
- -0.9053807799197521
- 0.014423710998464628
- -0.3702318930787536
- -0.33798272406458135
- 1.1610070846442218
- 0.7208970768869805
- -0.25345560531329464
- -0.25123849181546987
- 0.2726066590800409
- 1.2152963768700502
- -0.6474758343442504
- 0.565548433318983
- -0.5471936098788812
- 1.1860556663818425
- 0.4244529740204774
- -0.08517964388838668
- 0.5635306350190763
- 0.27736169825485363
- 0.627943764512698
- 0.5148964368343001
- 0.5643290338453254
- 0.1705034667554028
- 0.17676049276390685
- 0.08148455192436094
- 0.534510098607455
- -0.33868676841838374
- 0.5744346291624133
- 0.0709378810256845
- 0.42004227953758577
- 1.2144401361355912
- 0.15561957679748165
- -0.32807931265784435
- -5.556305332257111
- 0.48408096272473317
- 0.053158358187763974
- 1.6773937758385775
- -0.3809119743500184
- 0.4103959843692794
- 0.6561634844315043
- -0.01899151950168879
- -0.03938299136530882
- -0.6096115081711363
- 0.6469796312451648
- -0.008403409481851245
- 0.4508352798838222
- 0.3096969289422762
- 0.42958998294609746
- 0.32187323958378106
- 0.3136845620140716
- 0.30501974624349865
- 0.029754587292650993
- -0.19305090038840828
- 0.44022042006851897
- -0.3511290688263239
- -0.616899534893281
- 0.31052970922422374
- 0.03177549751542108
- 0.2465158212944597
- -0.7571067433758978
- -1.1187817701065939
- -0.35569491279675375
- 0.08108135818967457
- 0.5355901360052674
- 0.07771930498233827
- -0.18455558901143093
- 0.6542089863011594
- 0.7294759746907631
- 0.5114587441242302
- 1.129145221859367
- 0.012004445200800748
- 0.6536315473173535
- 0.6472664966104283
- 0.8167201031618881
- -0.9200961000224505
- 0.3234386004177801
- -0.1407714758328826
- 1.118650529348533
- 0.9178522263028093
- 0.4324916977868366
- 1.026268131833808
- 1.2358220758664928
- 0.8226844851451212
- 1.205228197126019
- 0.537910030489806
- 1.6197447599597357
- 1.7827265356063569
- 0.52727979602855
- 1.7896311722781808
- 1.3116165800611326
- 0.30759396767768676
- 0.7285012896845053
- 0.24986782851404218
- 0.7913863276947197
- 0.4247518534644013
- 0.22000358665491376
- 0.572134893824342
- 1.0945468471325377
- 0.3038863184814762
- 0.9851975338482422
- 0.14853131856908103
- 0.7808474756888278
- -1.1591157441190527
- 0.32158606390650646
- -0.11123114085125216
- 0.5408610628888055
- 0.09910126040310344
- 0.4206389907684716
- 0.5059745896067693
- 0.66355972467946
- 0.23459524178603194
- 0.8345064917189555
- 0.6787038147465325
- 0.5329393986353501
- -0.00016901876176376565
- 0.7120846936865396
- -0.2921694636642049
- 0.7193193693219733
- -0.24945962571933994
- 0.7123498761770943
- 0.2603652367105659
- 0.9286097860882617
- 0.7316780589869276
- 0.44536536414169137
- -0.8368946858984847
- 0.6112666575729918
- 0.49880809492698625
- 0.19252197480758085
- 0.13011793271903327
- 1.0270106992691785
- 0.30419149900727954
- -0.13262183854760645
- -0.2816905960153228
- 0.09160978483191087
- 0.10016973819316388
- -1.6916911208557417
- 0.27471755339625364
- -0.28601995337608527
- -0.1932736735529803
- 0.39745834341752617
- 0.05849018240789916
- -0.17200926247803128
- 0.34185105846244385
- 0.21424273463322854
- -0.19811575551993937
- -0.3492111416222488
- -0.12294813531433404
- 0.05998233231905007
- -0.17338310867943182
- 0.10589704950104696
- 0.63559054573423
- -0.2791978457532176
- 0.5322142084392832
- 0.5830055604401227
- 0.5604014881094035
- 0.7249258346579842
- -1.0401230540046884
- 0.24911202687162518
- 0.4225773207639346
- 0.25204916343199174
- -0.27812631424952966
- 0.2409284594984029
- -0.47241177823345976
- -0.2692367588144125
- 0.18603522312108417
- 0.0067348759500703735
- 0.3582752194801141
- 0.16297976987876336
- 0.4833661356899183
- -0.5441005509571241
- -0.21085265981801307
- -0.10221069566261512
- -0.5628037626774556
- -0.41774885208914647
- 0.19951333491186213
- -0.38914008051359134
- -0.08492581038926812
- -0.45543404859785874
- 0.14080407816449503
- -0.6924834819680055
- -0.8370565946384365
- 0.3723020749859881
- -0.815230049941712
- 0.22934613239564317
- -0.5046848240361851
- 0.16575222124721076
- -1.4250638199596695
- 0.038017874265135865
- -0.18253595356549346
- -0.3715819598822544
- -0.8611853217790802
- -0.006139643333341906
- 0.16830375686740193
- 0.3173746341605253
- 0.3002345517329067
- 0.17623135666560077
- -0.7287956082173863
- -0.9610628779015137
- 0.40605076981653027
- 0.18226222439069437
- -0.3121466589126882
- 0.22762008657128616
- 0.044149816094843135
- -0.03943527552502154
- 0.3863088330089787
- 0.480452955555161
- -0.2049837814597023
- 0.050385871559901374
- -0.86970753459761
- -0.8251194618170815
- 0.9662631116481216
- -0.6631237938563594
- -0.10926841597306858
- -0.5961988754115395
- -0.8079011046540583
- -0.3132044063138858
- 0.511834421544762
- -1.1616780169153382
- 0.3505700329797492
- 0.05964695186496368
- -1.626218180702916
- 0.5302477212829408
- 0.4500502746449453
- -0.17234828361777377
- 0.133881736839792
- 0.4253774524525599
- 0.23354527852141105
- -0.3302777701554893
- -1.3740227763719435
- 0.4610965540307373
- -0.8513626416075153
- -0.47945831812878925
- 0.18404223851638873
- -0.8964049444686198
- -0.27064157337001665
- 0.4179557786050321
- -0.44259527303420265
- 0.43009217402544675
- -0.3137971898815487
- -0.35204769932807856
- -0.6105098962679495
- 0.003493954948993786
- -0.7610815837116025
- 0.18722894893688763
- -0.7706489439135431
- -0.9318324397853136
- 0.17066248487527066
- -0.7111113170053198
- -0.3294506455420305
- -0.8509799257045816
- -0.5791717226599604
- -0.1997006930480287
- -0.30232660716434606
- -0.7696726379425509
- 0.16322162315629277
- -0.45996453998376957
- 0.4082491375430201
- -0.04016180640420546
- -0.3237080982593376
- -0.5319459418262676
- -0.6150641506884175
- 0.48126632741328323
- 0.3259158291079374
- -0.5596192163629057
- 0.31632966227601356
- -0.47700378139621824
- -0.8337738578537423
- -0.38369089735113415
- -0.7091902266158834
- -0.4262592921097843
- -0.7655132657256938
- -0.5773276246783964
- -6.850110469270412
- -0.8514134414452039
- 0.049427516618458206
- -0.03575410450426962
- 0.48972276897077505
- 0.013318418254464292
- -0.09098549330811943
- -6.86544681845988
- -0.37612537944065366
- 0.41839605148232034
- -0.556639500130873
- -1.0632389090792185
- -0.8476479959836294
- 0.3589885724100375
- -0.9218571039778817
- -0.17488049754930932
- -0.28750660784290355
- -0.8520696527283449
- -0.7844325078593459
- -0.4810454702602077
- -0.2560555372181693
- -0.007979490332166226
- 0.38993674638828835
beta_mu:
- 1.7814957339620379
- -0.4076215200394034
- -0.23656048628666063
- 0.013725005528962572
- -0.5543086379331688
- -0.14191419248218182
- 0.39798446305960367
- 0.07709057687307024
- 0.2288186631026727
- -0.0371478139022788
- 0.26877890790804904
- -0.25059916837319607
- 0.017828642608295506
- 0.29799957592806064
- -0.7533178723549456
- -0.3144204865427656
- 0.039856884529952834
- 0.19664689066832863
- 0.010984466534666157
- 0.13223329873549658
- 0.11582528713357874
- 0.5914329813859857
- 0.2250671371139225
- 0.3226285457924997
- 0.058721860167023944
- 0.4812305009843327
- -0.24113166960706653
- 0.11748489058576415
- 0.671073061266379
- 0.1959950641182971
- 0.2167564249668664
- -0.1671665611900984
- 0.2715176197915769
- 0.5238943586276681
- -0.09702600257582587
- 0.01160977903763834
- 0.0
- -0.1082454964360233
- -0.1817650695952427
- -0.23042852551876594
- 0.08835195870690407
- -0.06543274587457705
- -0.10799933669606798
- 0.0016125932474600996
- -0.3620061011711591
- 0.38784357542314685
- -0.024306332431702757
- 0.16698845511378207
- -0.04790473613622307
- 0.012110064495521142
- -0.13725909651917256
- -0.022226355267596025
- 0.1277111567210178
- -0.1966840677864743
- -0.40762152003940283
- -0.294126871594146
- -0.09067592220387533
- -0.06670561323723022
- -0.23366242167700535
- 0.039046142766692285
- -0.4379050973966882
- 0.07200876236124623
- -0.5543086379331685
- 0.6584575691625737
- 0.15161738507822328
- 0.14776554166929537
- 0.12966102078828645
- 0.00722513943777258
- -0.20482093127602427
- 0.037165420497670125
- 0.11117663797452848
- 0.11956921594166718
- 0.007223062339360669
- 0.02293149103188495
- 0.6096642840754884
- 0.2529383716013174
- 0.2933557182520999
- 0.20532115516011826
- 0.26994572025314345
- 0.5044901035550361
- 0.7761191032831544
- 0.4349037681307299
- 0.866228871951036
- 0.6752114655828199
- 0.7336342092643701
- 0.41736041963727877
- 0.5623450811625016
- 0.502027103237183
- 0.5640299562545483
- 0.5466254045788068
- 0.4813877558952437
- 0.7428532272147107
- 0.9049393649498966
- 0.5623528392438942
- 0.4608429398676648
- 0.360427296503091
- 0.3262106486423033
- 0.46142963274849236
- 0.20680386899157766
- 0.3607993515845761
- 0.10342363392824361
- -0.1182918765037505
- 0.2539654065392848
- 0.27480686076356825
- 0.24351720097378693
- 0.07707773486459549
- -0.34244039492430334
- 0.15959079253776412
- 0.2792933650673918
- 0.20190093877560514
- -0.100870287828937
- 0.5312249121144127
- -0.10307152692703173
- 0.18888251389412758
- 0.024055506352748352
- -0.1284906397647726
- 0.16756504171245448
- 0.4844265093649699
- 0.08307908969014413
- 0.41200812934174474
- -0.09773641172031934
- 0.147742289503768
- 0.433949672583501
- 0.07769397748878329
- 0.202451171174312
- 0.2296019106780482
- 0.3590598014977125
- 0.4196065906769392
- -0.050137964897392605
- 0.24197824836303158
- 0.28262977256131844
- 0.0594033535999983
- -0.3608820905563423
- -0.18370575088914248
- 0.2257367416431927
- 0.12536674258104985
- -0.2562726788718926
- 0.012110064495520684
- 0.0770392344975303
- -0.28304011505108434
- 0.35060988308002927
- -0.20806783841690488
- 0.09768675798872598
- 0.006869931314672832
- 0.04110009663040968
- -0.36101964311456314
- -0.028567610639686988
- -0.1559871666385072
- -0.14815256362590873
- 0.4838394199727335
- 0.08027693832375161
- -0.1446980697860081
- -0.2549394504323087
- 0.05114647669813748
- 0.7197383315046681
- -0.162881123473955
- -0.22571189662216357
- 0.26095675795277656
- -0.18702765422327067
- -0.43215856391196694
- 0.3180051353274995
- -0.11103312460324301
- -0.15545059318163157
- -0.0044468741407173275
- 0.18892262187827305
- -0.12342104103070486
- -0.23759058924669077
- 0.2674908613966428
- -0.059188211734910894
- 0.2743809807437199
- -0.09956295115727036
- 0.2387702834477029
- 0.11181287509785497
- 0.04501831035978644
- 0.011609779037638221
- -0.21566856366299605
- -0.0931440678223666
- -0.26586731343583053
- -0.20338544846866713
- 0.05358142214990145
- -0.03075912811619622
- -0.5073840835527971
- 0.13762975535759905
- 0.505116448728037
- -0.05277532391106896
- -0.1324872729445477
- 0.04418294088738946
- 0.2543047872709516
- -0.035406236142684906
- -0.38877982077158946
- -0.43707582277207163
- -0.06156585271252816
- -0.1661422654688849
- -0.2607306932400705
- 0.008090599348580124
- 0.07352641762803572
- -0.2033071271791786
- 0.15715272297269323
- -0.029745794774519534
- -0.4402088981323835
- -0.7648981815196829
- -0.03756870657226861
- -0.2910794369790702
- -0.5280747318559667
- 0.04216428129963681
- -0.2836086656550255
- 0.22109874492816575
- 0.0021935787799857802
- 0.07056674493759427
- -0.5806026085017144
- -0.01534618050970955
- -0.027704769039975676
- -0.4260652176376459
- -0.016927428226281318
- 0.25368648310447894
- 0.5171826667365033
- -0.47534301428834114
- -0.18176506959524283
- -0.2941268715941464
- -0.19439213979224274
- -0.42606521763764577
- 0.07710085356131544
- -0.07047605608370532
- 0.07703923449753029
- 0.09605740658747644
- -0.05806304658614239
- -0.5457612249950422
- -0.0022353302404559553
- -0.18447565407670813
- -0.1444179245082893
- -0.24681363510747223
- -0.38877982077158985
- 0.2163572571690881
- -0.4260652176376457
- 0.03642604306757237
- -0.169263295066345
- 0.2394985688066976
- -0.5120108930019215
- 0.09410754252020737
- -0.022073172654217633
- 0.12513678958084265
- -0.17231072968142053
- -0.11625604184019592
- 0.43225373308589177
- 0.035175280613295896
- -0.3212827137330739
- -0.15020904395561108
- 0.1830376497095345
- -0.65909114183774
- 0.2342342785964413
- -0.24681363510747212
- -0.2848323988573455
- 0.05479422941401188
- -0.1404235994233593
- -0.368128839981092
- 0.3310873344588604
- -0.9526690865308381
- -0.4063697436842491
- -0.23366242167700546
- -0.26789910578625803
- -0.36111645682100885
- 0.1655690199203379
- -0.5543086379331685
- -0.35469904008128705
- -0.3398575075237951
- -0.2638355210854025
- -0.45414518296960643
- -0.505061781263594
- -0.208391513130146
- -0.19913263971187262
- -0.1745373539187387
- -0.3035290629009467
- -0.5544471804570209
- -0.6095216822446445
- -0.49030944388832787
- 0.0
- 0.3706556795576933
- -0.10887426845771503
- -0.2125771858238795
- -0.16398404504670974
- -0.5120108930019213
- -0.3432317385643626
- 0.0
- -0.06445460208306708
- 0.1856511780812655
- -0.07038449611634727
- 0.25977982937880023
- -0.43215856391196705
- -0.38910374996736624
- -0.13248727294454773
- -0.03627304316451023
- 0.7426098058787926
- 0.4981875077623686
