semver: 1.0.0
version: '2025-12-31'
metadata:
  simulation_manifest: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084240Z/manifest.json
  simulation_config_path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/layer1/1A/models/hurdle/hurdle_simulation.priors.yaml
  seed: 9248923
  created_utc: 20251231T084240Z
  inputs:
    priors:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/layer1/1A/models/hurdle/hurdle_simulation.priors.yaml
      sha256: 749033594fabcae3a1aa337d704e61ae66b2da009e14409c6218afacdbbb5f0d
    transaction_schema_merchant_ids:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/layer1/transaction_schema_merchant_ids/2025-12-31/transaction_schema_merchant_ids.parquet
      sha256: a5ce122a1c61a4247ba4ece8624a201fe824c72c10f352cfba74623e54a0cb12
    world_bank_gdp_per_capita:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/world_bank_gdp_per_capita/2025-04-15/gdp.parquet
      sha256: 1eb6d9ae47639b17fd41e7875c03247c4133a849b442c0e3ebe61a4cb2c06074
    gdp_bucket_map:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/gdp_bucket_map/2024/gdp_bucket_map.parquet
      sha256: 624c9d1029e81980c7d7eb368a7ed07d67c62d8423d0c053cdcd9c58a6c80a3b
    iso3166_canonical:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/iso/iso3166_canonical/2024-12-31/iso3166.parquet
      sha256: bfb68d1770abef6a74571cfea4d659eefb7b6c7b39e81f1b6cc483bd60bd8b5f
    logistic:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084240Z/logistic.parquet
      sha256: da7fdbd584b2d12f7b76d638b9549cbe67bc1e970dbdb92bb81fb70ddcf4b99a
    nb_mean:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084240Z/nb_mean.parquet
      sha256: fcb72e92243d34165dc48f9139a7d33d71ada0498aa6876658e27c8d9abdf290
dict_mcc:
- 742
- 743
- 744
- 763
- 780
- 1520
- 1711
- 1731
- 1740
- 1750
- 1761
- 1771
- 1799
- 2741
- 2791
- 2842
- 4011
- 4111
- 4112
- 4119
- 4121
- 4131
- 4214
- 4215
- 4225
- 4411
- 4457
- 4468
- 4511
- 4582
- 4722
- 4784
- 4789
- 4812
- 4814
- 4815
- 4816
- 4821
- 4829
- 4899
- 4900
- 5013
- 5021
- 5039
- 5044
- 5045
- 5046
- 5047
- 5051
- 5065
- 5072
- 5074
- 5085
- 5094
- 5099
- 5111
- 5122
- 5131
- 5137
- 5139
- 5169
- 5172
- 5192
- 5193
- 5198
- 5199
- 5200
- 5211
- 5231
- 5251
- 5261
- 5262
- 5271
- 5300
- 5309
- 5310
- 5311
- 5331
- 5399
- 5411
- 5422
- 5441
- 5451
- 5462
- 5499
- 5511
- 5521
- 5531
- 5532
- 5533
- 5541
- 5542
- 5551
- 5552
- 5561
- 5571
- 5592
- 5598
- 5599
- 5611
- 5621
- 5631
- 5641
- 5651
- 5655
- 5661
- 5681
- 5691
- 5697
- 5698
- 5699
- 5712
- 5713
- 5714
- 5715
- 5718
- 5719
- 5722
- 5732
- 5733
- 5734
- 5735
- 5811
- 5812
- 5813
- 5814
- 5815
- 5816
- 5817
- 5818
- 5912
- 5921
- 5931
- 5932
- 5933
- 5935
- 5937
- 5940
- 5941
- 5942
- 5943
- 5944
- 5945
- 5946
- 5947
- 5948
- 5949
- 5950
- 5960
- 5962
- 5963
- 5964
- 5965
- 5966
- 5967
- 5968
- 5969
- 5970
- 5971
- 5972
- 5973
- 5975
- 5976
- 5977
- 5978
- 5983
- 5992
- 5993
- 5994
- 5995
- 5996
- 5997
- 5998
- 5999
- 6010
- 6011
- 6012
- 6051
- 6211
- 6300
- 7011
- 7012
- 7032
- 7033
- 7210
- 7211
- 7216
- 7217
- 7221
- 7230
- 7251
- 7261
- 7273
- 7276
- 7277
- 7278
- 7296
- 7297
- 7298
- 7299
- 7311
- 7321
- 7322
- 7333
- 7338
- 7339
- 7342
- 7349
- 7361
- 7372
- 7375
- 7379
- 7392
- 7393
- 7394
- 7395
- 7399
- 7512
- 7513
- 7519
- 7523
- 7531
- 7534
- 7535
- 7538
- 7542
- 7549
- 7622
- 7623
- 7629
- 7631
- 7641
- 7692
- 7699
- 7800
- 7801
- 7802
- 7829
- 7832
- 7841
- 7911
- 7922
- 7929
- 7932
- 7933
- 7941
- 7991
- 7992
- 7993
- 7994
- 7995
- 7996
- 7997
- 7998
- 7999
- 8011
- 8021
- 8031
- 8041
- 8042
- 8043
- 8049
- 8050
- 8062
- 8071
- 8099
- 8111
- 8211
- 8220
- 8241
- 8244
- 8249
- 8299
- 8351
- 8398
- 8641
- 8651
- 8661
- 8675
- 8699
- 8734
- 8911
- 8931
- 8999
- 9211
- 9222
- 9223
- 9311
- 9399
- 9402
dict_ch:
- CP
- CNP
dict_dev5:
- 1
- 2
- 3
- 4
- 5
design:
  beta_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
  - gdp_bucket_onehot([1,2,3,4,5])
  beta_mu_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
beta:
- -0.9053241682765886
- 0.21396020154918544
- -0.43405548126332744
- -0.3878010454822819
- 0.05516958369433146
- 0.1068738906483275
- -0.039038275257253216
- -0.37449471242083104
- 0.025071587519717664
- 0.12565211030945367
- 0.45927643549841823
- 0.025349605636786555
- -0.99043040783481
- -0.02781295646040288
- -0.3509672093555116
- -0.11113148577928346
- 0.14996417379581176
- -0.9717546571373065
- 0.16592238472684603
- 0.6182928072230123
- 0.4334402500546438
- 0.08554197384466257
- 0.10214884800306473
- 0.38018577665714026
- 0.013685683570221008
- 0.5935426860935921
- 0.3285622801859995
- 0.3589821408715832
- -0.21374036074057406
- -0.5259073178322844
- 0.11202288922152069
- 0.015851419346465803
- -0.694647643779957
- -0.05216868422342179
- -0.22272817219041421
- 0.19799378444821567
- 0.20098580618108727
- 0.18674389722944423
- 0.2933124960834415
- -0.19231419790295193
- -0.4984880372904357
- -0.024594625113016196
- -0.23629677557101547
- 0.05235150823758567
- 0.3082131505488255
- 0.4067614680278262
- 0.3224746145990893
- 0.14359688109708613
- 0.19514727861035824
- 0.1629951477757259
- -0.09552179671765845
- 0.22716035675649282
- 0.10396831932784044
- 0.08080480506244808
- 0.33617542895815167
- 0.4418713812567132
- 0.3146851207939639
- 0.24892242734827572
- 0.33448824836139524
- -0.14247417904224213
- 0.10063622900305351
- 0.03118502265582454
- 0.18687579162104823
- 0.05347105304132469
- 0.09445120016709566
- -0.20938740591198732
- 0.16452128021184717
- 0.3371549273715608
- -0.32356972684777563
- 0.046003262505960145
- -0.17305256298986704
- 0.2313734759756334
- 0.45781233217877126
- -0.20162313797957876
- 0.6502856543809424
- 0.722824862009697
- 0.9594879787027875
- 0.8122544894685678
- 0.7113104705736402
- 0.9092894209088862
- 1.2792096095980365
- 0.8132577856597996
- 0.7214391377223253
- 0.9836536342113034
- 0.9772956415222086
- 0.7701145454008165
- 0.8769040764635985
- 0.932058295543979
- 1.0235170150712405
- 0.5385478288550822
- 0.8943776915696514
- 0.954335714285141
- 0.6519102464537229
- 0.7159993688437523
- 0.8207623269272531
- 0.7151595722822276
- 0.8287926608212942
- 0.8752140105675893
- 0.8544332519183062
- 0.5224962628849774
- 0.6127858877734033
- 0.32707063170529965
- 0.23884863988008595
- 0.11613857725412269
- 0.15181823297339003
- 0.19911389495184326
- 0.02354131968558938
- 0.26982542534087844
- 0.13327782224977522
- -0.12234371198505734
- 0.42618869737930937
- 0.11576542083887155
- 0.31686672681914674
- 0.34855637568386993
- -0.31140669610327454
- 0.5454512421796639
- 0.18527989457505845
- 0.20323232233739308
- -0.005510265503478692
- 0.39237441873962275
- 0.3821174078242405
- 0.38694415711190006
- 0.13244391973671066
- 0.3656948235268085
- 0.2632289065013701
- 0.16894450182128704
- 0.3305936191790904
- -0.11846513417666799
- 0.07408015968979426
- 0.1002313718188723
- 0.22973297809233753
- 0.2387777233208354
- -0.04206146609249372
- 0.25165712072373914
- 0.405852594750241
- 0.39747734060548284
- -0.6498759202123288
- -0.006747016900221048
- 0.4498746140389275
- 0.03415301434358922
- 0.11259989909029296
- -0.44418528446995786
- -0.19153871613415258
- 0.07248923476616004
- -0.12262996808067159
- -0.1113269969419824
- 0.10684455587628282
- -0.28203635855023956
- 0.04005340284355525
- 0.349818341523693
- 0.2838973305159993
- -0.2787314923380577
- -0.03810801655826276
- 0.434640292092247
- 0.15019507534308102
- -0.04964695357721198
- 0.22824418335219912
- 0.06179156605466096
- 0.059821375013715324
- 0.005564232879826866
- 0.25437525793423393
- 0.18636700442167758
- 0.2853158873224752
- 0.17278691776250055
- 0.21048821409825857
- -0.2089831095607581
- 0.2294129644085816
- 0.22598553566925184
- 0.4555698552511732
- 0.047749600166125845
- -0.06601265641732723
- 0.17724300150795352
- 0.22652207263650329
- 0.051750883260902304
- -0.22289161104540514
- -0.4229977225445152
- -0.1946208705434748
- -0.13883669293136777
- -0.4185707807739638
- 0.2426932791324295
- 0.2529323450942542
- -0.052119859068210504
- -0.8061898808747693
- -0.15576074627001896
- 0.2616311144875816
- -0.019409502001095993
- -0.2694450998689621
- 0.17059709252855795
- -0.33072348143244124
- -0.7721955076400568
- -0.1835200732313527
- 0.3234497143293896
- 0.31665732160348653
- -0.5625540246060869
- -0.5091003754168518
- -0.4173679234660795
- 0.22436512921817844
- -0.16382758210807044
- -0.44377245352322603
- -0.32524610717954794
- -0.21817649710114356
- -0.3569438855672883
- 0.19367808007594178
- -0.6519201688053929
- -0.47744792260435626
- -0.9075706755518156
- -0.9519325716550675
- -0.012234749096147643
- 0.29909013586950367
- -0.4746755441473258
- 0.41533848561638503
- -0.03934024779262822
- -0.17961181925006636
- -0.025822834415328722
- 0.05923925493252004
- -0.22371759893937332
- 0.40481631744161695
- -0.6934677779838763
- 0.26781460108102734
- 0.10853648028446389
- 0.1580738732318246
- -0.6935006685859116
- -0.5411299526064841
- -0.13225098893908382
- 0.5018357515333032
- -0.291728101363112
- -0.21519869173114947
- 0.6459653956995467
- -0.34650802401341374
- 0.3639383188025728
- -1.2408913768079386
- -0.147251739809623
- 0.3179194342949468
- -1.002172094530653
- 0.025649875589810807
- 0.20079570154268242
- -0.09929618449366419
- 0.24225879602913813
- -0.4063439097608455
- -1.012251583213237
- -0.5602955076002275
- -0.6823210337209606
- 0.7155551773037094
- -0.3009350934448067
- 0.20850139916656452
- -0.2744928491253581
- 0.07882764528234219
- -0.24227952495027305
- -0.457767816564452
- 0.45122772461134986
- -0.5090717268458416
- -0.7951108382323522
- -0.585956423905312
- -0.7779173312986808
- 0.028273171682819866
- -0.298530475106179
- 0.449980551830657
- -0.9656393463515371
- -0.5483290936367989
- -0.013392582587951807
- -0.12963716207955867
- -0.34134226808771584
- -0.1064650267805864
- -0.3760335451754383
- 0.15806737419880443
- -0.7161679197534719
- -0.31039125066710677
- -0.3025073457910513
- -0.7956545656023282
- -0.6152278670496616
- -0.2335816402496909
- -0.48349757546877814
- -0.2901247205172597
- -0.3467216854381896
- -0.5564021503617127
- -0.4218888242362564
- -0.013645439370503649
- -0.36291255080647505
- -1.5099606173640825
- 0.014428964158474762
- 0.08434570039420412
- -0.4121814515342124
- -0.5023063372167543
- 0.1897708923907672
- -0.20039934368735995
- 0.09440427764694997
- -1.6709587129931007
- -6.749026030002962
- -1.13436780924228
- -0.30127372427053833
- -0.5811532802869512
- 0.0
- -0.9053241633944523
- -0.5944562075167208
- -0.386827045099014
- -0.20606914607455667
- 0.003143679139133222
- 0.2788845398744571
beta_mu:
- 1.256372066771996
- 0.06312147743452744
- -0.2364104217220587
- -0.14440636156617848
- -0.16739897162696513
- -0.11859539009974854
- 0.011197035656219434
- -0.2775338052655968
- -0.15976334368278472
- -0.3097059144957285
- -0.08126924923951867
- -0.14150947730224056
- -0.22494137875987388
- -0.16437269825823192
- -0.030823199910579007
- -0.058875224066078466
- -0.2860000679537116
- 0.19409816517207554
- 0.12128239205028346
- 0.13423195486883194
- 0.2307143886465897
- 0.03838827302912264
- 0.362143864008737
- 0.19891427498169198
- 0.09544771296564583
- 0.21863082165534956
- 0.07692858893886456
- 0.22666461819598152
- 0.2827564328114469
- 0.20247110824648618
- 0.3306200134967273
- 0.17792421356972415
- -0.17486735386756663
- 0.41671052039415357
- 0.12143891426625848
- -0.007078034632884452
- -0.06661134685356912
- -0.04555938741345124
- -0.03440930770052663
- -0.19024129217388192
- -0.1496503213946978
- -0.14792117852557857
- -0.0909788866508726
- -0.017100380507502917
- 0.10788325999182309
- 0.04840411495803906
- 0.05600600231093978
- 0.22353897753667315
- 0.16887948870366093
- 0.10352679779407
- 0.14783342935686294
- -0.13481533978973417
- -0.01096157197798892
- -0.02666951265428424
- -0.026759170192429623
- 0.06430382753747269
- -0.11561646700368669
- -0.004718168329892774
- -0.13143230234296627
- 0.04123566340340753
- 0.23920561352506028
- 0.05415486913718092
- -0.0646230795106978
- -0.016160638197790303
- 0.14370921885870436
- 0.10049540825349876
- -0.10864331411851445
- 0.15596451176197018
- 0.22477675655681026
- -0.05587225200257828
- 0.057311065590742616
- -0.0031372032213374174
- 0.20812144350346473
- 0.0657406038890578
- 0.4724565705733417
- 0.46089777978518315
- 0.826136979515853
- 0.5307206339504159
- 0.3961576516244639
- 0.3970995915264274
- 1.0918000835368018
- 0.5372042725850086
- 0.5405442879926579
- 0.8510013859003094
- 0.7822933357362476
- 0.5797103557652938
- 0.5648389376823073
- 0.6117353968451936
- 0.8141534082515187
- 0.5260047505153577
- 0.7625442015843492
- 0.6246741626244559
- 0.6184471020101251
- 0.6465506195016845
- 0.5753229593647238
- 0.5543939713316395
- 0.5253498295847602
- 0.5873970248124585
- 0.5893830010373974
- 0.5690436639006962
- 0.04959462669884427
- -0.05847987074840788
- 0.02679147212966252
- 0.029879460312547103
- 0.24961620725668002
- 0.045042563378152475
- 0.07413018289036245
- -0.15386926638883125
- 0.0973922355865469
- 0.08534627342719828
- -0.0034574531827986314
- -0.24472155198333234
- 0.23872376875444884
- -0.03932972449505507
- -0.12216773947070747
- 0.09440762965143072
- 0.07903670717692388
- 0.014877426067477545
- -0.0989317391765024
- -0.05587132997178627
- 0.12907462266837919
- 0.07431225649650613
- 0.10162466342945403
- 0.28986718585321924
- 0.024601900907992545
- 0.051729969997193204
- 0.14755615069631076
- -0.17739816234655545
- 0.11000665981970173
- 0.1063974474633745
- 0.010406271733268814
- 0.0028863453683360906
- 0.06222421910679253
- 0.20716894669667477
- 0.07588506840705134
- 0.03495699252103194
- -0.26517769506699906
- 0.3118273050540845
- -0.10433067068805746
- 0.28102102574500654
- 0.19399485532934205
- 0.2534035183237984
- 0.045710960326361245
- 0.04918610188621825
- 0.1586039262562511
- 0.08989764737430363
- 0.03526195620336135
- -0.32213978904089235
- 0.13257664216369616
- 0.06404056023859632
- -0.06513150417616016
- -0.24802478848450446
- 0.03276139130034955
- 0.05885647632790465
- 0.12187663663452887
- 0.08180040844533128
- -0.01663313632724495
- 0.26016222241484044
- 0.08199268336083489
- 0.1379131929411551
- -0.17903965825909826
- 0.06259837453491192
- 0.05698585434169258
- 0.1301080638966025
- -0.07696963299421865
- 0.12451484905071306
- 0.10396875260734859
- 0.07044425537783423
- -0.009491011217245193
- -0.12429835069223831
- -0.20825285063332005
- -0.06050365213433156
- 0.06095296282268774
- -0.26681101752197883
- 0.12185169130295495
- 0.088766505064954
- -0.1064056629235959
- 0.08053147606377176
- -0.14665382642340904
- 0.16067806650194089
- -0.401158927321491
- 0.030792273702084403
- 0.05674114140753673
- -0.024253826818650133
- -0.0654005492241604
- 0.08662948433391743
- -0.002811840052035031
- -0.28846619646251676
- -0.031140470300004833
- -0.2770120496816021
- -0.3769999046570425
- -0.15707572288678165
- -0.09533174557640901
- -0.3390909981966157
- -0.20133419546632628
- -0.023854172033213415
- -0.035812257813665274
- 0.2552612296039618
- -0.07874103111870984
- 0.07451646504871248
- -0.11223175473193756
- -0.2456607083774081
- 0.09470475426886968
- 0.005824430639650816
- -0.11926845890612062
- -0.32169618241895
- -0.2138540913895653
- -0.15526085758055802
- -0.022013317906339237
- 0.2215293325624884
- -0.08292493373701494
- 0.14769956283571437
- -0.14487943419393398
- -0.15428552758798236
- -0.14193894943355345
- -0.22042410557000777
- -0.054413417867736534
- -0.19278620183591072
- -0.14124843327119888
- -0.3589826838937164
- -0.27109800024443403
- -0.09783028112398677
- -0.13841033391276672
- -0.3728218118628334
- -0.26376792833543
- -0.03679930605423977
- -0.12414403817204817
- 0.1589794744405604
- -0.2555154250588749
- -0.16123589458379833
- -0.5015192182081798
- -0.014167399288998453
- -0.10456589557955692
- -0.3664092188385819
- -0.05677789634819015
- -0.034572686005052554
- -0.4274869725986458
- 0.01535247553173755
- -0.39159003954895244
- 0.17170072485973215
- -0.41742031444996924
- -0.009564699761494605
- -0.009752740534037532
- -0.17092165056216013
- -0.24441904801885675
- -0.016976155176019622
- -0.3115344417610398
- -0.1232669469521951
- -0.03414504218124271
- -0.14409035734141376
- -0.2064619506182598
- -0.47319225929231096
- -0.36035318753283613
- -0.070933345912131
- -0.10301124683065818
- -0.1906310839250947
- -0.1655246613640131
- -0.2614207370760642
- -0.19593524342122137
- -0.0741798730405142
- -0.2002747439258591
- -0.17155789543423328
- -0.037088859060863524
- -0.2368438131068375
- -0.37072138186104153
- -0.5275145428820364
- -0.12287515035002333
- -0.05677789634819008
- 0.0869012369000314
- -0.13002308665775716
- -0.33769856245404173
- -0.4495053528053675
- -0.10261706600996635
- -0.3342637446019015
- -0.227971206121533
- -0.3451837327391093
- -0.4412712969253854
- -0.3435294429740042
- -0.4569474533460682
- -0.21023054424689963
- -0.3617610620240564
- -0.4854022858550615
- -0.276652496373351
- -0.28031543532536823
- -0.294903364161009
- -0.7918128512168335
- -0.23379857718135041
- 0.0
- -0.39808536656126897
- -0.4224697289257299
- -0.09094151701103503
- 0.0
- 0.9217351455647282
