semver: 1.0.0
version: '2025-12-31'
metadata:
  simulation_manifest: ${FRAUD_DETECTION_ROOT}/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084240Z/manifest.json
  simulation_config_path: ${FRAUD_DETECTION_ROOT}/config/layer1/1A/models/hurdle/hurdle_simulation.priors.yaml
  seed: 9248923
  created_utc: 20251231T084240Z
  inputs:
    priors:
      path: ${FRAUD_DETECTION_ROOT}/config/layer1/1A/models/hurdle/hurdle_simulation.priors.yaml
      sha256: 749033594fabcae3a1aa337d704e61ae66b2da009e14409c6218afacdbbb5f0d
    transaction_schema_merchant_ids:
      path: ${FRAUD_DETECTION_ROOT}/reference/layer1/transaction_schema_merchant_ids/2025-12-31/transaction_schema_merchant_ids.parquet
      sha256: a5ce122a1c61a4247ba4ece8624a201fe824c72c10f352cfba74623e54a0cb12
    world_bank_gdp_per_capita:
      path: ${FRAUD_DETECTION_ROOT}/reference/economic/world_bank_gdp_per_capita/2025-04-15/gdp.parquet
      sha256: 1eb6d9ae47639b17fd41e7875c03247c4133a849b442c0e3ebe61a4cb2c06074
    gdp_bucket_map:
      path: ${FRAUD_DETECTION_ROOT}/reference/economic/gdp_bucket_map/2024/gdp_bucket_map.parquet
      sha256: 624c9d1029e81980c7d7eb368a7ed07d67c62d8423d0c053cdcd9c58a6c80a3b
    iso3166_canonical:
      path: ${FRAUD_DETECTION_ROOT}/reference/iso/iso3166_canonical/2024-12-31/iso3166.parquet
      sha256: bfb68d1770abef6a74571cfea4d659eefb7b6c7b39e81f1b6cc483bd60bd8b5f
    logistic:
      path: ${FRAUD_DETECTION_ROOT}/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084240Z/logistic.parquet
      sha256: da7fdbd584b2d12f7b76d638b9549cbe67bc1e970dbdb92bb81fb70ddcf4b99a
    nb_mean:
      path: ${FRAUD_DETECTION_ROOT}/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084240Z/nb_mean.parquet
      sha256: fcb72e92243d34165dc48f9139a7d33d71ada0498aa6876658e27c8d9abdf290
dict_mcc:
- 742
- 743
- 744
- 763
- 780
- 1520
- 1711
- 1731
- 1740
- 1750
- 1761
- 1771
- 1799
- 2741
- 2791
- 2842
- 4011
- 4111
- 4112
- 4119
- 4121
- 4131
- 4214
- 4215
- 4225
- 4411
- 4457
- 4468
- 4511
- 4582
- 4722
- 4784
- 4789
- 4812
- 4814
- 4815
- 4816
- 4821
- 4829
- 4899
- 4900
- 5013
- 5021
- 5039
- 5044
- 5045
- 5046
- 5047
- 5051
- 5065
- 5072
- 5074
- 5085
- 5094
- 5099
- 5111
- 5122
- 5131
- 5137
- 5139
- 5169
- 5172
- 5192
- 5193
- 5198
- 5199
- 5200
- 5211
- 5231
- 5251
- 5261
- 5262
- 5271
- 5300
- 5309
- 5310
- 5311
- 5331
- 5399
- 5411
- 5422
- 5441
- 5451
- 5462
- 5499
- 5511
- 5521
- 5531
- 5532
- 5533
- 5541
- 5542
- 5551
- 5552
- 5561
- 5571
- 5592
- 5598
- 5599
- 5611
- 5621
- 5631
- 5641
- 5651
- 5655
- 5661
- 5681
- 5691
- 5697
- 5698
- 5699
- 5712
- 5713
- 5714
- 5715
- 5718
- 5719
- 5722
- 5732
- 5733
- 5734
- 5735
- 5811
- 5812
- 5813
- 5814
- 5815
- 5816
- 5817
- 5818
- 5912
- 5921
- 5931
- 5932
- 5933
- 5935
- 5937
- 5940
- 5941
- 5942
- 5943
- 5944
- 5945
- 5946
- 5947
- 5948
- 5949
- 5950
- 5960
- 5962
- 5963
- 5964
- 5965
- 5966
- 5967
- 5968
- 5969
- 5970
- 5971
- 5972
- 5973
- 5975
- 5976
- 5977
- 5978
- 5983
- 5992
- 5993
- 5994
- 5995
- 5996
- 5997
- 5998
- 5999
- 6010
- 6011
- 6012
- 6051
- 6211
- 6300
- 7011
- 7012
- 7032
- 7033
- 7210
- 7211
- 7216
- 7217
- 7221
- 7230
- 7251
- 7261
- 7273
- 7276
- 7277
- 7278
- 7296
- 7297
- 7298
- 7299
- 7311
- 7321
- 7322
- 7333
- 7338
- 7339
- 7342
- 7349
- 7361
- 7372
- 7375
- 7379
- 7392
- 7393
- 7394
- 7395
- 7399
- 7512
- 7513
- 7519
- 7523
- 7531
- 7534
- 7535
- 7538
- 7542
- 7549
- 7622
- 7623
- 7629
- 7631
- 7641
- 7692
- 7699
- 7800
- 7801
- 7802
- 7829
- 7832
- 7841
- 7911
- 7922
- 7929
- 7932
- 7933
- 7941
- 7991
- 7992
- 7993
- 7994
- 7995
- 7996
- 7997
- 7998
- 7999
- 8011
- 8021
- 8031
- 8041
- 8042
- 8043
- 8049
- 8050
- 8062
- 8071
- 8099
- 8111
- 8211
- 8220
- 8241
- 8244
- 8249
- 8299
- 8351
- 8398
- 8641
- 8651
- 8661
- 8675
- 8699
- 8734
- 8911
- 8931
- 8999
- 9211
- 9222
- 9223
- 9311
- 9399
- 9402
dict_ch:
- CP
- CNP
design:
  beta_phi_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
  - ln_gdp_pc_usd_2015
beta_phi:
- 1.1958968056709922
- -0.054477095712569694
- -0.056687121836201906
- -0.0531189200090798
- -0.053858972254382215
- -0.0511355202729682
- -0.05151451492137799
- -0.05226265765756109
- -0.05034028687459934
- -0.05689475630291003
- -0.053554699147175165
- -0.052497694652171065
- -0.05319463905389549
- -0.04968106597948487
- -0.05429035023613698
- -0.054819676607228654
- -0.050578594805576894
- -0.05141019636413991
- -0.0524023770489783
- -0.05551314518441842
- -0.05537131128386
- -0.05374255579123928
- -0.05140843368524552
- -0.05532221887167257
- -0.05567004979882624
- -0.05478195666234361
- -0.05400475977872887
- -0.05308077155133831
- -0.05298411392008468
- -0.05354660851058707
- -0.05179264612026481
- -0.05261317190169025
- -0.05338275261117829
- -0.05714897407397678
- -0.053372632403905315
- -0.05098787792922871
- -0.05405205430424113
- -0.05306978254148606
- -0.052247358881280306
- -0.0529158629000079
- -0.05770975916786349
- -0.05186422531603706
- -0.05545753392519005
- -0.05071790008482009
- -0.05151433510343292
- -0.05548404875807141
- -0.053457630750186835
- -0.05611486405369067
- -0.05430875185568772
- -0.054317811778542516
- -0.05080613158439669
- -0.051664641107067866
- -0.05117049742735869
- -0.05335781698891422
- -0.053366548840096645
- -0.054514308958812735
- -0.05134983772663238
- -0.05271766149587159
- -0.05035419093514917
- -0.05264162119457862
- -0.051989413643333295
- -0.054806135052611456
- -0.05153667779790921
- -0.05188978848319347
- -0.05190875323528956
- -0.05540012143046991
- -0.05523514071006732
- -0.053765802512294264
- -0.04944069589743616
- -0.051464192363423575
- -0.054644119069899515
- -0.052578077569296375
- -0.053382901690852004
- -0.0525121931589833
- -0.05131826096319458
- -0.05361849405765531
- -0.055262009751893625
- -0.05250350913620294
- -0.05270678956632233
- -0.054905835752759334
- 0.8168756648967116
- 0.20569278151350548
- 0.2589107747043436
- 0.28492578042265376
- -0.05274302559289184
- 0.3846465712154365
- 0.5737913213880502
- 0.023696105702954724
- 0.46286384830673627
- 0.5608184256205732
- -0.011759777382038098
- 0.13648658903109778
- 1.8619313471965107
- 0.4516455785298052
- 0.02830002116867584
- 0.40814705272955065
- 0.7577690906239115
- 0.9067131541857814
- 0.5336402968232519
- 1.2112927324449658
- -0.05499319497353339
- -0.05282702834088872
- -0.05259076470692381
- -0.052259697595833925
- -0.05663761785340505
- -0.05418130829756096
- -0.05144806367017352
- -0.053076416420679985
- -0.05465810631749327
- -0.05423850803100061
- -0.05019724490998958
- -0.05760470426998068
- -0.05291186016216351
- -0.052845839839452007
- -0.052012149695290236
- -0.04885764547069337
- -0.05658704630429357
- -0.053902992305403956
- -0.05240389549913341
- -0.055333725635226566
- -0.0520183790051472
- -0.0542338248619637
- -0.05283149256283532
- 1.6088359393058156
- 0.36447205199953114
- 0.4356848673647252
- 1.5995851381820516
- 0.031791037319120294
- 0.13472085966682382
- 0.27775229043326477
- 0.827638649856973
- -0.05487006602978657
- -0.054594818011801764
- -0.05221900592852919
- -0.053107100908691134
- -0.05496025963196521
- -0.05341515531262904
- -0.05446284313286014
- -0.054880745458695826
- -0.05060678560061321
- -0.051975921156643554
- -0.05587251267600002
- -0.05235999280407594
- -0.050851800661989154
- -0.051238529760938824
- -0.055980583512067056
- -0.05171848996598726
- -0.050806353600916135
- -0.05616534732573094
- -0.053366961568934446
- -0.05361964268362082
- -0.052075056934176044
- -0.05074970207044317
- -0.052069478390240675
- -0.0532859870623067
- -0.05192491850162988
- -0.05322657556450015
- -0.052623962924764615
- -0.05309162762503642
- -0.05480148481067966
- -0.05694808203047358
- -0.05260532472867185
- -0.053769690535690015
- -0.05474417228563809
- -0.050722126899972624
- -0.050492577682604324
- -0.05220255326221486
- -0.05344160302600963
- -0.053052428181675715
- -0.05329667116977959
- -0.05404783634633327
- -0.0535800417102478
- -0.05297900608880692
- -0.053470253565681726
- -0.05189908514455959
- -0.055725792039232926
- -0.058143107064304866
- -0.05250185202921416
- -0.05512692096405334
- -0.0510393119238462
- -0.051560806420117476
- -0.053929375090976964
- -0.05384954777479884
- -0.05528668629846295
- -0.05362715376749454
- -0.05164525481896159
- -0.05084098501936443
- -0.05484480668138004
- -0.051034463221888524
- -0.0578099096749746
- -0.05596393130232397
- -0.05132615678265829
- -0.05154704503927973
- -0.05207246138244457
- -0.058164357992003805
- -0.052247728701519246
- -0.053002702058082496
- -0.05184160766839693
- -0.05099780556802513
- -0.0514896861410231
- -0.054606983358013936
- -0.053880007684266054
- -0.05464942112620521
- -0.05214754665871999
- -0.056793357856079085
- -0.04920557001274274
- -0.05020224823569104
- -0.05219174611456811
- -0.05448554635269466
- -0.054475165314620703
- -0.0514660168828845
- -0.05388323154348507
- -0.05645565937293251
- -0.055721501156693956
- -0.05113428110699445
- -0.051678975000922674
- -0.05257943439838649
- -0.05593393200390982
- -0.052334188187021034
- -0.049827102952651456
- -0.05450859704482064
- -0.05169774803066216
- -0.05337614812820949
- -0.05790355812584812
- -0.051095366469519524
- -0.04927516423168157
- -0.053510292633251515
- -0.05176205109834676
- -0.05321557784265677
- -0.05133875137396108
- -0.05382593490943184
- -0.05252821914310533
- -0.053252570710902974
- -0.054745465620819625
- -0.06005039289247052
- -0.056324382830549635
- -0.05276614606816865
- -0.050600496063824676
- -0.053717615568387514
- -0.05697138471369825
- -0.05010639051077257
- -0.053422855811944905
- -0.05083051344043328
- -0.05303559626340757
- -0.05183316964015854
- -0.05318810248497223
- -0.05149070298395496
- -0.051895428383775075
- -0.052692525796869484
- -0.05501676727995866
- -0.05357768065010872
- -0.05390422448875675
- -0.0569794454403116
- -0.052932666649349126
- -0.05006009588484056
- -0.05677084151478046
- -0.05514283545226413
- -0.04960332509012652
- -0.04936607873692889
- -0.05434839571168558
- -0.05376259773589024
- -0.0502083735797333
- -0.05288551090743152
- -0.05226482281855501
- -0.05079801587752969
- -0.05228521706934097
- -0.0533145127628374
- -0.05331439889264479
- -0.05309139909050272
- -0.05119393548254973
- -0.05638423393814794
- -0.056606835033659306
- -0.0534104338523819
- -0.0500472191871374
- -0.0577925870536079
- -0.053933659967290465
- -0.051000583323801724
- -0.05319747686206156
- -0.056198940133097744
- -0.050621525786421796
- -0.056342651735143835
- -0.049170287638256975
- -0.05223354878837833
- -0.05450437961750701
- -0.052719664421268776
- -0.04733694377115241
- -0.06053796919069823
- 0.0
- -0.04891727286548815
- -0.05561394480188333
- -0.05029265176901742
- 0.0
- 1.1958952674391998
- -0.003596972694930189
