semver: 1.0.0
version: '2026-02-12'
metadata:
  simulation_manifest: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2026-01-03/seed=9248923/20260103T184840Z/manifest.json
  simulation_config_path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/layer1/1A/models/hurdle/hurdle_simulation.priors.yaml
  seed: 9248923
  created_utc: 20260214T125000Z
  inputs:
    priors:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/layer1/1A/models/hurdle/hurdle_simulation.priors.yaml
      sha256: 7588df761e0c4ba3f09adced410db1ffb79fd7236b2ad99c6ef0362a230fa119
    transaction_schema_merchant_ids:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/layer1/transaction_schema_merchant_ids/2026-01-03/transaction_schema_merchant_ids.parquet
      sha256: df2f940f061a09a018e133828c9b7b2e7e442a1052b5c0105ef927e2b7c696e8
    world_bank_gdp_per_capita:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/world_bank_gdp_per_capita/2025-04-15/gdp.parquet
      sha256: 1eb6d9ae47639b17fd41e7875c03247c4133a849b442c0e3ebe61a4cb2c06074
    gdp_bucket_map:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/gdp_bucket_map/2024/gdp_bucket_map.parquet
      sha256: 624c9d1029e81980c7d7eb368a7ed07d67c62d8423d0c053cdcd9c58a6c80a3b
    iso3166_canonical:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/iso/iso3166_canonical/2024-12-31/iso3166.parquet
      sha256: bfb68d1770abef6a74571cfea4d659eefb7b6c7b39e81f1b6cc483bd60bd8b5f
    logistic:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2026-01-03/seed=9248923/20260103T184840Z/logistic.parquet
      sha256: e52e774343461db1071bf79d8166bc90e4ee9a78a43c935bb1ae0780afd05b00
    nb_mean:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2026-01-03/seed=9248923/20260103T184840Z/nb_mean.parquet
      sha256: 4e7ca3ee110b8dfb22d66b55dfcfa5264efc0a5d12202591c5301e023a51aea7
  remediation:
    wave: P4.R4A
    change: beta_mu_non_intercept_downscale_for_home_support
    delta_intercept: 2.2
    rationale: reduce upstream home-country outlet concentration for 1B collapse-sensitive
      countries while preserving 1A freeze floor
    parent_bundle: version=2026-02-12/20260212T200823Z
    note: retain P1.2 coefficient shape; concentration to be evaluated with S2 poisson
      inversion patch
    beta_mu_non_intercept_scale: 2.0
    intercept_recenter: none_first_pass
    non_intercept_scale: 0.95
    intercept_delta: 0.0
dict_mcc:
- 742
- 743
- 744
- 763
- 780
- 1520
- 1711
- 1731
- 1740
- 1750
- 1761
- 1771
- 1799
- 2741
- 2791
- 2842
- 4011
- 4111
- 4112
- 4119
- 4121
- 4131
- 4214
- 4215
- 4225
- 4411
- 4457
- 4468
- 4511
- 4582
- 4722
- 4784
- 4789
- 4812
- 4814
- 4815
- 4816
- 4821
- 4829
- 4899
- 4900
- 5013
- 5021
- 5039
- 5044
- 5045
- 5046
- 5047
- 5051
- 5065
- 5072
- 5074
- 5085
- 5094
- 5099
- 5111
- 5122
- 5131
- 5137
- 5139
- 5169
- 5172
- 5192
- 5193
- 5198
- 5199
- 5200
- 5211
- 5231
- 5251
- 5261
- 5262
- 5271
- 5300
- 5309
- 5310
- 5311
- 5331
- 5399
- 5411
- 5422
- 5441
- 5451
- 5462
- 5499
- 5511
- 5521
- 5531
- 5532
- 5533
- 5541
- 5542
- 5551
- 5552
- 5561
- 5571
- 5592
- 5598
- 5599
- 5611
- 5621
- 5631
- 5641
- 5651
- 5655
- 5661
- 5681
- 5691
- 5697
- 5698
- 5699
- 5712
- 5713
- 5714
- 5715
- 5718
- 5719
- 5722
- 5732
- 5733
- 5734
- 5735
- 5811
- 5812
- 5813
- 5814
- 5815
- 5816
- 5817
- 5818
- 5912
- 5921
- 5931
- 5932
- 5933
- 5935
- 5937
- 5940
- 5941
- 5942
- 5943
- 5944
- 5945
- 5946
- 5947
- 5948
- 5949
- 5950
- 5960
- 5962
- 5963
- 5964
- 5965
- 5966
- 5967
- 5968
- 5969
- 5970
- 5971
- 5972
- 5973
- 5975
- 5976
- 5977
- 5978
- 5983
- 5992
- 5993
- 5994
- 5995
- 5996
- 5997
- 5998
- 5999
- 6010
- 6011
- 6012
- 6051
- 6211
- 6300
- 7011
- 7012
- 7032
- 7033
- 7210
- 7211
- 7216
- 7217
- 7221
- 7230
- 7251
- 7261
- 7273
- 7276
- 7277
- 7278
- 7296
- 7297
- 7298
- 7299
- 7311
- 7321
- 7322
- 7333
- 7338
- 7339
- 7342
- 7349
- 7361
- 7372
- 7375
- 7379
- 7392
- 7393
- 7394
- 7395
- 7399
- 7512
- 7513
- 7519
- 7523
- 7531
- 7534
- 7535
- 7538
- 7542
- 7549
- 7622
- 7623
- 7629
- 7631
- 7641
- 7692
- 7699
- 7800
- 7801
- 7802
- 7829
- 7832
- 7841
- 7911
- 7922
- 7929
- 7932
- 7933
- 7941
- 7991
- 7992
- 7993
- 7994
- 7995
- 7996
- 7997
- 7998
- 7999
- 8011
- 8021
- 8031
- 8041
- 8042
- 8043
- 8049
- 8050
- 8062
- 8071
- 8099
- 8111
- 8211
- 8220
- 8241
- 8244
- 8249
- 8299
- 8351
- 8398
- 8641
- 8651
- 8661
- 8675
- 8699
- 8734
- 8911
- 8931
- 8999
- 9211
- 9222
- 9223
- 9311
- 9399
- 9402
dict_ch:
- CP
- CNP
dict_dev5:
- 1
- 2
- 3
- 4
- 5
design:
  beta_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
  - gdp_bucket_onehot([1,2,3,4,5])
  beta_mu_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
beta:
- 1.060423738098163
- -0.12355519992395293
- 0.6491379679497475
- 0.2529727775030237
- -0.9053807799197521
- 0.014423710998464628
- -0.3702318930787536
- -0.33798272406458135
- 1.1610070846442218
- 0.7208970768869805
- -0.25345560531329464
- -0.25123849181546987
- 0.2726066590800409
- 1.2152963768700502
- -0.6474758343442504
- 0.565548433318983
- -0.5471936098788812
- 1.1860556663818425
- 0.4244529740204774
- -0.08517964388838668
- 0.5635306350190763
- 0.27736169825485363
- 0.627943764512698
- 0.5148964368343001
- 0.5643290338453254
- 0.1705034667554028
- 0.17676049276390685
- 0.08148455192436094
- 0.534510098607455
- -0.33868676841838374
- 0.5744346291624133
- 0.0709378810256845
- 0.42004227953758577
- 1.2144401361355912
- 0.15561957679748165
- -0.32807931265784435
- -5.556305332257111
- 0.48408096272473317
- 0.053158358187763974
- 1.6773937758385775
- -0.3809119743500184
- 0.4103959843692794
- 0.6561634844315043
- -0.01899151950168879
- -0.03938299136530882
- -0.6096115081711363
- 0.6469796312451648
- -0.008403409481851245
- 0.4508352798838222
- 0.3096969289422762
- 0.42958998294609746
- 0.32187323958378106
- 0.3136845620140716
- 0.30501974624349865
- 0.029754587292650993
- -0.19305090038840828
- 0.44022042006851897
- -0.3511290688263239
- -0.616899534893281
- 0.31052970922422374
- 0.03177549751542108
- 0.2465158212944597
- -0.7571067433758978
- -1.1187817701065939
- -0.35569491279675375
- 0.08108135818967457
- 0.5355901360052674
- 0.07771930498233827
- -0.18455558901143093
- 0.6542089863011594
- 0.7294759746907631
- 0.5114587441242302
- 1.129145221859367
- 0.012004445200800748
- 0.6536315473173535
- 0.6472664966104283
- 0.8167201031618881
- -0.9200961000224505
- 0.3234386004177801
- -0.1407714758328826
- 1.118650529348533
- 0.9178522263028093
- 0.4324916977868366
- 1.026268131833808
- 1.2358220758664928
- 0.8226844851451212
- 1.205228197126019
- 0.537910030489806
- 1.6197447599597357
- 1.7827265356063569
- 0.52727979602855
- 1.7896311722781808
- 1.3116165800611326
- 0.30759396767768676
- 0.7285012896845053
- 0.24986782851404218
- 0.7913863276947197
- 0.4247518534644013
- 0.22000358665491376
- 0.572134893824342
- 1.0945468471325377
- 0.3038863184814762
- 0.9851975338482422
- 0.14853131856908103
- 0.7808474756888278
- -1.1591157441190527
- 0.32158606390650646
- -0.11123114085125216
- 0.5408610628888055
- 0.09910126040310344
- 0.4206389907684716
- 0.5059745896067693
- 0.66355972467946
- 0.23459524178603194
- 0.8345064917189555
- 0.6787038147465325
- 0.5329393986353501
- -0.00016901876176376565
- 0.7120846936865396
- -0.2921694636642049
- 0.7193193693219733
- -0.24945962571933994
- 0.7123498761770943
- 0.2603652367105659
- 0.9286097860882617
- 0.7316780589869276
- 0.44536536414169137
- -0.8368946858984847
- 0.6112666575729918
- 0.49880809492698625
- 0.19252197480758085
- 0.13011793271903327
- 1.0270106992691785
- 0.30419149900727954
- -0.13262183854760645
- -0.2816905960153228
- 0.09160978483191087
- 0.10016973819316388
- -1.6916911208557417
- 0.27471755339625364
- -0.28601995337608527
- -0.1932736735529803
- 0.39745834341752617
- 0.05849018240789916
- -0.17200926247803128
- 0.34185105846244385
- 0.21424273463322854
- -0.19811575551993937
- -0.3492111416222488
- -0.12294813531433404
- 0.05998233231905007
- -0.17338310867943182
- 0.10589704950104696
- 0.63559054573423
- -0.2791978457532176
- 0.5322142084392832
- 0.5830055604401227
- 0.5604014881094035
- 0.7249258346579842
- -1.0401230540046884
- 0.24911202687162518
- 0.4225773207639346
- 0.25204916343199174
- -0.27812631424952966
- 0.2409284594984029
- -0.47241177823345976
- -0.2692367588144125
- 0.18603522312108417
- 0.0067348759500703735
- 0.3582752194801141
- 0.16297976987876336
- 0.4833661356899183
- -0.5441005509571241
- -0.21085265981801307
- -0.10221069566261512
- -0.5628037626774556
- -0.41774885208914647
- 0.19951333491186213
- -0.38914008051359134
- -0.08492581038926812
- -0.45543404859785874
- 0.14080407816449503
- -0.6924834819680055
- -0.8370565946384365
- 0.3723020749859881
- -0.815230049941712
- 0.22934613239564317
- -0.5046848240361851
- 0.16575222124721076
- -1.4250638199596695
- 0.038017874265135865
- -0.18253595356549346
- -0.3715819598822544
- -0.8611853217790802
- -0.006139643333341906
- 0.16830375686740193
- 0.3173746341605253
- 0.3002345517329067
- 0.17623135666560077
- -0.7287956082173863
- -0.9610628779015137
- 0.40605076981653027
- 0.18226222439069437
- -0.3121466589126882
- 0.22762008657128616
- 0.044149816094843135
- -0.03943527552502154
- 0.3863088330089787
- 0.480452955555161
- -0.2049837814597023
- 0.050385871559901374
- -0.86970753459761
- -0.8251194618170815
- 0.9662631116481216
- -0.6631237938563594
- -0.10926841597306858
- -0.5961988754115395
- -0.8079011046540583
- -0.3132044063138858
- 0.511834421544762
- -1.1616780169153382
- 0.3505700329797492
- 0.05964695186496368
- -1.626218180702916
- 0.5302477212829408
- 0.4500502746449453
- -0.17234828361777377
- 0.133881736839792
- 0.4253774524525599
- 0.23354527852141105
- -0.3302777701554893
- -1.3740227763719435
- 0.4610965540307373
- -0.8513626416075153
- -0.47945831812878925
- 0.18404223851638873
- -0.8964049444686198
- -0.27064157337001665
- 0.4179557786050321
- -0.44259527303420265
- 0.43009217402544675
- -0.3137971898815487
- -0.35204769932807856
- -0.6105098962679495
- 0.003493954948993786
- -0.7610815837116025
- 0.18722894893688763
- -0.7706489439135431
- -0.9318324397853136
- 0.17066248487527066
- -0.7111113170053198
- -0.3294506455420305
- -0.8509799257045816
- -0.5791717226599604
- -0.1997006930480287
- -0.30232660716434606
- -0.7696726379425509
- 0.16322162315629277
- -0.45996453998376957
- 0.4082491375430201
- -0.04016180640420546
- -0.3237080982593376
- -0.5319459418262676
- -0.6150641506884175
- 0.48126632741328323
- 0.3259158291079374
- -0.5596192163629057
- 0.31632966227601356
- -0.47700378139621824
- -0.8337738578537423
- -0.38369089735113415
- -0.7091902266158834
- -0.4262592921097843
- -0.7655132657256938
- -0.5773276246783964
- -6.850110469270412
- -0.8514134414452039
- 0.049427516618458206
- -0.03575410450426962
- 0.48972276897077505
- 0.013318418254464292
- -0.09098549330811943
- -6.86544681845988
- -0.37612537944065366
- 0.41839605148232034
- -0.556639500130873
- -1.0632389090792185
- -0.8476479959836294
- 0.3589885724100375
- -0.9218571039778817
- -0.17488049754930932
- -0.28750660784290355
- -0.8520696527283449
- -0.7844325078593459
- -0.4810454702602077
- -0.2560555372181693
- -0.007979490332166226
- 0.38993674638828835
beta_mu:
- 1.7814957339620379
- -0.6734616418042317
- -0.39083906429970017
- 0.022676096091329468
- -0.915814271367844
- -0.23446692670969171
- 0.657539547663693
- 0.1273670400511595
- 0.37804822599572013
- -0.06137464905593889
- 0.4440695000219941
- -0.41403340861658483
- 0.02945601822240127
- 0.4923471254463611
- -1.244612136934258
- -0.5194773255923953
- 0.06585050487557426
- 0.3248948628433256
- 0.01814824905727452
- 0.21847240660647263
- 0.19136351787286923
- 0.9771501431594545
- 0.3718500526230024
- 0.5330384669615214
- 0.09701872549334392
- 0.7950764798871583
- -0.39839145413341426
- 0.19410547140256687
- 1.1087294055705392
- 0.32381793202153436
- 0.35811931081482273
- -0.27618823153146693
- 0.448594328351301
- 0.8655645925152777
- -0.16030383034266885
- 0.019181374062185085
- 0.0
- -0.1788403854160385
- -0.30030750628779224
- -0.3807079986831785
- 0.1459728013418415
- -0.10810627579277948
- -0.17843368671524276
- 0.0026642844958036428
- -0.5980970367175672
- 0.640785037655634
- -0.04015828836542194
- 0.2758939693184226
- -0.079146955355499
- 0.020007932644774063
- -0.22677589859689382
- -0.03672180435515865
- 0.2110010415390729
- -0.32495628590808795
- -0.6734616418042307
- -0.48594874437293695
- -0.14981239320640272
- -0.11020927404411951
- -0.3860509575533132
- 0.06451101848410029
- -0.7234953783075718
- 0.11897099868379812
- -0.9158142713678438
- 1.087886418616426
- 0.25049828839010807
- 0.2441343731927489
- 0.21422255608499502
- 0.01193718689718948
- -0.33839979949951837
- 0.06140373821354195
- 0.18368314100139488
- 0.19754913938188493
- 0.011933755169378496
- 0.03788681127007079
- 1.0072714258638504
- 0.41789817916739397
- 0.484674664938252
- 0.3392262563514997
- 0.44599727693997615
- 0.8335053884822335
- 1.2822837358591246
- 0.7185366603899016
- 1.4311607449625814
- 1.1155667692237894
- 1.2120913022628723
- 0.689551997661591
- 0.9290918732250026
- 0.8294360836092589
- 0.931875579898819
- 0.9031202336519418
- 0.7953362923486634
- 1.2273227232243047
- 1.495117211656351
- 0.9291046909246949
- 0.7613926832596201
- 0.5954885768311939
- 0.5389567238438056
- 0.7623620019322918
- 0.3416759574643457
- 0.5961032765310388
- 0.1708738299684025
- -0.19543875248445736
- 0.4195950194996879
- 0.4540287264789389
- 0.4023327668262567
- 0.12734582281976645
- -0.5657710872662404
- 0.2636717441928277
- 0.46144121185047343
- 0.33357546406404326
- -0.1666552581521568
- 0.877675941754247
- -0.17029208796640025
- 0.3120667620859499
- 0.03974388006106249
- -0.2122888830896243
- 0.2768465906553596
- 0.8003568415595156
- 0.13726110470545552
- 0.680709083260274
- -0.16147754979878848
- 0.24409595657144278
- 0.7169603286162191
- 0.128363962807555
- 0.3344845436792981
- 0.3793422872072101
- 0.5932292372570902
- 0.6932630628575517
- -0.0828366376565617
- 0.39979014946935654
- 0.46695353727522176
- 0.09814467116521458
- -0.596239975701783
- -0.303513849295105
- 0.37295635575831837
- 0.2071276616556476
- -0.42340703465790946
- 0.020007932644773303
- 0.12728221351765878
- -0.46763149443222635
- 0.5792685024800484
- -0.3437642547757559
- 0.16139551319876466
- 0.01135032130250294
- 0.06790450747632903
- -0.5964672364501478
- -0.047198661056874154
- -0.25771792748970757
- -0.2447738007732405
- 0.799386867781038
- 0.13263146331750267
- -0.2390663761681873
- -0.42120430940990133
- 0.08450287454474888
- 1.1891328955294518
- -0.26910794313088215
- -0.372915307462705
- 0.4311459479219787
- -0.30900221132540373
- -0.7140011055936846
- 0.5253997888019557
- -0.1834460319531841
- -0.2568314148218261
- -0.007347009449880803
- 0.3121330274510598
- -0.20391302431159936
- -0.3925409735380109
- 0.4419414231770621
- -0.09778921938811365
- 0.45332509862005904
- -0.1644953106076641
- 0.3944900335222917
- 0.18473431537906473
- 0.07437807798573413
- 0.01918137406218489
- -0.3563219747475587
- -0.15389019901086656
- -0.4392590395896331
- -0.3360281322525805
- 0.08852582789983718
- -0.050819429061541584
- -0.8382867467394038
- 0.22738829146038106
- 0.8345402196376263
- -0.08719401341828785
- -0.21889201616925272
- 0.07299790233568693
- 0.42015573549113744
- -0.05849725971400115
- -0.6423318777965391
- -0.7221252724060314
- -0.10171749578591609
- -0.27449591686163594
- -0.430772449700986
- 0.01336707718461064
- 0.12147842912458075
- -0.3358987318612516
- 0.2596436292592323
- -0.04914522614920619
- -0.727301657783938
- -1.2637448216412153
- -0.06207003694548727
- -0.48091385240020296
- -0.872471296109858
- 0.06966272562548692
- -0.46857083890830303
- 0.3652935785769695
- 0.0036241736364982457
- 0.11658853511428618
- -0.9592564836115283
- -0.025354559102998386
- -0.04577309667474242
- -0.7039338378361106
- -0.02796705533037783
- 0.4191341894769652
- 0.8544757102603098
- -0.7853493279546506
- -0.3003075062877925
- -0.48594874437293756
- -0.32116962226544454
- -0.7039338378361104
- 0.1273840189273907
- -0.11643870135568704
- 0.12728221351765875
- 0.15870354131843933
- -0.09593025088145266
- -0.9016924586874611
- -0.0036931543103185345
- -0.30478586325717
- -0.23860352744847801
- -0.40777904930799763
- -0.6423318777965398
- 0.35745981619240647
- -0.7039338378361103
- 0.060182158111641314
- -0.27965240054439605
- 0.3956932875936743
- -0.8459310406118703
- 0.15548202677251652
- -0.03646872003740305
- 0.20674773930747914
- -0.28468729251712954
- -0.19207519956206284
- 0.714158341620169
- 0.058115681013271484
- -0.5308149183416003
- -0.24817146392666178
- 0.30241002995488314
- -1.088933190862353
- 0.38699576463759866
- -0.4077790493079974
- -0.47059265898170133
- 0.09052959642315007
- -0.23200420774294145
- -0.6082128660557173
- 0.5470138569320303
- -1.573975012529211
- -0.6713934895652811
- -0.38605095755331337
- -0.44261591390773064
- -0.5966271895303625
- 0.2735488155205583
- -0.9158142713678437
- -0.5860245010038656
- -0.5615037080827919
- -0.4359021652715345
- -0.7503268240367411
- -0.8344498994789815
- -0.3442990216932847
- -0.32900175256744174
- -0.28836606299617695
- -0.5014827995754771
- -0.9160431677115998
- -1.007035822838978
- -0.8100764725111504
- 0.0
- 0.6123876444866236
- -0.1798792261475292
- -0.3512144809264096
- -0.27093016138152043
- -0.84593104061187
- -0.5670785245845991
- 0.0
- -0.10649021213724126
- 0.30672803335165605
- -0.11628742836613896
- 0.4292014572345395
- -0.7140011055936847
- -0.6428670651634747
- -0.2188920161692528
- -0.059929375663103863
- 1.2269205488432227
- 0.8230924041291308
