semver: 1.0.0
version: '2026-01-03'
metadata:
  simulation_manifest: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2026-01-03/seed=9248923/20260103T175111Z/manifest.json
  simulation_config_path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/models/hurdle/hurdle_simulation.priors.yaml
  seed: 9248923
  created_utc: 20260103T175111Z
  inputs:
    priors:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/models/hurdle/hurdle_simulation.priors.yaml
      sha256: 7588df761e0c4ba3f09adced410db1ffb79fd7236b2ad99c6ef0362a230fa119
    transaction_schema_merchant_ids:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/layer1/transaction_schema_merchant_ids/2026-01-03/transaction_schema_merchant_ids.parquet
      sha256: df2f940f061a09a018e133828c9b7b2e7e442a1052b5c0105ef927e2b7c696e8
    world_bank_gdp_per_capita:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/world_bank_gdp_per_capita/2025-04-15/gdp.parquet
      sha256: 1eb6d9ae47639b17fd41e7875c03247c4133a849b442c0e3ebe61a4cb2c06074
    gdp_bucket_map:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/gdp_bucket_map/2024/gdp_bucket_map.parquet
      sha256: 624c9d1029e81980c7d7eb368a7ed07d67c62d8423d0c053cdcd9c58a6c80a3b
    iso3166_canonical:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/iso/iso3166_canonical/2024-12-31/iso3166.parquet
      sha256: bfb68d1770abef6a74571cfea4d659eefb7b6c7b39e81f1b6cc483bd60bd8b5f
    logistic:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2026-01-03/seed=9248923/20260103T175111Z/logistic.parquet
      sha256: e52e774343461db1071bf79d8166bc90e4ee9a78a43c935bb1ae0780afd05b00
    nb_mean:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2026-01-03/seed=9248923/20260103T175111Z/nb_mean.parquet
      sha256: 4e7ca3ee110b8dfb22d66b55dfcfa5264efc0a5d12202591c5301e023a51aea7
dict_mcc:
- 742
- 743
- 744
- 763
- 780
- 1520
- 1711
- 1731
- 1740
- 1750
- 1761
- 1771
- 1799
- 2741
- 2791
- 2842
- 4011
- 4111
- 4112
- 4119
- 4121
- 4131
- 4214
- 4215
- 4225
- 4411
- 4457
- 4468
- 4511
- 4582
- 4722
- 4784
- 4789
- 4812
- 4814
- 4815
- 4816
- 4821
- 4829
- 4899
- 4900
- 5013
- 5021
- 5039
- 5044
- 5045
- 5046
- 5047
- 5051
- 5065
- 5072
- 5074
- 5085
- 5094
- 5099
- 5111
- 5122
- 5131
- 5137
- 5139
- 5169
- 5172
- 5192
- 5193
- 5198
- 5199
- 5200
- 5211
- 5231
- 5251
- 5261
- 5262
- 5271
- 5300
- 5309
- 5310
- 5311
- 5331
- 5399
- 5411
- 5422
- 5441
- 5451
- 5462
- 5499
- 5511
- 5521
- 5531
- 5532
- 5533
- 5541
- 5542
- 5551
- 5552
- 5561
- 5571
- 5592
- 5598
- 5599
- 5611
- 5621
- 5631
- 5641
- 5651
- 5655
- 5661
- 5681
- 5691
- 5697
- 5698
- 5699
- 5712
- 5713
- 5714
- 5715
- 5718
- 5719
- 5722
- 5732
- 5733
- 5734
- 5735
- 5811
- 5812
- 5813
- 5814
- 5815
- 5816
- 5817
- 5818
- 5912
- 5921
- 5931
- 5932
- 5933
- 5935
- 5937
- 5940
- 5941
- 5942
- 5943
- 5944
- 5945
- 5946
- 5947
- 5948
- 5949
- 5950
- 5960
- 5962
- 5963
- 5964
- 5965
- 5966
- 5967
- 5968
- 5969
- 5970
- 5971
- 5972
- 5973
- 5975
- 5976
- 5977
- 5978
- 5983
- 5992
- 5993
- 5994
- 5995
- 5996
- 5997
- 5998
- 5999
- 6010
- 6011
- 6012
- 6051
- 6211
- 6300
- 7011
- 7012
- 7032
- 7033
- 7210
- 7211
- 7216
- 7217
- 7221
- 7230
- 7251
- 7261
- 7273
- 7276
- 7277
- 7278
- 7296
- 7297
- 7298
- 7299
- 7311
- 7321
- 7322
- 7333
- 7338
- 7339
- 7342
- 7349
- 7361
- 7372
- 7375
- 7379
- 7392
- 7393
- 7394
- 7395
- 7399
- 7512
- 7513
- 7519
- 7523
- 7531
- 7534
- 7535
- 7538
- 7542
- 7549
- 7622
- 7623
- 7629
- 7631
- 7641
- 7692
- 7699
- 7800
- 7801
- 7802
- 7829
- 7832
- 7841
- 7911
- 7922
- 7929
- 7932
- 7933
- 7941
- 7991
- 7992
- 7993
- 7994
- 7995
- 7996
- 7997
- 7998
- 7999
- 8011
- 8021
- 8031
- 8041
- 8042
- 8043
- 8049
- 8050
- 8062
- 8071
- 8099
- 8111
- 8211
- 8220
- 8241
- 8244
- 8249
- 8299
- 8351
- 8398
- 8641
- 8651
- 8661
- 8675
- 8699
- 8734
- 8911
- 8931
- 8999
- 9211
- 9222
- 9223
- 9311
- 9399
- 9402
dict_ch:
- CP
- CNP
dict_dev5:
- 1
- 2
- 3
- 4
- 5
design:
  beta_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
  - gdp_bucket_onehot([1,2,3,4,5])
  beta_mu_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
beta:
- -1.1395762619018373
- -0.12355519992395293
- 0.6491379679497475
- 0.2529727775030237
- -0.9053807799197521
- 0.014423710998464628
- -0.3702318930787536
- -0.33798272406458135
- 1.1610070846442218
- 0.7208970768869805
- -0.25345560531329464
- -0.25123849181546987
- 0.2726066590800409
- 1.2152963768700502
- -0.6474758343442504
- 0.565548433318983
- -0.5471936098788812
- 1.1860556663818425
- 0.4244529740204774
- -0.08517964388838668
- 0.5635306350190763
- 0.27736169825485363
- 0.627943764512698
- 0.5148964368343001
- 0.5643290338453254
- 0.1705034667554028
- 0.17676049276390685
- 0.08148455192436094
- 0.534510098607455
- -0.33868676841838374
- 0.5744346291624133
- 0.0709378810256845
- 0.42004227953758577
- 1.2144401361355912
- 0.15561957679748165
- -0.32807931265784435
- -5.556305332257111
- 0.48408096272473317
- 0.053158358187763974
- 1.6773937758385775
- -0.3809119743500184
- 0.4103959843692794
- 0.6561634844315043
- -0.01899151950168879
- -0.03938299136530882
- -0.6096115081711363
- 0.6469796312451648
- -0.008403409481851245
- 0.4508352798838222
- 0.3096969289422762
- 0.42958998294609746
- 0.32187323958378106
- 0.3136845620140716
- 0.30501974624349865
- 0.029754587292650993
- -0.19305090038840828
- 0.44022042006851897
- -0.3511290688263239
- -0.616899534893281
- 0.31052970922422374
- 0.03177549751542108
- 0.2465158212944597
- -0.7571067433758978
- -1.1187817701065939
- -0.35569491279675375
- 0.08108135818967457
- 0.5355901360052674
- 0.07771930498233827
- -0.18455558901143093
- 0.6542089863011594
- 0.7294759746907631
- 0.5114587441242302
- 1.129145221859367
- 0.012004445200800748
- 0.6536315473173535
- 0.6472664966104283
- 0.8167201031618881
- -0.9200961000224505
- 0.3234386004177801
- -0.1407714758328826
- 1.118650529348533
- 0.9178522263028093
- 0.4324916977868366
- 1.026268131833808
- 1.2358220758664928
- 0.8226844851451212
- 1.205228197126019
- 0.537910030489806
- 1.6197447599597357
- 1.7827265356063569
- 0.52727979602855
- 1.7896311722781808
- 1.3116165800611326
- 0.30759396767768676
- 0.7285012896845053
- 0.24986782851404218
- 0.7913863276947197
- 0.4247518534644013
- 0.22000358665491376
- 0.572134893824342
- 1.0945468471325377
- 0.3038863184814762
- 0.9851975338482422
- 0.14853131856908103
- 0.7808474756888278
- -1.1591157441190527
- 0.32158606390650646
- -0.11123114085125216
- 0.5408610628888055
- 0.09910126040310344
- 0.4206389907684716
- 0.5059745896067693
- 0.66355972467946
- 0.23459524178603194
- 0.8345064917189555
- 0.6787038147465325
- 0.5329393986353501
- -0.00016901876176376565
- 0.7120846936865396
- -0.2921694636642049
- 0.7193193693219733
- -0.24945962571933994
- 0.7123498761770943
- 0.2603652367105659
- 0.9286097860882617
- 0.7316780589869276
- 0.44536536414169137
- -0.8368946858984847
- 0.6112666575729918
- 0.49880809492698625
- 0.19252197480758085
- 0.13011793271903327
- 1.0270106992691785
- 0.30419149900727954
- -0.13262183854760645
- -0.2816905960153228
- 0.09160978483191087
- 0.10016973819316388
- -1.6916911208557417
- 0.27471755339625364
- -0.28601995337608527
- -0.1932736735529803
- 0.39745834341752617
- 0.05849018240789916
- -0.17200926247803128
- 0.34185105846244385
- 0.21424273463322854
- -0.19811575551993937
- -0.3492111416222488
- -0.12294813531433404
- 0.05998233231905007
- -0.17338310867943182
- 0.10589704950104696
- 0.63559054573423
- -0.2791978457532176
- 0.5322142084392832
- 0.5830055604401227
- 0.5604014881094035
- 0.7249258346579842
- -1.0401230540046884
- 0.24911202687162518
- 0.4225773207639346
- 0.25204916343199174
- -0.27812631424952966
- 0.2409284594984029
- -0.47241177823345976
- -0.2692367588144125
- 0.18603522312108417
- 0.0067348759500703735
- 0.3582752194801141
- 0.16297976987876336
- 0.4833661356899183
- -0.5441005509571241
- -0.21085265981801307
- -0.10221069566261512
- -0.5628037626774556
- -0.41774885208914647
- 0.19951333491186213
- -0.38914008051359134
- -0.08492581038926812
- -0.45543404859785874
- 0.14080407816449503
- -0.6924834819680055
- -0.8370565946384365
- 0.3723020749859881
- -0.815230049941712
- 0.22934613239564317
- -0.5046848240361851
- 0.16575222124721076
- -1.4250638199596695
- 0.038017874265135865
- -0.18253595356549346
- -0.3715819598822544
- -0.8611853217790802
- -0.006139643333341906
- 0.16830375686740193
- 0.3173746341605253
- 0.3002345517329067
- 0.17623135666560077
- -0.7287956082173863
- -0.9610628779015137
- 0.40605076981653027
- 0.18226222439069437
- -0.3121466589126882
- 0.22762008657128616
- 0.044149816094843135
- -0.03943527552502154
- 0.3863088330089787
- 0.480452955555161
- -0.2049837814597023
- 0.050385871559901374
- -0.86970753459761
- -0.8251194618170815
- 0.9662631116481216
- -0.6631237938563594
- -0.10926841597306858
- -0.5961988754115395
- -0.8079011046540583
- -0.3132044063138858
- 0.511834421544762
- -1.1616780169153382
- 0.3505700329797492
- 0.05964695186496368
- -1.626218180702916
- 0.5302477212829408
- 0.4500502746449453
- -0.17234828361777377
- 0.133881736839792
- 0.4253774524525599
- 0.23354527852141105
- -0.3302777701554893
- -1.3740227763719435
- 0.4610965540307373
- -0.8513626416075153
- -0.47945831812878925
- 0.18404223851638873
- -0.8964049444686198
- -0.27064157337001665
- 0.4179557786050321
- -0.44259527303420265
- 0.43009217402544675
- -0.3137971898815487
- -0.35204769932807856
- -0.6105098962679495
- 0.003493954948993786
- -0.7610815837116025
- 0.18722894893688763
- -0.7706489439135431
- -0.9318324397853136
- 0.17066248487527066
- -0.7111113170053198
- -0.3294506455420305
- -0.8509799257045816
- -0.5791717226599604
- -0.1997006930480287
- -0.30232660716434606
- -0.7696726379425509
- 0.16322162315629277
- -0.45996453998376957
- 0.4082491375430201
- -0.04016180640420546
- -0.3237080982593376
- -0.5319459418262676
- -0.6150641506884175
- 0.48126632741328323
- 0.3259158291079374
- -0.5596192163629057
- 0.31632966227601356
- -0.47700378139621824
- -0.8337738578537423
- -0.38369089735113415
- -0.7091902266158834
- -0.4262592921097843
- -0.7655132657256938
- -0.5773276246783964
- -6.850110469270412
- -0.8514134414452039
- 0.049427516618458206
- -0.03575410450426962
- 0.48972276897077505
- 0.013318418254464292
- -0.09098549330811943
- -6.86544681845988
- -0.37612537944065366
- 0.41839605148232034
- -0.556639500130873
- -1.0632389090792185
- -0.8476479959836294
- 0.3589885724100375
- -0.9218571039778817
- -0.17488049754930932
- -0.28750660784290355
- -0.8520696527283449
- -0.7844325078593459
- -0.4810454702602077
- -0.2560555372181693
- -0.007979490332166226
- 0.38993674638828835
beta_mu:
- 1.7814957339620379
- -0.35445349568643775
- -0.20570477068405274
- 0.011934787416489194
- -0.4820075112462337
- -0.12340364563667985
- 0.3460734461387858
- 0.06703528423745238
- 0.19897275052406324
- -0.032302446871546785
- 0.23372078948526007
- -0.21791232032451835
- 0.015503167485474353
- 0.2591300660244006
- -0.6550590194390832
- -0.2734091187328397
- 0.034658160460828556
- 0.17099729623332927
- 0.009551710030144486
- 0.11498547716130139
- 0.10071764098572066
- 0.5142895490312919
- 0.19571055401210655
- 0.28054656155869545
- 0.05106248710175996
- 0.41846130520376756
- -0.209679712701797
- 0.10216077442240362
- 0.583541792405547
- 0.17043049053764966
- 0.18848384779727514
- -0.1453622271218247
- 0.2361022780796321
- 0.45556031185014617
- -0.08437043702245729
- 0.010095460032728992
- 0.0
- -0.09412651864002027
- -0.15805658225673277
- -0.20037263088588345
- 0.07682779017991659
- -0.05689803989093657
- -0.09391246669223303
- 0.001402254997791391
- -0.3147879140618775
- 0.3372552829766495
- -0.02113594124495892
- 0.145207352272854
- -0.04165629229236789
- 0.01053049086567056
- -0.11935573610362833
- -0.0193272654500835
- 0.11105317975740679
- -0.17102962416215156
- -0.35445349568643725
- -0.2557624970383879
- -0.07884862800336985
- -0.058004881075852374
- -0.2031847145017438
- 0.033953167623210684
- -0.3807870412145115
- 0.06261631509673586
- -0.4820075112462336
- 0.5725717992718032
- 0.13184120441584635
- 0.12849177536460468
- 0.11274871372894475
- 0.0062827299458892
- -0.17810515763132548
- 0.03231775695449576
- 0.0966753373691552
- 0.10397323125362365
- 0.006280923773357104
- 0.019940426984247785
- 0.530142855717816
- 0.2199464100881021
- 0.2550919289148695
- 0.17854013492184198
- 0.23473540891577693
- 0.4386870465695966
- 0.6748861767679604
- 0.3781771896788956
- 0.7532424973487271
- 0.587140404854626
- 0.6379427906646696
- 0.36292210403241637
- 0.4889957227500014
- 0.43654530716276785
- 0.4904608315256942
- 0.4753264387641799
- 0.41859804860455974
- 0.645959328012792
- 0.7869037956086058
- 0.4890024689077342
- 0.40073299118927375
- 0.3134150404374705
- 0.2836614336020029
- 0.4012431589117325
- 0.17982945129702407
- 0.3137385665952836
- 0.08993359472021184
- -0.10286250130760914
- 0.22083948394720418
- 0.23896248762049416
- 0.211754087803293
- 0.06702411727356129
- -0.297774256455916
- 0.13877460220675142
- 0.2428637957107755
- 0.1755660337179175
- -0.08771329376429306
- 0.46193470618644583
- -0.08962741471915803
- 0.16424566425576312
- 0.020917831611085524
- -0.11173099109980227
- 0.14570873192387349
- 0.42124044292606083
- 0.07224268668708186
- 0.35826793855803896
- -0.08498818410462552
- 0.12847155609023306
- 0.3773475413769574
- 0.06755998042502895
- 0.1760444966733148
- 0.19965383537221584
- 0.31222591434583696
- 0.3648752962408167
- -0.04359823034555879
- 0.2104158681417666
- 0.24576501961853778
- 0.05165509008695505
- -0.3138105135272542
- -0.15974413120795
- 0.19629281882016758
- 0.10901455876613032
- -0.2228458077146892
- 0.01053049086567016
- 0.06699063869350462
- -0.24612183917485597
- 0.3048781592000255
- -0.1809285551451347
- 0.08494500694671825
- 0.005973853317106811
- 0.03573921446122581
- -0.3139301244474462
- -0.024841400556249556
- -0.13564101446826715
- -0.1288283161964424
- 0.42072993041107265
- 0.0698060333250014
- -0.12582440850957227
- -0.2216864786367902
- 0.0444751971288152
- 0.6258594186997115
- -0.14163575954256957
- -0.1962712144540553
- 0.22691891995893618
- -0.16263274280284407
- -0.37579005557562345
- 0.2765262046326083
- -0.0965505431332548
- -0.13517442885359268
- -0.0038668470788846333
- 0.1642805407637157
- -0.10732264437452597
- -0.20660051238842678
- 0.232600749040559
- -0.051468010204270345
- 0.23859215716845214
- -0.08657647926719163
- 0.20762633343278514
- 0.09722858704161302
- 0.03914635683459691
- 0.01009546003272889
- -0.18753788144608355
- -0.08099484158466662
- -0.23118896820507007
- -0.17685691171188447
- 0.046592540999914306
- -0.02674706792712715
- -0.44120355091547575
- 0.11967804813704266
- 0.4392316945461191
- -0.04589158600962519
- -0.1152063242996067
- 0.038419948597729965
- 0.22113459762691445
- -0.03078803142842166
- -0.33806940936659957
- -0.38006593284527973
- -0.053535524097850576
- -0.1444715351903347
- -0.22672234194788737
- 0.007035303781374022
- 0.06393601532872671
- -0.176788806242764
- 0.13665454171538544
- -0.025865908499582205
- -0.38279034620207264
- -0.6651288534953765
- -0.03266844049762488
- -0.25311255389484366
- -0.4591954190051884
- 0.0366645924344668
- -0.24661623100437002
- 0.192259778198405
- 0.0019074598086832872
- 0.061362386902255886
- -0.5048718334797517
- -0.013344504791051783
- -0.02409110351302233
- -0.37049149359795297
- -0.014719502805462017
- 0.22059694182998169
- 0.449724058031742
- -0.4133417515550793
- -0.1580565822567329
- -0.2557624970383882
- -0.1690366432976024
- -0.37049149359795286
- 0.06704422048810038
- -0.06128352702930897
- 0.0669906386935046
- 0.08352817964128387
- -0.05048960572708035
- -0.4745749782565585
- -0.0019437654264834394
- -0.1604136122406158
- -0.1255808039202516
- -0.21462055226736718
- -0.3380694093665999
- 0.18813674536442446
- -0.3704914935979528
- 0.03167482005875859
- -0.14718547397073478
- 0.20825962504930226
- -0.44522686347993173
- 0.08183264566974555
- -0.019194063177580552
- 0.10881459963551535
- -0.14983541711427872
- -0.10109221029582255
- 0.37587281137903633
- 0.03058720053330078
- -0.2793762728113686
- -0.13061655996140095
- 0.1591631736604648
- -0.5731227320328174
- 0.20368198138820984
- -0.21462055226736707
- -0.2476803468324744
- 0.04764715601218425
- -0.12210747775944288
- -0.320112034766167
- 0.2879020299642265
- -0.8284079013311637
- -0.3533649945080427
- -0.20318471450174388
- -0.23295574416196352
- -0.3140143102791382
- 0.14397306080029385
- -0.48200751124623353
- -0.30843394789677137
- -0.2955282674119958
- -0.2294221922481761
- -0.39490885475617954
- -0.4391841576205166
- -0.18121001141751827
- -0.17315881714075881
- -0.15177161210325105
- -0.26393831556604064
- -0.48212798300610515
- -0.5300188541257779
- -0.4263560381637634
- 0.0
- 0.3223092865719072
- -0.0946732769197522
- -0.1848497268033735
- -0.1425948217797476
- -0.44522686347993157
- -0.29846238136031533
- 0.0
- -0.056047480072232245
- 0.1614358070271874
- -0.06120390966638893
- 0.2258955038076524
- -0.37579005557562356
- -0.3383510869281446
- -0.11520632429960674
- -0.03154177666479151
- 0.6457476572859067
- 0.4332065284890162
