policy_id: grouping_policy_5B
version: v1.0.3
mode: stratified_bucket_hash_v1
zone_group_buckets: 16
in_stratum_buckets: 32
scenario_band_law: baseline_if_is_baseline_else_stress
virtual_band_law: virtual_if_virtual_mode_not_NON_VIRTUAL_else_physical
stratum_fields:
  - scenario_band
  - demand_class
  - channel_group
  - virtual_band
  - zone_group_id
group_id_format: "g|{scenario_band}|{demand_class}|{channel_group}|{virtual_band}|{zone_group_id}|b{b:02d}"
realism_targets:
  min_groups_per_scenario: 100
  max_groups_per_scenario: 50000
  min_group_members_median: 3
  max_single_group_share: 0.02
