semver: 1.0.0
version: '2025-12-31'
metadata:
  simulation_manifest: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084218Z/manifest.json
  simulation_config_path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/models/hurdle/hurdle_simulation.priors.yaml
  seed: 9248923
  created_utc: 20251231T084218Z
  inputs:
    priors:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/models/hurdle/hurdle_simulation.priors.yaml
      sha256: 279cf29d9a726aa1e77ce13d70d49183d0c6f75aa41da0592274a80e69ec6fee
    transaction_schema_merchant_ids:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/layer1/transaction_schema_merchant_ids/2025-12-31/transaction_schema_merchant_ids.parquet
      sha256: a5ce122a1c61a4247ba4ece8624a201fe824c72c10f352cfba74623e54a0cb12
    world_bank_gdp_per_capita:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/world_bank_gdp_per_capita/2025-04-15/gdp.parquet
      sha256: 1eb6d9ae47639b17fd41e7875c03247c4133a849b442c0e3ebe61a4cb2c06074
    gdp_bucket_map:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/gdp_bucket_map/2024/gdp_bucket_map.parquet
      sha256: 624c9d1029e81980c7d7eb368a7ed07d67c62d8423d0c053cdcd9c58a6c80a3b
    iso3166_canonical:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/iso/iso3166_canonical/2024-12-31/iso3166.parquet
      sha256: bfb68d1770abef6a74571cfea4d659eefb7b6c7b39e81f1b6cc483bd60bd8b5f
    logistic:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084218Z/logistic.parquet
      sha256: da7fdbd584b2d12f7b76d638b9549cbe67bc1e970dbdb92bb81fb70ddcf4b99a
    nb_mean:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084218Z/nb_mean.parquet
      sha256: 7ee7782b97a23c0ef24039563d27203af05f1793d40d0471dd0ed48e4505bbf3
dict_mcc:
- 742
- 743
- 744
- 763
- 780
- 1520
- 1711
- 1731
- 1740
- 1750
- 1761
- 1771
- 1799
- 2741
- 2791
- 2842
- 4011
- 4111
- 4112
- 4119
- 4121
- 4131
- 4214
- 4215
- 4225
- 4411
- 4457
- 4468
- 4511
- 4582
- 4722
- 4784
- 4789
- 4812
- 4814
- 4815
- 4816
- 4821
- 4829
- 4899
- 4900
- 5013
- 5021
- 5039
- 5044
- 5045
- 5046
- 5047
- 5051
- 5065
- 5072
- 5074
- 5085
- 5094
- 5099
- 5111
- 5122
- 5131
- 5137
- 5139
- 5169
- 5172
- 5192
- 5193
- 5198
- 5199
- 5200
- 5211
- 5231
- 5251
- 5261
- 5262
- 5271
- 5300
- 5309
- 5310
- 5311
- 5331
- 5399
- 5411
- 5422
- 5441
- 5451
- 5462
- 5499
- 5511
- 5521
- 5531
- 5532
- 5533
- 5541
- 5542
- 5551
- 5552
- 5561
- 5571
- 5592
- 5598
- 5599
- 5611
- 5621
- 5631
- 5641
- 5651
- 5655
- 5661
- 5681
- 5691
- 5697
- 5698
- 5699
- 5712
- 5713
- 5714
- 5715
- 5718
- 5719
- 5722
- 5732
- 5733
- 5734
- 5735
- 5811
- 5812
- 5813
- 5814
- 5815
- 5816
- 5817
- 5818
- 5912
- 5921
- 5931
- 5932
- 5933
- 5935
- 5937
- 5940
- 5941
- 5942
- 5943
- 5944
- 5945
- 5946
- 5947
- 5948
- 5949
- 5950
- 5960
- 5962
- 5963
- 5964
- 5965
- 5966
- 5967
- 5968
- 5969
- 5970
- 5971
- 5972
- 5973
- 5975
- 5976
- 5977
- 5978
- 5983
- 5992
- 5993
- 5994
- 5995
- 5996
- 5997
- 5998
- 5999
- 6010
- 6011
- 6012
- 6051
- 6211
- 6300
- 7011
- 7012
- 7032
- 7033
- 7210
- 7211
- 7216
- 7217
- 7221
- 7230
- 7251
- 7261
- 7273
- 7276
- 7277
- 7278
- 7296
- 7297
- 7298
- 7299
- 7311
- 7321
- 7322
- 7333
- 7338
- 7339
- 7342
- 7349
- 7361
- 7372
- 7375
- 7379
- 7392
- 7393
- 7394
- 7395
- 7399
- 7512
- 7513
- 7519
- 7523
- 7531
- 7534
- 7535
- 7538
- 7542
- 7549
- 7622
- 7623
- 7629
- 7631
- 7641
- 7692
- 7699
- 7800
- 7801
- 7802
- 7829
- 7832
- 7841
- 7911
- 7922
- 7929
- 7932
- 7933
- 7941
- 7991
- 7992
- 7993
- 7994
- 7995
- 7996
- 7997
- 7998
- 7999
- 8011
- 8021
- 8031
- 8041
- 8042
- 8043
- 8049
- 8050
- 8062
- 8071
- 8099
- 8111
- 8211
- 8220
- 8241
- 8244
- 8249
- 8299
- 8351
- 8398
- 8641
- 8651
- 8661
- 8675
- 8699
- 8734
- 8911
- 8931
- 8999
- 9211
- 9222
- 9223
- 9311
- 9399
- 9402
dict_ch:
- CP
- CNP
design:
  beta_phi_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
  - ln_gdp_pc_usd_2015
beta_phi:
- 1.158639107776702
- -0.03423983290832783
- -0.03298958685855468
- -0.03500146862368474
- -0.03458750484437299
- -0.03612030790003332
- -0.03590432358320072
- -0.0354823753966324
- -0.03656599362699295
- -0.032878989842948354
- -0.034759650879807286
- -0.03535312873738514
- -0.03495176691196747
- -0.036937998234348075
- -0.03434007919731246
- -0.0340442916508453
- -0.036432359042452775
- -0.03595633068642559
- -0.03540761261631028
- -0.033657751998988815
- -0.03373632908654507
- -0.03465095725533414
- -0.03596694769231886
- -0.03376423122526101
- -0.03356667555517128
- -0.0340693942801302
- -0.034505543858132905
- -0.03502579886469318
- -0.035076226838122934
- -0.03475804515998383
- -0.03575065276946637
- -0.03528887243374122
- -0.034848172830174794
- -0.03273466032769329
- -0.03485671450015923
- -0.03620351694362456
- -0.034478381048847276
- -0.035031895456795865
- -0.035494339735409365
- -0.03511578096169951
- -0.0324154723220941
- -0.035710027301411554
- -0.03368880285055845
- -0.0363576303014128
- -0.03590997317360687
- -0.0336749508039881
- -0.034815725621816646
- -0.03331951216892043
- -0.03433641019751896
- -0.034331734440727686
- -0.03630776515646295
- -0.03582485422088898
- -0.036102976189253226
- -0.03487192045179659
- -0.03486694981658497
- -0.03422128130332937
- -0.036002176324218205
- -0.03523216495763672
- -0.03656265847512005
- -0.0352743102398568
- -0.03564194443523712
- -0.03405632949690132
- -0.03589700718598975
- -0.03569753422835991
- -0.03568741517966847
- -0.03372127069265678
- -0.033815160380007106
- -0.034642602785331704
- -0.03707603565511257
- -0.035937458599265025
- -0.034147076710802665
- -0.035310905241998466
- -0.03485811001540318
- -0.03534732492583033
- -0.03602058758711786
- -0.03472573598307888
- -0.033800784684119206
- -0.035353531797481526
- -0.03523895824460948
- -0.03400138844066772
- 0.8213613604030897
- 0.3901282889503308
- 0.39902396421680814
- 0.4097049056368149
- 0.5686169414724468
- 0.8606227569972495
- -0.0017322394399763694
- 1.3076719423485161
- 0.549490865215442
- 0.1409248311191805
- 0.043883020114745895
- 0.12466492411211885
- 0.4150519622291667
- 0.12694162966082415
- 0.06598730972721503
- -0.03460991979908869
- 0.2396778666134372
- 0.17306320986693138
- -0.03445667816520943
- 0.20140082253588307
- -0.033951726684873736
- -0.0351706890371988
- -0.03530341682065389
- -0.03549007909164139
- -0.03302526967230683
- -0.034408265434542194
- -0.0359464291056817
- -0.0350301621032296
- -0.03413937370244886
- -0.034375223072886124
- -0.03665132265361283
- -0.032480896479512966
- -0.03512297642429647
- -0.03516008383003728
- -0.035627785252627664
- -0.03740569227108447
- -0.03305401998237051
- -0.034564956546081306
- -0.03540840669965805
- -0.033759806218861356
- -0.035626254648243406
- -0.03437888650205596
- -0.03516815243316954
- 0.5903822675071718
- 0.9612881394614534
- 0.32559806111269646
- 0.4889728091020667
- 0.39643982856927157
- -0.034535926075447226
- 0.6853317217550545
- 0.0998489029140556
- -0.03402062676959122
- -0.03417516917428535
- -0.03551323156058885
- -0.035013317047304905
- -0.033969981204194394
- -0.03483755532216462
- -0.0342492192473706
- -0.03401464800969783
- -0.036420254382053534
- -0.03564971872541873
- -0.03345512048677312
- -0.035432634642563854
- -0.036282433822545236
- -0.036064717975410686
- -0.033393754677244154
- -0.03579433896905453
- -0.03630659611203364
- -0.03329146213344957
- -0.034866616693798674
- -0.03472481558432716
- -0.035592640545163215
- -0.03633945216128162
- -0.035597503170752894
- -0.03491246308165426
- -0.03567826178755947
- -0.03494591961826913
- -0.03528487977310585
- -0.035021293708039886
- -0.034058807822259965
- -0.03285123205475908
- -0.03529561382560419
- -0.034639872425029104
- -0.034091578540774395
- -0.03635569831307532
- -0.03648410011006464
- -0.03552197232566247
- -0.0348248268734391
- -0.03504407776877819
- -0.03490616672040104
- -0.03448273345473692
- -0.03474687389163031
- -0.03508519941646611
- -0.034808286659817306
- -0.03569209986271202
- -0.033533803892369256
- -0.032171516267353754
- -0.03534849565025285
- -0.03386912619172708
- -0.03617496227496536
- -0.03588130851832324
- -0.034546599855716044
- -0.03458308173066548
- -0.033781824731839646
- -0.03471735076268226
- -0.03583155645082317
- -0.03628349168115144
- -0.03403335945023531
- -0.03617588412031109
- -0.03235587557924175
- -0.03339985076309134
- -0.036013674748523225
- -0.03588932424845952
- -0.035587440378806234
- -0.03215955291752887
- -0.03549180257419654
- -0.035069368925188346
- -0.03572221195153586
- -0.03619363892123091
- -0.03591673151040164
- -0.03416339809260662
- -0.03457290036159523
- -0.03414201171468534
- -0.03554354016304495
- -0.03292978059090374
- -0.03719743962287066
- -0.03664004426197678
- -0.035526753258860226
- -0.03423506674919728
- -0.034233191898068775
- -0.03593554219823707
- -0.034572713493282496
- -0.033122920265899095
- -0.03353650392593678
- -0.03612077975822597
- -0.03581257345211959
- -0.03530894999182542
- -0.033411969574786086
- -0.03544560270971573
- -0.036857380143909955
- -0.034220821029981065
- -0.035798873354031466
- -0.03485004630609623
- -0.032309596983807455
- -0.03614479463266133
- -0.03716646429790302
- -0.03478078736501378
- -0.0357697933567007
- -0.03494694552055799
- -0.03600776055545958
- -0.03459286487032881
- -0.03533418308419527
- -0.03492941557968181
- -0.03407052974768021
- -0.031101391306395648
- -0.03319969677117544
- -0.03519813998055352
- -0.03642188549428597
- -0.0346639519913142
- -0.032822840058071616
- -0.03669228480090847
- -0.034825596468960836
- -0.03629412264771017
- -0.035047244513600334
- -0.035727759167511766
- -0.034962697407231
- -0.03592039528571484
- -0.03569161413988352
- -0.03523995691968719
- -0.033936934498932925
- -0.034741653160505266
- -0.03455230111413806
- -0.032828051446701416
- -0.03509924600391389
- -0.036725548182282824
- -0.032945486401603934
- -0.0338645609827278
- -0.03697352078023119
- -0.03710938586382851
- -0.0343102950365329
- -0.034639674510484546
- -0.036639287788662774
- -0.03513496906856418
- -0.03547914924038602
- -0.036310256932801946
- -0.03546742322706095
- -0.03489100293355806
- -0.034891067037533585
- -0.03501034765381347
- -0.036082012325007774
- -0.03316254649134231
- -0.03303679210785431
- -0.03483666685160448
- -0.03673158120786638
- -0.03236884381784911
- -0.034538035902713045
- -0.036196918529269484
- -0.03495531946698889
- -0.033241477120035036
- -0.03641009106834313
- -0.03318837704367348
- -0.03722324548254062
- -0.03549778337804493
- -0.03422410610435358
- -0.035226946618283524
- -0.03825170076797616
- -0.03076638499775078
- 0.0
- -0.03734073970587887
- -0.033592769213856316
- -0.036581949904071126
- 0.0
- 1.1586378081749173
- 0.0020249394882704526
