semver: 1.0.0
version: '2025-12-31'
metadata:
  simulation_manifest: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084444Z/manifest.json
  simulation_config_path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/models/hurdle/hurdle_simulation.priors.yaml
  seed: 9248923
  created_utc: 20251231T084444Z
  inputs:
    priors:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/models/hurdle/hurdle_simulation.priors.yaml
      sha256: 0cbc883238558d808fa12862e5154d6e69ae4f6bd62fe2b74e3b93d235c032df
    transaction_schema_merchant_ids:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/layer1/transaction_schema_merchant_ids/2025-12-31/transaction_schema_merchant_ids.parquet
      sha256: a5ce122a1c61a4247ba4ece8624a201fe824c72c10f352cfba74623e54a0cb12
    world_bank_gdp_per_capita:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/world_bank_gdp_per_capita/2025-04-15/gdp.parquet
      sha256: 1eb6d9ae47639b17fd41e7875c03247c4133a849b442c0e3ebe61a4cb2c06074
    gdp_bucket_map:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/gdp_bucket_map/2024/gdp_bucket_map.parquet
      sha256: 624c9d1029e81980c7d7eb368a7ed07d67c62d8423d0c053cdcd9c58a6c80a3b
    iso3166_canonical:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/iso/iso3166_canonical/2024-12-31/iso3166.parquet
      sha256: bfb68d1770abef6a74571cfea4d659eefb7b6c7b39e81f1b6cc483bd60bd8b5f
    logistic:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084444Z/logistic.parquet
      sha256: 41de8046f724fe7e781d44af238d61393e9ed494381793e9f45c7f452ed254ef
    nb_mean:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T084444Z/nb_mean.parquet
      sha256: 6c182aa4de8ded51f4f68b8f48709ecf05562ecda6ecb5b8b7dc3cbf16c4a579
dict_mcc:
- 742
- 743
- 744
- 763
- 780
- 1520
- 1711
- 1731
- 1740
- 1750
- 1761
- 1771
- 1799
- 2741
- 2791
- 2842
- 4011
- 4111
- 4112
- 4119
- 4121
- 4131
- 4214
- 4215
- 4225
- 4411
- 4457
- 4468
- 4511
- 4582
- 4722
- 4784
- 4789
- 4812
- 4814
- 4815
- 4816
- 4821
- 4829
- 4899
- 4900
- 5013
- 5021
- 5039
- 5044
- 5045
- 5046
- 5047
- 5051
- 5065
- 5072
- 5074
- 5085
- 5094
- 5099
- 5111
- 5122
- 5131
- 5137
- 5139
- 5169
- 5172
- 5192
- 5193
- 5198
- 5199
- 5200
- 5211
- 5231
- 5251
- 5261
- 5262
- 5271
- 5300
- 5309
- 5310
- 5311
- 5331
- 5399
- 5411
- 5422
- 5441
- 5451
- 5462
- 5499
- 5511
- 5521
- 5531
- 5532
- 5533
- 5541
- 5542
- 5551
- 5552
- 5561
- 5571
- 5592
- 5598
- 5599
- 5611
- 5621
- 5631
- 5641
- 5651
- 5655
- 5661
- 5681
- 5691
- 5697
- 5698
- 5699
- 5712
- 5713
- 5714
- 5715
- 5718
- 5719
- 5722
- 5732
- 5733
- 5734
- 5735
- 5811
- 5812
- 5813
- 5814
- 5815
- 5816
- 5817
- 5818
- 5912
- 5921
- 5931
- 5932
- 5933
- 5935
- 5937
- 5940
- 5941
- 5942
- 5943
- 5944
- 5945
- 5946
- 5947
- 5948
- 5949
- 5950
- 5960
- 5962
- 5963
- 5964
- 5965
- 5966
- 5967
- 5968
- 5969
- 5970
- 5971
- 5972
- 5973
- 5975
- 5976
- 5977
- 5978
- 5983
- 5992
- 5993
- 5994
- 5995
- 5996
- 5997
- 5998
- 5999
- 6010
- 6011
- 6012
- 6051
- 6211
- 6300
- 7011
- 7012
- 7032
- 7033
- 7210
- 7211
- 7216
- 7217
- 7221
- 7230
- 7251
- 7261
- 7273
- 7276
- 7277
- 7278
- 7296
- 7297
- 7298
- 7299
- 7311
- 7321
- 7322
- 7333
- 7338
- 7339
- 7342
- 7349
- 7361
- 7372
- 7375
- 7379
- 7392
- 7393
- 7394
- 7395
- 7399
- 7512
- 7513
- 7519
- 7523
- 7531
- 7534
- 7535
- 7538
- 7542
- 7549
- 7622
- 7623
- 7629
- 7631
- 7641
- 7692
- 7699
- 7800
- 7801
- 7802
- 7829
- 7832
- 7841
- 7911
- 7922
- 7929
- 7932
- 7933
- 7941
- 7991
- 7992
- 7993
- 7994
- 7995
- 7996
- 7997
- 7998
- 7999
- 8011
- 8021
- 8031
- 8041
- 8042
- 8043
- 8049
- 8050
- 8062
- 8071
- 8099
- 8111
- 8211
- 8220
- 8241
- 8244
- 8249
- 8299
- 8351
- 8398
- 8641
- 8651
- 8661
- 8675
- 8699
- 8734
- 8911
- 8931
- 8999
- 9211
- 9222
- 9223
- 9311
- 9399
- 9402
dict_ch:
- CP
- CNP
dict_dev5:
- 1
- 2
- 3
- 4
- 5
design:
  beta_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
  - gdp_bucket_onehot([1,2,3,4,5])
  beta_mu_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
beta:
- -0.7527573388556168
- -0.018374795706732363
- -0.3104000876735988
- -0.46149456815201395
- -0.1654369199252734
- -0.04293472615357192
- -0.22870696552247982
- -0.19621120800612366
- -0.06451150150901153
- -0.0909277614937458
- 0.21389869797562835
- 0.036601523759086846
- -0.572454380215097
- 0.2681258915917215
- -0.5324683084214464
- 0.0752559430046702
- -0.057826591362048305
- -0.8703044852003204
- 0.2085759550682284
- 0.5679319980204435
- 0.205235289692529
- 0.19161298570174495
- -0.005461058406015246
- 0.30886927348217447
- -0.007335590975696322
- 0.3379370310236438
- 0.3860485227965119
- 0.22514356390118126
- -0.023819287816940166
- -0.19846942980101717
- 0.34727582333346485
- -0.13323675372077856
- -0.6525876577736152
- -0.14936734390001954
- -0.3977554353659377
- 0.15801459820417554
- 0.07686686094882138
- 0.05823451306040118
- 0.3783892534090506
- -0.055882155895106145
- -0.25644809575740884
- -0.045912661657816364
- -0.3127746516867603
- 0.04953129414547174
- 0.4295637410117708
- 0.4395395919392724
- 0.24732982533406747
- 0.14294310594399243
- 0.17155867884088866
- 0.1421577129225126
- -0.2433736829477251
- -0.03831459600988778
- 0.06991443912586054
- 0.17816822574712168
- 0.40021361215629303
- 0.35587096680965863
- 0.4102143163442353
- 0.1915644089420611
- 0.3358527209960026
- -0.0030596149656069854
- -0.0150364462755174
- 0.007255750010010273
- 0.29276802159886517
- -0.08907109246971857
- 0.12024941404862625
- 0.14176576671943641
- 0.22019682538685814
- 0.4510221820138847
- -0.1694709549062231
- -0.1162694798332142
- -0.20331247151846082
- 0.14222671981208218
- 0.5478651723468662
- -0.08856529931045865
- 0.7113365169187946
- 0.6846048512252738
- 0.9791754000646239
- 0.8688116802231928
- 0.7376018043213548
- 0.8592804958122291
- 1.2533339681908886
- 0.8244332028398997
- 0.7289427175083512
- 0.924118499748363
- 1.0615884016215291
- 0.7890417390458758
- 0.7796477322103179
- 0.9118852956508909
- 1.0017288045346853
- 0.732763313705047
- 0.9556956615760769
- 0.9637879660089248
- 0.8146402910859408
- 0.7062743664464165
- 0.7736225086045695
- 0.7773473092131259
- 0.9421257159221882
- 0.8977142170980104
- 0.8092247505204675
- 0.48689811185299997
- 0.5498078492798011
- 0.31292645419222187
- 0.030588639344547138
- 0.12957592822773253
- 0.39107964111887206
- 0.20472484508454555
- 0.016096386305706232
- 0.31933045003211424
- 0.04663425468793414
- -0.19333411949755153
- 0.3093494139419449
- 0.11799410696157477
- 0.17750409744710227
- 0.25795374892013934
- -0.20831749437219935
- 0.5308440383071668
- 0.20374654346441676
- 0.07739499948283608
- -0.0613644777410816
- 0.35646511465060465
- 0.36615301645638804
- 0.27581887385231846
- 0.1594658858233431
- 0.3989211315472366
- 0.21730422715268366
- 0.227216027313778
- 0.3590493347558493
- -0.12394424042343273
- 0.0747582887040578
- 0.2149569272316036
- 0.15605328885394554
- 0.20994301267630316
- -0.19861409870224594
- 0.13541909684560927
- 0.2983753365712571
- 0.33064137179806957
- -0.4755689989965442
- 0.06708392767383231
- 0.3071212806347462
- 0.10480674307360208
- 0.2340256012636078
- -0.29043095774872135
- -0.1542351987856305
- -0.05640466475418737
- -0.18705130791571217
- 0.030226141769131982
- 0.1350046178315571
- -0.1838914221882419
- 0.14801806849225263
- 0.19663815147012106
- 0.04986525754821514
- -0.258047646101303
- 0.22273453384963576
- 0.227976806878423
- 0.000494835197706857
- 0.03799022042570297
- 0.03781268491592179
- 0.000638182471754474
- 0.19074918935791893
- 0.13428776132983067
- 0.20231773460838526
- 0.2714873872768408
- 0.2946455150481572
- 0.17976858927348421
- 0.18669957042936644
- -0.195850033242088
- 0.01850906033930014
- 0.07570981501959714
- 0.40414622450660465
- 0.313839367646124
- -0.022455028028532144
- -0.005099323671360177
- 0.1668308665779703
- 0.18195167055284425
- -0.258691293316546
- -0.14644537381742764
- -0.19481886589176475
- -0.3360673681707545
- -0.3505866718110241
- 0.29194421186207653
- 0.11356735268838015
- -0.07614014793606656
- -0.015635501120653754
- -0.15601675927470326
- 0.042850404985340776
- 0.023809318614187357
- -0.46470256518396763
- 0.027383937329921414
- -0.30149251495865903
- -0.3430849885267316
- -0.25773123669200326
- 0.25231078484491537
- 0.08033151813090632
- -0.3250005362936594
- -0.6669946953383453
- -0.5964734392188753
- 0.16345924095991327
- -0.1617758425429807
- 0.015821750685044662
- -0.0394888380362843
- -0.08342869046535954
- -0.2842433283908624
- -0.027014085426115404
- -0.45903205479051634
- -0.7967502810852674
- -0.353963011364646
- -0.7759168418251663
- -0.33524260206746437
- 0.08235852166072209
- -0.13952254732293531
- 0.31205831255416333
- -0.23698159273053473
- -0.22378743811537283
- -0.21576097525979915
- -0.08097494060694792
- -0.09279024358317924
- 0.23272179487915362
- -0.5119266482940439
- 0.23223811863990193
- 0.06417168262027577
- 0.05291340984882084
- -0.8205140910394008
- -0.659074580730324
- -0.23287938326583538
- 0.23985695622814526
- -0.15948316369537782
- -0.17730442726801746
- 0.6525681311893894
- -0.6679138009017087
- 0.11381784869237302
- -1.268693169350952
- -0.34225819586202416
- 0.16107179922977619
- -1.0218976869724419
- 0.1736511081362849
- 0.08245441228795856
- 0.09673533303148084
- 0.1160603147521452
- -0.7355098318373493
- -0.5956035034175454
- -0.44104912220075243
- -1.0021812266916894
- 0.4667536597692114
- -0.11407729100961736
- 0.25452710658605815
- -0.3480274158409198
- -0.2374319369451812
- -0.3411287585976882
- -0.6131242623118516
- 0.35419231883694274
- -0.2668151716824051
- -0.5129247803242275
- -0.22903290444475918
- -0.8597007907989771
- 0.3060232741499279
- -0.4739747378601118
- 0.13267952844471675
- -0.8634563937281464
- -0.8719547800623709
- -0.21730092796605135
- -0.46016416456783604
- -0.2665762735511378
- -0.32395787342601234
- -0.5255722003341332
- -0.04972238104855356
- -0.8405784909726464
- -0.2811630271713113
- -0.6235710236687859
- -0.9275912712804085
- -0.6313905416379305
- -0.04517346333912014
- -0.5280865200851484
- -0.46306862242799307
- -0.4006268523224588
- -0.018293016905730566
- -0.37545214579655345
- -0.13385474319779114
- -0.4128251204249033
- -1.113060184593114
- -0.314745483295641
- -0.027020537722763253
- -0.5928720983172411
- -0.3837513161666123
- -0.027580149137106002
- -0.4073255630741777
- -0.2421162585683191
- -1.2638222034905098
- -2.0516764594398302
- -1.4553328545336566
- -0.3777018252754587
- -0.8973251902347954
- 0.0
- -0.7527573373790634
- -0.6095038035448398
- -0.3966016190501488
- -0.18192330813380464
- 0.08836259019718813
- 0.3469087666712505
beta_mu:
- 1.0427599509663739
- 0.022371763692446197
- 0.015808529749614726
- 0.12323176594791925
- 0.034236693420397625
- -0.006048600448986366
- 0.25995420361937793
- -0.006854658866910978
- 0.01289053999178974
- -0.15444457315520835
- -0.04328971239892217
- -0.11356273693752038
- -0.011814676168630736
- -0.15035409705067732
- -0.05105969313765404
- -0.3348171183965449
- -0.24470435196419316
- 0.20226888409679913
- 0.23194809362566968
- -0.04922612840186503
- 0.21503523414119846
- -0.015352780735906377
- 0.3251217509957964
- 0.32141013975043836
- 0.25533478290331696
- 0.15459190025578265
- 0.31329198915195455
- 0.07863275557256459
- 0.04629409356355286
- 0.2765852812194091
- 0.2435011721822046
- 0.05262572049705758
- 0.26887870164146904
- 0.11162608845734359
- 0.11006149329732207
- 0.06068300710596158
- -0.04374270950579217
- -0.03521918313549095
- -0.19325228762223007
- -0.10744264512547719
- 0.012081919706107586
- 0.01897435584038993
- 0.10685976489560592
- 0.09813925867699151
- 0.040573941271507354
- -0.10374978259624644
- 0.11545856082274449
- -0.03548268144763212
- -0.04245904632667522
- 0.06028625207196942
- 0.09616228764382193
- -0.09627030324636973
- -0.0549452914208854
- -0.04126478115879392
- -0.051602503789186314
- -0.17718426223070272
- 0.016019228134190513
- 0.1803754629052075
- -0.046913305247293875
- -0.023971617622088222
- 0.16407714087157374
- 0.15483532259221827
- -0.0845927830075874
- 0.047873385656050434
- -0.1823386926892783
- -0.1369390496281346
- -0.039665931739639865
- -0.04425923413913448
- 0.0999406269198684
- -0.046290278418130194
- -0.11140535035856346
- 0.07618342856403428
- 0.14257853665832965
- 0.11161269767786358
- 0.2544690455589999
- 0.3849579751857827
- 0.4265539126807892
- 0.2245290867632164
- 0.14628353499550972
- 0.30617695882314727
- 0.6825918406870104
- 0.2820246263801373
- 0.3080929599329631
- 0.5683275016115766
- 0.44478583279198436
- 0.3506531295225348
- 0.26245629322983266
- 0.3680986410312581
- 0.4707850170981906
- 0.34498773182107134
- 0.40669066433350815
- 0.3587638947828246
- 0.29697342336714194
- 0.35117436824920156
- 0.38928267881764783
- 0.2666089103139761
- 0.3280487240299051
- 0.3319667712274581
- 0.31313936794434244
- 0.3618698223494283
- 0.021328646152112073
- 0.0711664499164889
- -0.04327843519566299
- 0.005311760840802234
- 0.07105968464257956
- -0.06712551005008631
- 0.19186118230865143
- -0.008078508929231336
- 0.16192798766218605
- -0.010771750577393
- -0.04178144735658972
- 0.05078287189548639
- 0.07683001148021679
- 0.01988729970729164
- -0.061829047892988556
- -0.0338719871387052
- 0.10373942446428859
- -0.062188800924252816
- -0.06449628266969248
- 0.07972944733852781
- 0.14719173483381948
- 0.065867024787812
- -0.06400041683996506
- 0.16320691803528528
- 0.03078194012552161
- 0.03850925090155384
- 0.1345099970941078
- -0.11986359494743964
- 0.08678180210772425
- 0.018862514288732434
- -0.034127718708251036
- 0.009737271081496643
- 0.16824521157505298
- 0.047967594083113796
- 0.13194010788226215
- 0.007888230951861414
- -0.21972529671691202
- 0.1467230746120538
- -0.009858825189384314
- 0.05647371145684472
- 0.03223741841817946
- 0.06642448593947878
- -0.0792408184389766
- 0.0014609982271608615
- -0.050271564040970836
- -0.1932146599251587
- -0.05416325575860421
- -0.15013218264764286
- -0.09307014469575045
- -0.05360189448668364
- -0.06633402904289971
- 0.029274862456771827
- 0.11946184499075455
- -0.08893057750765244
- 0.024844704997048626
- 0.17557227821223892
- -0.006455803435655773
- 0.016587127883872968
- 0.15436642302736597
- 0.11398334540943517
- -0.02337172109674316
- 0.05650259964413313
- 0.013152398138718211
- 0.09249652679770172
- -0.04569184751689128
- 0.11023625502638691
- 0.0983882207699846
- 0.012696067736269055
- -0.13532520189227404
- 0.0019110682732120896
- 0.03566299469873514
- 0.1264498627271868
- 0.09883588565502978
- -0.03503965492392186
- 0.0696967659363493
- -0.0057729724999212376
- -0.3109573986344462
- -0.16388329139062296
- 0.14313941433621746
- -0.04560447162091758
- 0.0905463187023997
- 0.07749042139187985
- -0.09324573490640622
- -0.2392039179750228
- -0.05052265139941708
- 0.04234692728591405
- -0.025819450412745866
- -0.14758367764247043
- -0.1415545169233799
- 0.15534903067048922
- -0.29233988188607646
- -0.1869139073020318
- -0.016120643691351494
- -0.17350490360490692
- -0.04234475767406043
- 0.2887853308954413
- 0.11868135300331606
- 0.12765267079896392
- -0.21289595271031056
- -0.11856933395345154
- -0.19898604056486632
- -0.01209016081231644
- 0.1593493186246489
- -0.0462178198323257
- -0.017987046578474577
- 0.0329344801803735
- 0.03431674039646001
- -0.07667255457789478
- -0.14648299543589277
- -0.16612778725969501
- -0.040877617748532234
- -0.02083208230765132
- -0.09858091777634437
- -0.0683694173337666
- -0.19033663913138946
- -0.06373863591542721
- -0.06864434879455728
- -0.1742047504256311
- 0.0038365736713705007
- 0.02174432068439456
- -0.04664630645858767
- -0.0963079313053093
- 0.252277981322318
- -0.14895524335602303
- -0.0033321793181910714
- 0.12661754705939587
- -0.255713248666853
- -0.10898989292897938
- -0.18683853166041647
- -0.24609464263574748
- 0.19371840757623363
- -0.04949384386466337
- 0.07227347738534282
- 0.09688096628518456
- -0.1206586296414871
- 0.05696749124674718
- -0.03291434181561535
- 0.04606616366973735
- -0.21871162854860537
- 0.0077354836066221904
- -0.021731898411845457
- 0.03614401629277325
- -0.10185127915878028
- 0.07756614395762443
- -0.23893781581094933
- -0.1873681666077362
- -0.34268985870915386
- -0.003682640336721383
- -0.3280751296694014
- 0.20848407516539896
- -0.10169000328373315
- -0.5157322744106014
- -0.03920901704879292
- 0.0028360379232838444
- -0.05197487806626604
- 0.030470763810188876
- -0.20569138634965933
- -0.28618199949200557
- -0.37651208942842207
- -0.3639946700817652
- -0.5363315990778487
- 0.14835049334221873
- -0.3375732954722361
- -0.36577910707755235
- -0.19167896204030066
- -0.24293734102090342
- -0.09137142464345434
- -0.19896039519029723
- -0.18612571179734202
- -0.1463152926935715
- -0.2509758610530896
- -0.34268985870915414
- -0.19188998505551472
- -0.07691969409591841
- -0.13773481086942685
- -0.5134828304785721
- -0.1206586296414871
- -0.16563291442896727
- -0.28813404019998096
- -0.1829113683384474
- -0.10546643259174494
- -0.20406250674138532
- -0.26568206173549047
- -0.29090060093629255
- -0.222075245192136
- -0.16658964901676887
- -0.31438900812042747
- -0.15014402511335634
- 0.08466531282798435
- -0.10906473950831454
- -0.39481895451369853
- 0.0
- 0.8798660092313655
