version: "0.1.0"
default_action: quarantine
policies:
  - event_type: arrival_events_5B
    class: traffic
    schema_version_required: false
    payload_schema_ref: docs/model_spec/data-engine/layer-2/specs/contracts/5B/schemas.5B.yaml#/egress/s4_arrival_events_5B
  - event_type: s2_flow_anchor_baseline_6B
    class: traffic
    schema_version_required: false
    payload_schema_ref: docs/model_spec/data-engine/layer-3/specs/contracts/6B/schemas.6B.yaml#/egress/s2_flow_anchor_baseline_6B
  - event_type: s3_flow_anchor_with_fraud_6B
    class: traffic
    schema_version_required: false
    payload_schema_ref: docs/model_spec/data-engine/layer-3/specs/contracts/6B/schemas.6B.yaml#/egress/s3_flow_anchor_with_fraud_6B
