semver: 1.0.0
version: '2026-02-12'
metadata:
  simulation_manifest: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2026-01-03/seed=9248923/20260103T184840Z/manifest.json
  simulation_config_path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/layer1/1A/models/hurdle/hurdle_simulation.priors.yaml
  seed: 9248923
  created_utc: 20260212T200704Z
  inputs:
    priors:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/layer1/1A/models/hurdle/hurdle_simulation.priors.yaml
      sha256: 7588df761e0c4ba3f09adced410db1ffb79fd7236b2ad99c6ef0362a230fa119
    transaction_schema_merchant_ids:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/layer1/transaction_schema_merchant_ids/2026-01-03/transaction_schema_merchant_ids.parquet
      sha256: df2f940f061a09a018e133828c9b7b2e7e442a1052b5c0105ef927e2b7c696e8
    world_bank_gdp_per_capita:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/world_bank_gdp_per_capita/2025-04-15/gdp.parquet
      sha256: 1eb6d9ae47639b17fd41e7875c03247c4133a849b442c0e3ebe61a4cb2c06074
    gdp_bucket_map:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/gdp_bucket_map/2024/gdp_bucket_map.parquet
      sha256: 624c9d1029e81980c7d7eb368a7ed07d67c62d8423d0c053cdcd9c58a6c80a3b
    iso3166_canonical:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/iso/iso3166_canonical/2024-12-31/iso3166.parquet
      sha256: bfb68d1770abef6a74571cfea4d659eefb7b6c7b39e81f1b6cc483bd60bd8b5f
    logistic:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2026-01-03/seed=9248923/20260103T184840Z/logistic.parquet
      sha256: e52e774343461db1071bf79d8166bc90e4ee9a78a43c935bb1ae0780afd05b00
    nb_mean:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2026-01-03/seed=9248923/20260103T184840Z/nb_mean.parquet
      sha256: 4e7ca3ee110b8dfb22d66b55dfcfa5264efc0a5d12202591c5301e023a51aea7
  remediation:
    wave: P1.3
    change: beta_mu_non_intercept_uplift_after_sampler_fix
    delta_intercept: 2.2
    rationale: restore single-site tier in B-band after S8 scope fix
    parent_bundle: version=2026-02-12/20260212T195808Z
    note: retain P1.2 coefficient shape; concentration to be evaluated with S2 poisson
      inversion patch
    beta_mu_non_intercept_scale: 1.4
    intercept_recenter: none_first_pass
dict_mcc:
- 742
- 743
- 744
- 763
- 780
- 1520
- 1711
- 1731
- 1740
- 1750
- 1761
- 1771
- 1799
- 2741
- 2791
- 2842
- 4011
- 4111
- 4112
- 4119
- 4121
- 4131
- 4214
- 4215
- 4225
- 4411
- 4457
- 4468
- 4511
- 4582
- 4722
- 4784
- 4789
- 4812
- 4814
- 4815
- 4816
- 4821
- 4829
- 4899
- 4900
- 5013
- 5021
- 5039
- 5044
- 5045
- 5046
- 5047
- 5051
- 5065
- 5072
- 5074
- 5085
- 5094
- 5099
- 5111
- 5122
- 5131
- 5137
- 5139
- 5169
- 5172
- 5192
- 5193
- 5198
- 5199
- 5200
- 5211
- 5231
- 5251
- 5261
- 5262
- 5271
- 5300
- 5309
- 5310
- 5311
- 5331
- 5399
- 5411
- 5422
- 5441
- 5451
- 5462
- 5499
- 5511
- 5521
- 5531
- 5532
- 5533
- 5541
- 5542
- 5551
- 5552
- 5561
- 5571
- 5592
- 5598
- 5599
- 5611
- 5621
- 5631
- 5641
- 5651
- 5655
- 5661
- 5681
- 5691
- 5697
- 5698
- 5699
- 5712
- 5713
- 5714
- 5715
- 5718
- 5719
- 5722
- 5732
- 5733
- 5734
- 5735
- 5811
- 5812
- 5813
- 5814
- 5815
- 5816
- 5817
- 5818
- 5912
- 5921
- 5931
- 5932
- 5933
- 5935
- 5937
- 5940
- 5941
- 5942
- 5943
- 5944
- 5945
- 5946
- 5947
- 5948
- 5949
- 5950
- 5960
- 5962
- 5963
- 5964
- 5965
- 5966
- 5967
- 5968
- 5969
- 5970
- 5971
- 5972
- 5973
- 5975
- 5976
- 5977
- 5978
- 5983
- 5992
- 5993
- 5994
- 5995
- 5996
- 5997
- 5998
- 5999
- 6010
- 6011
- 6012
- 6051
- 6211
- 6300
- 7011
- 7012
- 7032
- 7033
- 7210
- 7211
- 7216
- 7217
- 7221
- 7230
- 7251
- 7261
- 7273
- 7276
- 7277
- 7278
- 7296
- 7297
- 7298
- 7299
- 7311
- 7321
- 7322
- 7333
- 7338
- 7339
- 7342
- 7349
- 7361
- 7372
- 7375
- 7379
- 7392
- 7393
- 7394
- 7395
- 7399
- 7512
- 7513
- 7519
- 7523
- 7531
- 7534
- 7535
- 7538
- 7542
- 7549
- 7622
- 7623
- 7629
- 7631
- 7641
- 7692
- 7699
- 7800
- 7801
- 7802
- 7829
- 7832
- 7841
- 7911
- 7922
- 7929
- 7932
- 7933
- 7941
- 7991
- 7992
- 7993
- 7994
- 7995
- 7996
- 7997
- 7998
- 7999
- 8011
- 8021
- 8031
- 8041
- 8042
- 8043
- 8049
- 8050
- 8062
- 8071
- 8099
- 8111
- 8211
- 8220
- 8241
- 8244
- 8249
- 8299
- 8351
- 8398
- 8641
- 8651
- 8661
- 8675
- 8699
- 8734
- 8911
- 8931
- 8999
- 9211
- 9222
- 9223
- 9311
- 9399
- 9402
dict_ch:
- CP
- CNP
dict_dev5:
- 1
- 2
- 3
- 4
- 5
design:
  beta_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
  - gdp_bucket_onehot([1,2,3,4,5])
  beta_mu_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
beta:
- 1.060423738098163
- -0.12355519992395293
- 0.6491379679497475
- 0.2529727775030237
- -0.9053807799197521
- 0.014423710998464628
- -0.3702318930787536
- -0.33798272406458135
- 1.1610070846442218
- 0.7208970768869805
- -0.25345560531329464
- -0.25123849181546987
- 0.2726066590800409
- 1.2152963768700502
- -0.6474758343442504
- 0.565548433318983
- -0.5471936098788812
- 1.1860556663818425
- 0.4244529740204774
- -0.08517964388838668
- 0.5635306350190763
- 0.27736169825485363
- 0.627943764512698
- 0.5148964368343001
- 0.5643290338453254
- 0.1705034667554028
- 0.17676049276390685
- 0.08148455192436094
- 0.534510098607455
- -0.33868676841838374
- 0.5744346291624133
- 0.0709378810256845
- 0.42004227953758577
- 1.2144401361355912
- 0.15561957679748165
- -0.32807931265784435
- -5.556305332257111
- 0.48408096272473317
- 0.053158358187763974
- 1.6773937758385775
- -0.3809119743500184
- 0.4103959843692794
- 0.6561634844315043
- -0.01899151950168879
- -0.03938299136530882
- -0.6096115081711363
- 0.6469796312451648
- -0.008403409481851245
- 0.4508352798838222
- 0.3096969289422762
- 0.42958998294609746
- 0.32187323958378106
- 0.3136845620140716
- 0.30501974624349865
- 0.029754587292650993
- -0.19305090038840828
- 0.44022042006851897
- -0.3511290688263239
- -0.616899534893281
- 0.31052970922422374
- 0.03177549751542108
- 0.2465158212944597
- -0.7571067433758978
- -1.1187817701065939
- -0.35569491279675375
- 0.08108135818967457
- 0.5355901360052674
- 0.07771930498233827
- -0.18455558901143093
- 0.6542089863011594
- 0.7294759746907631
- 0.5114587441242302
- 1.129145221859367
- 0.012004445200800748
- 0.6536315473173535
- 0.6472664966104283
- 0.8167201031618881
- -0.9200961000224505
- 0.3234386004177801
- -0.1407714758328826
- 1.118650529348533
- 0.9178522263028093
- 0.4324916977868366
- 1.026268131833808
- 1.2358220758664928
- 0.8226844851451212
- 1.205228197126019
- 0.537910030489806
- 1.6197447599597357
- 1.7827265356063569
- 0.52727979602855
- 1.7896311722781808
- 1.3116165800611326
- 0.30759396767768676
- 0.7285012896845053
- 0.24986782851404218
- 0.7913863276947197
- 0.4247518534644013
- 0.22000358665491376
- 0.572134893824342
- 1.0945468471325377
- 0.3038863184814762
- 0.9851975338482422
- 0.14853131856908103
- 0.7808474756888278
- -1.1591157441190527
- 0.32158606390650646
- -0.11123114085125216
- 0.5408610628888055
- 0.09910126040310344
- 0.4206389907684716
- 0.5059745896067693
- 0.66355972467946
- 0.23459524178603194
- 0.8345064917189555
- 0.6787038147465325
- 0.5329393986353501
- -0.00016901876176376565
- 0.7120846936865396
- -0.2921694636642049
- 0.7193193693219733
- -0.24945962571933994
- 0.7123498761770943
- 0.2603652367105659
- 0.9286097860882617
- 0.7316780589869276
- 0.44536536414169137
- -0.8368946858984847
- 0.6112666575729918
- 0.49880809492698625
- 0.19252197480758085
- 0.13011793271903327
- 1.0270106992691785
- 0.30419149900727954
- -0.13262183854760645
- -0.2816905960153228
- 0.09160978483191087
- 0.10016973819316388
- -1.6916911208557417
- 0.27471755339625364
- -0.28601995337608527
- -0.1932736735529803
- 0.39745834341752617
- 0.05849018240789916
- -0.17200926247803128
- 0.34185105846244385
- 0.21424273463322854
- -0.19811575551993937
- -0.3492111416222488
- -0.12294813531433404
- 0.05998233231905007
- -0.17338310867943182
- 0.10589704950104696
- 0.63559054573423
- -0.2791978457532176
- 0.5322142084392832
- 0.5830055604401227
- 0.5604014881094035
- 0.7249258346579842
- -1.0401230540046884
- 0.24911202687162518
- 0.4225773207639346
- 0.25204916343199174
- -0.27812631424952966
- 0.2409284594984029
- -0.47241177823345976
- -0.2692367588144125
- 0.18603522312108417
- 0.0067348759500703735
- 0.3582752194801141
- 0.16297976987876336
- 0.4833661356899183
- -0.5441005509571241
- -0.21085265981801307
- -0.10221069566261512
- -0.5628037626774556
- -0.41774885208914647
- 0.19951333491186213
- -0.38914008051359134
- -0.08492581038926812
- -0.45543404859785874
- 0.14080407816449503
- -0.6924834819680055
- -0.8370565946384365
- 0.3723020749859881
- -0.815230049941712
- 0.22934613239564317
- -0.5046848240361851
- 0.16575222124721076
- -1.4250638199596695
- 0.038017874265135865
- -0.18253595356549346
- -0.3715819598822544
- -0.8611853217790802
- -0.006139643333341906
- 0.16830375686740193
- 0.3173746341605253
- 0.3002345517329067
- 0.17623135666560077
- -0.7287956082173863
- -0.9610628779015137
- 0.40605076981653027
- 0.18226222439069437
- -0.3121466589126882
- 0.22762008657128616
- 0.044149816094843135
- -0.03943527552502154
- 0.3863088330089787
- 0.480452955555161
- -0.2049837814597023
- 0.050385871559901374
- -0.86970753459761
- -0.8251194618170815
- 0.9662631116481216
- -0.6631237938563594
- -0.10926841597306858
- -0.5961988754115395
- -0.8079011046540583
- -0.3132044063138858
- 0.511834421544762
- -1.1616780169153382
- 0.3505700329797492
- 0.05964695186496368
- -1.626218180702916
- 0.5302477212829408
- 0.4500502746449453
- -0.17234828361777377
- 0.133881736839792
- 0.4253774524525599
- 0.23354527852141105
- -0.3302777701554893
- -1.3740227763719435
- 0.4610965540307373
- -0.8513626416075153
- -0.47945831812878925
- 0.18404223851638873
- -0.8964049444686198
- -0.27064157337001665
- 0.4179557786050321
- -0.44259527303420265
- 0.43009217402544675
- -0.3137971898815487
- -0.35204769932807856
- -0.6105098962679495
- 0.003493954948993786
- -0.7610815837116025
- 0.18722894893688763
- -0.7706489439135431
- -0.9318324397853136
- 0.17066248487527066
- -0.7111113170053198
- -0.3294506455420305
- -0.8509799257045816
- -0.5791717226599604
- -0.1997006930480287
- -0.30232660716434606
- -0.7696726379425509
- 0.16322162315629277
- -0.45996453998376957
- 0.4082491375430201
- -0.04016180640420546
- -0.3237080982593376
- -0.5319459418262676
- -0.6150641506884175
- 0.48126632741328323
- 0.3259158291079374
- -0.5596192163629057
- 0.31632966227601356
- -0.47700378139621824
- -0.8337738578537423
- -0.38369089735113415
- -0.7091902266158834
- -0.4262592921097843
- -0.7655132657256938
- -0.5773276246783964
- -6.850110469270412
- -0.8514134414452039
- 0.049427516618458206
- -0.03575410450426962
- 0.48972276897077505
- 0.013318418254464292
- -0.09098549330811943
- -6.86544681845988
- -0.37612537944065366
- 0.41839605148232034
- -0.556639500130873
- -1.0632389090792185
- -0.8476479959836294
- 0.3589885724100375
- -0.9218571039778817
- -0.17488049754930932
- -0.28750660784290355
- -0.8520696527283449
- -0.7844325078593459
- -0.4810454702602077
- -0.2560555372181693
- -0.007979490332166226
- 0.38993674638828835
beta_mu:
- 1.7814957339620379
- -0.49623489396101284
- -0.2879866789576738
- 0.016708702383084872
- -0.6748105157447272
- -0.17276510389135177
- 0.4845028245943001
- 0.09384939793243333
- 0.2785618507336885
- -0.04522342562016549
- 0.3272091052793641
- -0.30507724845432566
- 0.021704434479664095
- 0.3627820924341608
- -0.9170826272147163
- -0.38277276622597556
- 0.048521424645159975
- 0.23939621472666095
- 0.013372394042202279
- 0.16097966802582195
- 0.1410046973800089
- 0.7200053686438086
- 0.2739947756169491
- 0.3927651861821736
- 0.07148748194246393
- 0.5858458272852746
- -0.29355159778251577
- 0.14302508419136506
- 0.8169585093677658
- 0.23860268675270951
- 0.2638773869161852
- -0.20350711797055457
- 0.3305431893114849
- 0.6377844365902046
- -0.1181186118314402
- 0.014133644045820588
- 0.0
- -0.13177712609602837
- -0.22127921515942586
- -0.2805216832402368
- 0.10755890625188322
- -0.07965725584731119
- -0.13147745336912625
- 0.0019631569969079474
- -0.4407030796866285
- 0.47215739616730923
- -0.029590317742942487
- 0.2032902931819956
- -0.058318809209315044
- 0.014742687211938782
- -0.16709803054507966
- -0.027058171630116902
- 0.1554744516603695
- -0.23944147382701217
- -0.4962348939610121
- -0.35806749585374303
- -0.11038807920471778
- -0.08120683350619332
- -0.2844586003024413
- 0.047534434672494956
- -0.533101857700316
- 0.0876628411354302
- -0.674810515744727
- 0.8016005189805245
- 0.18457768618218487
- 0.17988848551044653
- 0.15784819922052265
- 0.008795821924244879
- -0.24934722068385565
- 0.045244859736294066
- 0.1353454723168173
- 0.1455625237550731
- 0.008793293282699946
- 0.027916597777946896
- 0.7421999980049424
- 0.3079249741233429
- 0.35712870048081724
- 0.24995618889057875
- 0.3286295724820877
- 0.6141618651974352
- 0.9448406474751444
- 0.5294480655504538
- 1.0545394962882177
- 0.8219965667964764
- 0.8931199069305374
- 0.5080909456453829
- 0.6845940118500019
- 0.611163430027875
- 0.6866451641359719
- 0.6654570142698518
- 0.5860372680463836
- 0.9043430592179087
- 1.101665313852048
- 0.6846034564708279
- 0.5610261876649832
- 0.43878105661245864
- 0.39712600704280404
- 0.5617404224764255
- 0.2517612318158337
- 0.439233993233397
- 0.12590703260829658
- -0.14400750183065278
- 0.3091752775260858
- 0.3345474826686918
- 0.2964557229246102
- 0.09383376418298581
- -0.41688395903828235
- 0.19428444308945197
- 0.34000931399508566
- 0.2457924472050845
- -0.12279861127001027
- 0.6467085886610241
- -0.12547838060682123
- 0.22994392995806834
- 0.02928496425551973
- -0.15642338753972315
- 0.20399222469342287
- 0.5897366200964851
- 0.1011397613619146
- 0.5015751139812545
- -0.11898345774647573
- 0.17986017852632627
- 0.5282865579277404
- 0.09458397259504052
- 0.2464622953426407
- 0.2795153695211022
- 0.43711628008417175
- 0.5108254147371434
- -0.0610375224837823
- 0.29458221539847324
- 0.34407102746595286
- 0.07231712612173706
- -0.43933471893815584
- -0.22364178369113
- 0.2748099463482346
- 0.15262038227258246
- -0.31198413080056486
- 0.014742687211938223
- 0.09378689417090647
- -0.34457057484479836
- 0.42682942288003567
- -0.2532999772031886
- 0.11892300972540554
- 0.008363394643949534
- 0.050034900245716135
- -0.4395021742264247
- -0.034777960778749374
- -0.189897420255574
- -0.18035964267501933
- 0.5890219025755017
- 0.09772844665500197
- -0.17615417191340116
- -0.31036107009150626
- 0.06226527598034128
- 0.876203186179596
- -0.1982900633595974
- -0.2747797002356774
- 0.31768648794251064
- -0.22768583992398167
- -0.5261060778058728
- 0.3871366864856516
- -0.1351707603865567
- -0.18924420039502973
- -0.005413585910438486
- 0.22999275706920197
- -0.15025170212433636
- -0.28924071734379747
- 0.32564104865678256
- -0.07205521428597848
- 0.33402902003583296
- -0.12120707097406827
- 0.29067686680589916
- 0.13612002185825822
- 0.05480489956843567
- 0.014133644045820444
- -0.26255303402451696
- -0.11339277821853326
- -0.32366455548709805
- -0.24759967639663824
- 0.06522955739988003
- -0.03744589509797801
- -0.617684971281666
- 0.1675492673918597
- 0.6149243723645667
- -0.06424822041347526
- -0.16128885401944937
- 0.05378792803682195
- 0.3095884366776802
- -0.04310324399979032
- -0.4732971731132394
- -0.5320923059833916
- -0.0749497337369908
- -0.20226014926646857
- -0.3174112787270423
- 0.00984942529392363
- 0.08951042146021738
- -0.24750432873986958
- 0.1913163584015396
- -0.03621227189941509
- -0.5359064846829017
- -0.9311803948935271
- -0.04573581669667483
- -0.3543575754527811
- -0.6428735866072637
- 0.05133042940825352
- -0.345262723406118
- 0.269163689477767
- 0.002670443732156602
- 0.08590734166315823
- -0.7068205668716524
- -0.018682306707472496
- -0.03372754491823126
- -0.5186880910371341
- -0.020607303927646824
- 0.30883571856197434
- 0.6296136812444387
- -0.578678452177111
- -0.22127921515942606
- -0.3580674958537435
- -0.23665130061664336
- -0.518688091037134
- 0.09386190868334053
- -0.08579693784103255
- 0.09378689417090644
- 0.1169394514977974
- -0.07068544801791248
- -0.6644049695591818
- -0.002721271597076815
- -0.22457905713686208
- -0.1758131254883522
- -0.30046877317431403
- -0.4732971731132398
- 0.2633914435101942
- -0.5186880910371339
- 0.04434474808226202
- -0.2060596635590287
- 0.29156347506902314
- -0.6233176088719043
- 0.11456570393764376
- -0.02687168844861277
- 0.15234043948972148
- -0.2097695839599902
- -0.14152909441415157
- 0.5262219359306508
- 0.04282208074662109
- -0.39112678193591605
- -0.18286318394596132
- 0.22282844312465072
- -0.8023718248459443
- 0.28515477394349376
- -0.30046877317431386
- -0.3467524855654641
- 0.06670601841705795
- -0.17095046886322002
- -0.4481568486726338
- 0.40306284194991704
- -1.1597710618636292
- -0.49471099231125976
- -0.2844586003024414
- -0.3261380418267489
- -0.4396200343907934
- 0.20156228512041138
- -0.674810515744727
- -0.43180752705547987
- -0.4137395743767941
- -0.3211910691474465
- -0.5528723966586513
- -0.6148578206687232
- -0.25369401598452557
- -0.24242234399706233
- -0.21248025694455144
- -0.3695136417924569
- -0.6749791762085472
- -0.742026395776089
- -0.5968984534292687
- 0.0
- 0.45123300120067006
- -0.1325425876876531
- -0.2587896175247229
- -0.19963275049164664
- -0.6233176088719041
- -0.41784733390444145
- 0.0
- -0.07846647210112513
- 0.22601012983806235
- -0.08568547353294449
- 0.31625370533071334
- -0.5261060778058729
- -0.4736915216994024
- -0.16128885401944942
- -0.04415848733070811
- 0.9040467202002692
- 0.6064891398846226
