semver: 1.0.0
version: '2025-12-31'
metadata:
  simulation_manifest: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T134200Z/manifest.json
  simulation_config_path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/models/hurdle/hurdle_simulation.priors.yaml
  seed: 9248923
  created_utc: 20251231T134200Z
  inputs:
    priors:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/models/hurdle/hurdle_simulation.priors.yaml
      sha256: 3a1858d7979b01fbcc7f97bcbde0c8b5af8b01343f4865714afd13ae9789d564
    transaction_schema_merchant_ids:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/layer1/transaction_schema_merchant_ids/2025-12-31/transaction_schema_merchant_ids.parquet
      sha256: a5ce122a1c61a4247ba4ece8624a201fe824c72c10f352cfba74623e54a0cb12
    world_bank_gdp_per_capita:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/world_bank_gdp_per_capita/2025-04-15/gdp.parquet
      sha256: 1eb6d9ae47639b17fd41e7875c03247c4133a849b442c0e3ebe61a4cb2c06074
    gdp_bucket_map:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/gdp_bucket_map/2024/gdp_bucket_map.parquet
      sha256: 624c9d1029e81980c7d7eb368a7ed07d67c62d8423d0c053cdcd9c58a6c80a3b
    iso3166_canonical:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/iso/iso3166_canonical/2024-12-31/iso3166.parquet
      sha256: bfb68d1770abef6a74571cfea4d659eefb7b6c7b39e81f1b6cc483bd60bd8b5f
    logistic:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T134200Z/logistic.parquet
      sha256: debf8f31ae020f2418119a5a7d1cb8d9395ad90ec008e11ebaba2538098754e8
    nb_mean:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T134200Z/nb_mean.parquet
      sha256: 76ce8da13ca0472e3e3083d48c43c07285c741ecf12b9eb1df5d9bfb3017eba5
dict_mcc:
- 742
- 743
- 744
- 763
- 780
- 1520
- 1711
- 1731
- 1740
- 1750
- 1761
- 1771
- 1799
- 2741
- 2791
- 2842
- 4011
- 4111
- 4112
- 4119
- 4121
- 4131
- 4214
- 4215
- 4225
- 4411
- 4457
- 4468
- 4511
- 4582
- 4722
- 4784
- 4789
- 4812
- 4814
- 4815
- 4816
- 4821
- 4829
- 4899
- 4900
- 5013
- 5021
- 5039
- 5044
- 5045
- 5046
- 5047
- 5051
- 5065
- 5072
- 5074
- 5085
- 5094
- 5099
- 5111
- 5122
- 5131
- 5137
- 5139
- 5169
- 5172
- 5192
- 5193
- 5198
- 5199
- 5200
- 5211
- 5231
- 5251
- 5261
- 5262
- 5271
- 5300
- 5309
- 5310
- 5311
- 5331
- 5399
- 5411
- 5422
- 5441
- 5451
- 5462
- 5499
- 5511
- 5521
- 5531
- 5532
- 5533
- 5541
- 5542
- 5551
- 5552
- 5561
- 5571
- 5592
- 5598
- 5599
- 5611
- 5621
- 5631
- 5641
- 5651
- 5655
- 5661
- 5681
- 5691
- 5697
- 5698
- 5699
- 5712
- 5713
- 5714
- 5715
- 5718
- 5719
- 5722
- 5732
- 5733
- 5734
- 5735
- 5811
- 5812
- 5813
- 5814
- 5815
- 5816
- 5817
- 5818
- 5912
- 5921
- 5931
- 5932
- 5933
- 5935
- 5937
- 5940
- 5941
- 5942
- 5943
- 5944
- 5945
- 5946
- 5947
- 5948
- 5949
- 5950
- 5960
- 5962
- 5963
- 5964
- 5965
- 5966
- 5967
- 5968
- 5969
- 5970
- 5971
- 5972
- 5973
- 5975
- 5976
- 5977
- 5978
- 5983
- 5992
- 5993
- 5994
- 5995
- 5996
- 5997
- 5998
- 5999
- 6010
- 6011
- 6012
- 6051
- 6211
- 6300
- 7011
- 7012
- 7032
- 7033
- 7210
- 7211
- 7216
- 7217
- 7221
- 7230
- 7251
- 7261
- 7273
- 7276
- 7277
- 7278
- 7296
- 7297
- 7298
- 7299
- 7311
- 7321
- 7322
- 7333
- 7338
- 7339
- 7342
- 7349
- 7361
- 7372
- 7375
- 7379
- 7392
- 7393
- 7394
- 7395
- 7399
- 7512
- 7513
- 7519
- 7523
- 7531
- 7534
- 7535
- 7538
- 7542
- 7549
- 7622
- 7623
- 7629
- 7631
- 7641
- 7692
- 7699
- 7800
- 7801
- 7802
- 7829
- 7832
- 7841
- 7911
- 7922
- 7929
- 7932
- 7933
- 7941
- 7991
- 7992
- 7993
- 7994
- 7995
- 7996
- 7997
- 7998
- 7999
- 8011
- 8021
- 8031
- 8041
- 8042
- 8043
- 8049
- 8050
- 8062
- 8071
- 8099
- 8111
- 8211
- 8220
- 8241
- 8244
- 8249
- 8299
- 8351
- 8398
- 8641
- 8651
- 8661
- 8675
- 8699
- 8734
- 8911
- 8931
- 8999
- 9211
- 9222
- 9223
- 9311
- 9399
- 9402
dict_ch:
- CP
- CNP
dict_dev5:
- 1
- 2
- 3
- 4
- 5
design:
  beta_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
  - gdp_bucket_onehot([1,2,3,4,5])
  beta_mu_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
beta:
- -1.166434147554944
- 0.12456339741398786
- -0.2890411518494914
- -0.5208724110467555
- -0.1759151162303173
- -0.07995233408389824
- -0.31374894215558335
- -0.3812479968843241
- -0.21805741703455098
- 0.136369873636808
- 0.26233581450212573
- 0.15874711705527653
- -0.711854068965056
- 0.19368456740760623
- -0.49899835819070437
- -0.2117146348505751
- -0.09989961253044817
- -0.7269179832642301
- 0.2729702052288171
- 0.4358250208653015
- 0.3086476338772109
- 0.38059600509399844
- -0.03904629090262676
- 0.41031420408116553
- 0.0013958239667895616
- 0.46971136167412314
- 0.33047293322408483
- 0.23942907110628986
- -0.09214457431436264
- -0.2839597630105638
- 0.4775756002613283
- 0.04291610896433492
- -0.422571848136596
- -0.0894485639635821
- -0.5113863936328356
- -0.06294351118629812
- 0.08484921742247115
- -0.056972808812403374
- 0.30127377413942796
- 0.03409255825728771
- -0.6960904096040754
- 0.018511169255541714
- -0.33859386248072076
- -0.05920575126209651
- 0.35003435928103643
- 0.4329029466924724
- 0.06684546902944034
- 0.025256627273489766
- 0.11615929072046284
- 0.16966302064036715
- -0.03490091384530665
- 0.01406631573301912
- 0.11131739312161718
- 0.013725493083546137
- 0.12553884556394448
- 0.39173724752354555
- 0.3762409144602605
- 0.14874194332505203
- 0.3475260868834796
- -0.028472366796377758
- 0.004557048565913437
- -0.03332689715325851
- 0.11982124264975796
- -0.20452409921874823
- -0.036916647853393145
- -0.02507311809690272
- 0.3253005689125816
- 0.4184686866722476
- -0.25220386725049043
- -0.08754185415081356
- -0.4501726370648454
- 0.17955602824483058
- 0.46801593689616544
- -0.11750319352461985
- 0.6454390352520614
- 0.5933469646761818
- 0.47029986381382877
- 0.6997612213818579
- 0.7110430128562607
- 0.8842551663683093
- 1.2749084982148495
- 1.1050918295123686
- 1.0457682230988412
- 0.9668737976181822
- 0.9332015216207813
- 0.7900008463225789
- 0.9227324198521552
- 0.9519963848935036
- 0.9175802623739925
- 0.8469785689914421
- 0.800753063585482
- 1.4698701016549522
- 1.405311381576816
- 0.7066238031213871
- 0.7458804776073705
- 0.7804003732920831
- 0.8680338811888969
- 0.8001918124754891
- 0.8514614096048874
- 0.4994864205710973
- 0.7452121410080776
- 0.4481654044085459
- 0.2976133682636074
- 0.20997900039710515
- 0.505078243123284
- 0.37217752025190914
- 0.2412181324079784
- 0.4370179444779434
- 0.20716701076969857
- 0.18558599573517004
- 0.356106853655206
- 0.16359038983359894
- 0.24994755228718635
- 0.22346046149334733
- -0.2784309524720033
- 0.5760793202115029
- 0.2737198139606178
- 0.21082468071513277
- 0.030844067457278905
- 0.4433628597378141
- 0.4999318488251522
- 0.40868597438718274
- 0.22441739403000516
- 0.5106174966464452
- 0.6657100820413254
- 0.43844005467240643
- 0.5422995725391503
- -0.017608076151312206
- -0.08133663601640058
- 0.030766858994510125
- 0.03592071534075634
- 0.1316045619954839
- -0.01943721364436971
- 0.18618163295877158
- 0.36615857055543016
- 0.22209056305926242
- -0.504467765173034
- 0.050037627875843024
- 0.2723014292443709
- 0.040764374433621346
- 0.17108147768527074
- -0.5937104243535799
- -0.19168640483090854
- 0.012252371659729581
- -0.12836712173826983
- -0.0763619398456702
- -0.028452504706820928
- -0.26284185163461515
- 0.06263662578003741
- 0.3522718564028375
- 0.06501569448566068
- -0.322426743039516
- 0.1683366978168666
- 0.3150605621511061
- -0.07505659892004334
- -0.12182123560965764
- -0.008095050440274833
- 0.23416782193964988
- -0.036290014941251406
- -0.2130436074062643
- 0.2518704874282757
- 0.22884877714517038
- 0.1566524719592579
- 0.1776109428259145
- 0.10782329497017001
- -0.1343970124412158
- 0.1084866763399787
- 0.09932873499788596
- 0.35095127757444816
- 0.2351798776562072
- -0.169964299949759
- 0.0715785384093063
- 0.12654601422618184
- -0.05499669681914436
- -0.31191836132247763
- -0.1954527790741613
- -0.04484541274000162
- -0.8154185775068191
- -0.45935683556644863
- 0.30038807867180445
- 0.21779057979849933
- -0.18552190477580832
- -0.7235773231717377
- -0.07055255893638403
- 0.23505771870394468
- 0.21513525615634851
- -0.27293051917444333
- 0.18371544836147516
- -0.35473104177448167
- -0.7067717598081723
- -0.31118419802972025
- 0.41844366051424364
- 0.18222342960539864
- -0.20894039236259943
- -0.6241533646498522
- -0.5961163814955003
- 0.1729563936390299
- -0.06636300322227993
- -0.4140042062753991
- -0.28888557248069413
- -0.36674745498688754
- -0.17098856635527743
- -0.056943273162253165
- -0.5538984345744412
- -0.6003221838675404
- -0.6124893660996107
- -0.6083329045912698
- -0.2839539809450954
- -0.04797530597480745
- -0.18807082543650802
- 0.41894838186356137
- -0.05713454042126507
- -0.3327918822111886
- -0.11590589693674377
- 0.10732762877296335
- 0.0033472434311662075
- 0.17246812068483375
- -0.4811282279589984
- 0.11911979098367803
- -0.04188031422599437
- 0.09790360267737959
- -0.670898538378143
- -0.6594525384788019
- -0.035059626612314994
- 0.2875307160510471
- -0.4296009841184511
- -0.11471207145964155
- 0.5531321098505384
- -0.6510233472589025
- 0.2735430846897991
- -1.1164792301772541
- -0.17298659593950533
- 0.10603202311781751
- -1.1401884330932492
- -0.3219900448265031
- 0.212232375606892
- 0.05965618054190878
- 0.20164772979129264
- -0.6039763328806659
- -0.55757976722902
- -0.4879827578354061
- -1.0662444799971367
- 0.6910208880137862
- -0.027445580495380473
- 0.2881256356374795
- -0.1602130771910698
- -0.09780503500296917
- -0.36540302891374743
- -0.5833152028960384
- 0.46020300493790395
- -0.36942792697730104
- -0.9245544403521608
- -0.3449025892999802
- -0.6960298875034787
- 0.1352940908239936
- -0.4443527300019035
- -0.040089114900395545
- -0.8578562514539256
- -0.925617369454011
- -0.2538417419991597
- -0.5473601845504423
- -0.4275830652820024
- -0.24136649326448034
- -0.4847951482701677
- 0.022175679207698706
- -0.8258293305478452
- -0.5983031735909773
- -0.4245621762039333
- -1.2249730962721492
- -0.4592218979992543
- -0.2302326224302459
- -0.32386023242511425
- -0.26820124262866146
- -0.5446532812004908
- -0.05737498084622399
- -0.7979452975204523
- 0.018164053890201967
- -0.6692816485407771
- -0.9501500123329487
- -0.16078015834600554
- -0.008145698893633873
- -0.5349694553878924
- -0.35748695719516793
- 0.04906861976650699
- -0.14048869936856415
- -0.30734387659141366
- -1.7537304544801033
- -1.8076392204320173
- -1.2979818690094156
- -0.17890665081900975
- -0.6634181191918181
- -0.298909164447608
- -0.8675249964277161
- -0.7947074667734411
- -0.5344350081662217
- -0.2619966731229617
- 0.07127605774715493
- 0.3534289775179169
beta_mu:
- 1.8820464249108122
- 0.06868149572987889
- 0.007076626312013894
- -0.10699193350228389
- -0.11602431388210072
- -0.09918812694517526
- 0.257194261768644
- 0.04106409231421902
- -0.13078947030309493
- -0.15023988818829653
- -0.1522831862761666
- -0.3141432011127013
- -0.19372057127792539
- -0.07437744018133259
- -0.10824897543735125
- -0.18833805021572791
- -0.1298027398541561
- -0.29242999425848476
- 0.19346523493409132
- -0.08082350441800906
- 0.3077680420668231
- -0.050138981602355186
- 0.15917534443880907
- 0.1478310774467545
- 0.06858457466077356
- 0.18616150489448957
- 0.1246470822759758
- -0.004416681483627151
- -0.001983628011312098
- 0.5973540682974708
- 0.14550591496953358
- 0.22317648078602367
- 0.016800122884874
- 0.024517299039921406
- -0.13426561777124751
- 0.0975971712747279
- -0.05808241850156192
- -0.02938838367056061
- -0.19252509577358012
- -0.31711924505151773
- 0.14390362387391337
- -0.1727860708392561
- -0.11022142381928911
- -0.1305338163996809
- -0.0816235861203003
- -0.1349804578458443
- -0.10994823719568815
- -0.06592292080971078
- -0.049137586280652686
- -0.05793313690495763
- 0.08469660187306577
- 0.1094424549431218
- -0.04344004542839449
- -0.06098719089422278
- 0.015250691843965889
- -0.05771516611142498
- 0.09736443891454782
- 0.0634903438607325
- 0.02582576079120247
- -0.2722076611143293
- -0.03479224010816901
- -0.18625326651689522
- 0.0262487499386305
- -0.04911849820176032
- -0.09313708660528117
- -0.05650830816466768
- -0.03927421285430285
- -0.043500039829272294
- -0.014753534827715343
- 0.04665976278961951
- -0.12020319913482756
- -0.15586616987176494
- -0.07796013222178184
- 0.04520898914583762
- 0.24128350017865088
- 0.2881990735314
- 0.09038624532857863
- 0.20615291277975964
- 0.17685280714844812
- 0.2766640483864032
- 0.7144470416969382
- 0.5099559121072645
- 0.4596320295819919
- 0.5259065724362215
- 0.4464373983869904
- 0.30230432644351296
- 0.34677401822631976
- 0.21543999107113818
- 0.4474396716902784
- 0.4522462575536973
- 0.4902855459695064
- 0.75633736766891
- 0.7802655734070284
- 0.4356773675981238
- 0.3654425327257655
- 0.3451652182950305
- 0.3064692505407075
- 0.31986617558159935
- 0.3623108764096484
- 0.3266611892471642
- 0.12024951226208198
- -0.0048870985058582705
- 0.2606757144845228
- 0.13755035804324584
- 0.2173619889585132
- 0.15051716077913693
- 0.21566014417787643
- 0.23227913931853045
- 0.07164528571006094
- 0.17090507296004664
- 0.0785202639680604
- 0.06835071975306627
- 0.18452581175460545
- 0.1129653819973179
- 0.26985811450289254
- 0.11307278806595326
- 0.08109220483186046
- 0.1702884882444088
- 0.13734168756952475
- 0.15973336074535613
- 0.23369261655948004
- 0.20209349946220817
- -0.013661568162689732
- 0.2570932492391909
- 0.3561099146447205
- 0.13979620364729978
- 0.39774279750429825
- 0.029332549667663212
- 0.11149944124549667
- 0.00577794098903883
- -0.02696166586884492
- -0.05356458440999328
- -0.00810247050334725
- 0.05057995170166682
- -0.11725209569438542
- -0.01742044560272172
- -0.21212787455030294
- -0.12106571923764177
- 0.13590727932308924
- -0.11492818653692405
- 0.07379942044311734
- -0.15751364848881558
- -0.03814028375951343
- 0.09040867221700614
- 0.1294959449216627
- -0.10260916836334959
- -0.015726008232125957
- 0.13367228383579485
- -0.00415152633166129
- -0.017882725112911994
- -0.06350201303188847
- -0.025365449654116544
- 0.06523279867104169
- 0.08894937854642894
- -0.04531203309881609
- -0.12480006651596372
- -0.23834015064139752
- 0.09555867420752688
- -0.0521204658544384
- -0.21658800367225708
- -0.18569875410639639
- -0.09815245468325268
- -0.21599317594533407
- -0.02919243453479868
- -0.17824990603973478
- -0.03023140860200864
- -0.026764476617001688
- -0.08514724391114849
- 0.004785424572408926
- 0.01947602788631809
- -0.19316465791259754
- -0.051826861465052124
- 0.001557114478679313
- 0.06042648643389277
- 0.063726884867714
- -0.012721307190142707
- 0.02068423391143232
- -0.059168688622446494
- -0.1997617997591845
- -0.041079444977757486
- -0.20504726734483583
- 0.13168642104681033
- -0.2680891484017141
- -0.11604118276088113
- 0.0055964465632917905
- 0.08676818050674893
- 0.17782536118348707
- 0.014136653014704133
- -0.020729342385431313
- -0.1457815490396687
- 0.0008610830332124244
- -0.198265048756583
- -0.16688045667578924
- 0.12375443752854427
- -0.12615431430272758
- -0.029486081460598265
- -0.16995013004516096
- 0.07360341978603253
- -0.12908139328658003
- -0.07445383063582846
- -0.0025423014640296557
- -0.23877166030874175
- -0.08409081701542809
- 0.15279526636244026
- 0.15355656987922459
- -0.558000658392124
- -0.3826351461682501
- 0.06100819609204476
- -0.09056698924937692
- -0.13432384393455912
- 0.14207651374730185
- -0.022218312153527056
- 0.15241600220644136
- 0.09881130636203309
- -0.05149182259525275
- 0.07864984482278285
- -0.018729189738529956
- 0.006929089669363614
- 0.04334762014770406
- -0.12199327063851335
- 0.03262027720014773
- 0.15541955514233347
- -0.09777276953017142
- -0.05881712763248956
- 0.019426397863732577
- -0.1388557771569347
- -0.14115324381719815
- 0.05616440643181695
- -0.13974032055840999
- -0.010954159671250494
- 0.03994566800207806
- 0.015624489384141675
- 0.19556477331203062
- -0.3073116551540918
- -0.04873677965502224
- 0.2250936884081938
- -0.3667669127580919
- 0.036912410912248554
- -0.2548308680150114
- 0.16386760141382176
- -0.21622012951944164
- 0.38010476651135106
- -0.05806868895880222
- -0.17933570692545608
- -0.04638618072784993
- -0.00944768861490832
- -0.14429379859925354
- -0.10730254386354664
- -0.030276269826213197
- -0.16865128118445166
- -0.1394267785822841
- 0.048128487140023164
- -0.3671026977436369
- 0.0691231998426831
- -0.015678121028548535
- -0.33929031918587754
- -0.1520241955618622
- -0.4918302457903304
- -0.32469202692588967
- -0.05688613101460145
- 0.15010705536265395
- -0.21310305444535535
- -0.44286369181398155
- -0.18902620751077112
- 0.027469789236519493
- 0.17402345579748502
- -0.16554437941663147
- 0.0870544623376529
- -0.3552722863761783
- -0.05832121692814892
- -0.278303049138653
- -0.018958819916408628
- -0.039069067475278635
- -0.1713589243416557
- -0.2851124855265195
- 0.09369748408927438
- -0.16581276871476816
- -0.0072634427925948215
- 0.1265801614000363
- -0.03568168349015608
- 0.012419044808232433
- -0.22523408490252217
- -0.24274868499204127
- -0.0035021395259816714
- -0.16352186385528034
- -0.180886941971238
- -0.90376348529653
- -0.9037634852965298
- -0.3551835126914267
- -0.06222928334946093
- -0.2665413725614211
- 0.5949015607037845
- 0.4080114215056086
