semver: 1.0.0
version: '2025-12-31'
metadata:
  simulation_manifest: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T134200Z/manifest.json
  simulation_config_path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/models/hurdle/hurdle_simulation.priors.yaml
  seed: 9248923
  created_utc: 20251231T134200Z
  inputs:
    priors:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/config/models/hurdle/hurdle_simulation.priors.yaml
      sha256: 3a1858d7979b01fbcc7f97bcbde0c8b5af8b01343f4865714afd13ae9789d564
    transaction_schema_merchant_ids:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/layer1/transaction_schema_merchant_ids/2025-12-31/transaction_schema_merchant_ids.parquet
      sha256: a5ce122a1c61a4247ba4ece8624a201fe824c72c10f352cfba74623e54a0cb12
    world_bank_gdp_per_capita:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/world_bank_gdp_per_capita/2025-04-15/gdp.parquet
      sha256: 1eb6d9ae47639b17fd41e7875c03247c4133a849b442c0e3ebe61a4cb2c06074
    gdp_bucket_map:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/economic/gdp_bucket_map/2024/gdp_bucket_map.parquet
      sha256: 624c9d1029e81980c7d7eb368a7ed07d67c62d8423d0c053cdcd9c58a6c80a3b
    iso3166_canonical:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/reference/iso/iso3166_canonical/2024-12-31/iso3166.parquet
      sha256: bfb68d1770abef6a74571cfea4d659eefb7b6c7b39e81f1b6cc483bd60bd8b5f
    logistic:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T134200Z/logistic.parquet
      sha256: debf8f31ae020f2418119a5a7d1cb8d9395ad90ec008e11ebaba2538098754e8
    nb_mean:
      path: C:/Users/LEGION/Documents/Data Science/Python & R Scripts/fraud-detection-system/artefacts/training/1A/hurdle_sim/simulation_version=2025-12-31/seed=9248923/20251231T134200Z/nb_mean.parquet
      sha256: 76ce8da13ca0472e3e3083d48c43c07285c741ecf12b9eb1df5d9bfb3017eba5
dict_mcc:
- 742
- 743
- 744
- 763
- 780
- 1520
- 1711
- 1731
- 1740
- 1750
- 1761
- 1771
- 1799
- 2741
- 2791
- 2842
- 4011
- 4111
- 4112
- 4119
- 4121
- 4131
- 4214
- 4215
- 4225
- 4411
- 4457
- 4468
- 4511
- 4582
- 4722
- 4784
- 4789
- 4812
- 4814
- 4815
- 4816
- 4821
- 4829
- 4899
- 4900
- 5013
- 5021
- 5039
- 5044
- 5045
- 5046
- 5047
- 5051
- 5065
- 5072
- 5074
- 5085
- 5094
- 5099
- 5111
- 5122
- 5131
- 5137
- 5139
- 5169
- 5172
- 5192
- 5193
- 5198
- 5199
- 5200
- 5211
- 5231
- 5251
- 5261
- 5262
- 5271
- 5300
- 5309
- 5310
- 5311
- 5331
- 5399
- 5411
- 5422
- 5441
- 5451
- 5462
- 5499
- 5511
- 5521
- 5531
- 5532
- 5533
- 5541
- 5542
- 5551
- 5552
- 5561
- 5571
- 5592
- 5598
- 5599
- 5611
- 5621
- 5631
- 5641
- 5651
- 5655
- 5661
- 5681
- 5691
- 5697
- 5698
- 5699
- 5712
- 5713
- 5714
- 5715
- 5718
- 5719
- 5722
- 5732
- 5733
- 5734
- 5735
- 5811
- 5812
- 5813
- 5814
- 5815
- 5816
- 5817
- 5818
- 5912
- 5921
- 5931
- 5932
- 5933
- 5935
- 5937
- 5940
- 5941
- 5942
- 5943
- 5944
- 5945
- 5946
- 5947
- 5948
- 5949
- 5950
- 5960
- 5962
- 5963
- 5964
- 5965
- 5966
- 5967
- 5968
- 5969
- 5970
- 5971
- 5972
- 5973
- 5975
- 5976
- 5977
- 5978
- 5983
- 5992
- 5993
- 5994
- 5995
- 5996
- 5997
- 5998
- 5999
- 6010
- 6011
- 6012
- 6051
- 6211
- 6300
- 7011
- 7012
- 7032
- 7033
- 7210
- 7211
- 7216
- 7217
- 7221
- 7230
- 7251
- 7261
- 7273
- 7276
- 7277
- 7278
- 7296
- 7297
- 7298
- 7299
- 7311
- 7321
- 7322
- 7333
- 7338
- 7339
- 7342
- 7349
- 7361
- 7372
- 7375
- 7379
- 7392
- 7393
- 7394
- 7395
- 7399
- 7512
- 7513
- 7519
- 7523
- 7531
- 7534
- 7535
- 7538
- 7542
- 7549
- 7622
- 7623
- 7629
- 7631
- 7641
- 7692
- 7699
- 7800
- 7801
- 7802
- 7829
- 7832
- 7841
- 7911
- 7922
- 7929
- 7932
- 7933
- 7941
- 7991
- 7992
- 7993
- 7994
- 7995
- 7996
- 7997
- 7998
- 7999
- 8011
- 8021
- 8031
- 8041
- 8042
- 8043
- 8049
- 8050
- 8062
- 8071
- 8099
- 8111
- 8211
- 8220
- 8241
- 8244
- 8249
- 8299
- 8351
- 8398
- 8641
- 8651
- 8661
- 8675
- 8699
- 8734
- 8911
- 8931
- 8999
- 9211
- 9222
- 9223
- 9311
- 9399
- 9402
dict_ch:
- CP
- CNP
design:
  beta_phi_order:
  - intercept
  - mcc_onehot(dict_mcc)
  - ch_onehot(['CP','CNP'])
  - ln_gdp_pc_usd_2015
beta_phi:
- 1.3883979273899032
- -0.02070711125950978
- -0.038061890817491215
- -0.05803812487267803
- -0.007155548821490783
- -0.04313295238473387
- -0.03634403336740731
- -0.03147888197940546
- -0.0297709112382052
- -0.05150969801263647
- -0.06276255604636369
- -0.05030143682804801
- -0.0487218410308644
- -0.062173329278066625
- -0.05766322235139693
- 0.008925924443620024
- -0.0611657352629238
- -0.11352167690154315
- -0.09363715233934217
- -0.0009930675417361375
- 0.03342820484184291
- -0.06673457657880348
- -0.04943424161594545
- -0.052687730906757234
- 0.013579601552143343
- -0.024671690828899553
- -0.07430386312609638
- -0.029343873842233907
- -0.10004445675466446
- -0.08680890541534877
- -0.08717169730034005
- -0.01982609406892618
- -0.06545637092370238
- -0.051593001944707666
- 0.008778129292251713
- 0.012574808593511264
- -0.0752983344222292
- -0.10307041356126019
- -0.06855070353496769
- -0.08307541515735915
- -0.07007803594100454
- -0.03939332864653008
- -0.02457658808766637
- -0.07901491089027432
- -0.09095829286951444
- -0.030298277760216458
- 0.0033162964946276204
- -0.06861847036285136
- 0.003479702882178778
- -0.061008540149727605
- -0.07161889417212303
- -0.05992383818790651
- -0.07001646772157054
- -0.09532259851119229
- -0.05723974586992551
- -0.006119584526352514
- -0.05849934110123127
- -0.05519741895610702
- -0.04968306860060138
- -0.10013520910390078
- -0.04802076551292593
- -0.08106420960153073
- -0.06866338290521189
- -0.04992187184921031
- -0.04542560206986558
- -0.054957884163125734
- -0.05845020676086663
- -0.043319657245306065
- -0.08821377389018698
- -0.0769471289427168
- -0.05309270022829562
- -0.0412405613755057
- -0.050316672944502705
- -0.06809579279664078
- -0.05666716744991548
- -0.05679886697097352
- -0.020311331952456525
- -0.06032570735320112
- -0.08301816734510976
- 0.30454032022927763
- 0.9935082209561068
- 0.34985131018805804
- 0.20444556196880279
- 0.1402347759828372
- -0.07413227634894451
- 0.6897504168659729
- 0.4770466175067291
- -0.0014494525422871604
- 0.35315570164289595
- 0.3525830862098767
- 0.5562395681042864
- 0.20108681179898
- 0.5703548011727904
- 1.2591438541425861
- 0.5995942983953682
- -0.016474835567615417
- 0.5229510650324161
- 0.4080880070792317
- 0.19352928339822734
- 1.5403051935982093
- -0.04908167216432497
- 0.0012784918697651539
- -0.083620382769147
- -0.08390469837242026
- -0.035869056559226696
- -0.050090907978714266
- -0.029027344131250507
- -0.08872055582155838
- 0.059621797957857804
- -0.011393846899458054
- -0.06967677512630696
- -0.026200108017072718
- -0.06685206731453652
- -0.08075000145982787
- -0.04819500495863133
- -0.08037479681470032
- -0.0340010148718247
- -0.07664328596915847
- -0.09897390700884166
- -0.046407485822411665
- -0.0611243758713032
- -0.016801377591002805
- -0.06690529341285992
- 0.330628486882196
- 0.2649461474191897
- 0.5484057511697016
- 0.09958285081374722
- -0.0815645932409362
- 0.6620531068357749
- 1.648189868475657
- 1.6426540831074017
- -0.03761918846997116
- -0.06847248981434646
- -0.051841730092552364
- -0.06392990214316337
- -0.03212147628764409
- -0.06973898454655406
- -0.049641021612374665
- -0.05655830010901951
- -0.08009302038610627
- -0.03707333061949968
- -0.0632888121772166
- -0.05211923717558053
- -0.04322216623564992
- -0.10277733864174936
- -0.04508072231147546
- -0.041114652612561656
- -0.06940509902404358
- -0.0726314021358305
- -0.07664910429277469
- -0.06985072073446096
- -0.06213863432916576
- 0.19606555506467718
- -0.05452636098030068
- -0.06689597590990519
- -0.04573480172633738
- -0.07141064221150269
- 0.19447620208701974
- -0.07921344794439289
- -0.0020787875455814306
- -0.058426583613143575
- -0.09972747603462276
- -0.04123675447130861
- -0.017706148226214052
- -0.0653100664925468
- -0.02174913320006042
- -0.03651420287250213
- -0.06661202356083165
- -0.05680446708537894
- -0.07916780410451525
- -0.06713490458872058
- -0.050569289694876354
- -0.050109429928955604
- -0.08891324031972535
- -0.0829527712522082
- -0.07472192061231918
- -0.0448956473283776
- 0.11200190998460881
- 0.018319900311652888
- -0.06725180488654355
- -0.022830801228596508
- 0.01726677329820926
- -0.03556584783855214
- 0.01771349962081441
- -0.05638552518676887
- -0.042115139205574845
- -0.018602414065474
- -0.08794829027788759
- 0.08811826047354573
- -0.010593511996107906
- -0.0608895488482063
- 0.01116373708141805
- -0.024291236063779382
- -0.0785765581533748
- -0.00784503243607689
- -0.07689058665709246
- -0.09745603333255531
- 0.006434462564448804
- -0.11287941435250912
- -0.028602298342246493
- -0.008220593571187347
- -0.03863101593128022
- -0.06776282461808023
- -0.07343625169429786
- 0.04477660293576693
- -0.13635555377928982
- -0.06333261782150684
- -0.10432391572111276
- 0.026765939887247084
- -0.06480450654742295
- -0.053080972248113
- -0.07239671516537578
- 0.032923298512553566
- -0.0030055227949765243
- -0.040344348388249705
- -0.09609904242184104
- -0.024828204074997015
- -0.0957372648519966
- -0.046971445674777026
- -0.10483812697605177
- -0.06310163352598293
- -0.07113484948511856
- -0.02401381349414024
- -0.047199699958352076
- -0.03547366765554607
- -0.0696666826707975
- -0.015329004862325902
- -0.08963620718007122
- -0.10796884766807933
- -0.09067306778111835
- -0.09415239879528894
- -0.0798877796265203
- -0.019507804295041013
- -0.0783999371307815
- -0.03712235546073678
- -0.041155365847058714
- -0.08665657108367984
- -0.10114671767140598
- -0.0922016541157626
- -0.06055063241313426
- -0.1188655326225875
- -0.09451243195877196
- -0.10448554408231862
- -0.06093617266007966
- -0.07200243424418178
- -0.038798580701001
- -0.11142788799653962
- -0.05833957393517101
- -0.055027923232571996
- -0.030553698889626793
- -0.06756925323972847
- 0.005249474529201734
- -0.10073601270071249
- -0.03226287929225765
- -0.07473199341804428
- 0.014080250994431406
- 0.010655394514934106
- -0.11442159303036484
- -0.0633674949741989
- -0.08879496314567484
- -0.014477412362618078
- -0.12245954641631233
- -0.10558473456975148
- -0.049489238146641475
- -0.025197226300184238
- -0.10452816309968554
- -0.02786919676812376
- -0.017587772143633995
- -0.11778713213534991
- -0.01653258609503062
- -0.05605769958583524
- -0.015021323270223685
- -0.06498325700316326
- -0.09198450006566747
- -0.09767874885564835
- -0.03052621595027602
- -0.11909472125743317
- 0.04436975914811177
- -0.06128915119344373
- -0.09761845206131552
- -0.01571766301277365
- -0.008212697820563107
- -0.07689801567390858
- -0.041587689078830564
- -0.09217758674400967
- -0.08030819362709452
- -0.032894288851995
- -0.12586428387523985
- -0.1333753419226397
- -0.08537382218475406
- -0.023174004721094696
- 0.8827487983301715
- 0.5056491549250596
- 0.031016223416679527
